### PR TITLE
Implemented CD Override

### PR DESCRIPTION
**Pull request by robocoder99**
New pull request. Cleaned it up.

### CODE REVIEW

**Comment by robocoder99** [comment]
What repo is development for the currently distributed version performed on?

**Comment by SpamWall** [comment]
I think it should be on https://github.com/openrocket/openrocket/tree/unstable, but I’m not seeing any changes to that repo since 4 months ago.  Did it move?  If so, why?

**Comment by SpamWall** [comment]
I've not seen any changes to https://github.com/openrocket/openrocket/tree/unstable in months.  Where is the active branch?

**Comment by teyrana** [comment]
openrocket/unstable IS the official branch, but u havent heard from the
maintainers in a while, so thats why I'm making alternate arrangements.

Once someone with write access returns, we can merge it back in, but theres
still quite a few bugs to fix in the meantime.

**Comment by wcravens** [comment]
I'm constantly lurking.  What's needed?

Wes

**Comment by robocoder99** [comment]
I can do anything as well. Are any further changes needed to merge this? I can also help further development, I love rocketry and I'd love to help this project out.

**Comment by robocoder99** [comment]
Checking in to see if there is anything needed on my end. @wcravens

**Comment by teyrana** [comment]
@robocoder99 
Thanks!  I've merged this patch into my rc0.  
(note: there was a trivial merge conflict in RocketComponentConfig)

**Pull request closed without merging**
