### PR TITLE
Minimal change to re-enable ant builds -- add "script-api-1.0.jar"

### PR DESCRIPTION
**Pull request by teyrana**
This adds the smallest changeset I could find to re-enable the ant builds.  

this should work with:

```
$ ant clean
$ ant jar 
$ java -jar swing/build/jar/OpenRocket.jar
```
(assuming a valid `$JAVA_HOME`)

### CODE REVIEW

**Comment by teyrana** [comment]
Update
---- 
Intellij builds now work.

**Comment by wolsen** [comment]
Ubuntu 20.04 w/ adoptopenjdk 11, builds and loads using ant and the resultant jar file.

3d views throw an exception in the jogl stuff referencing AWT components:

24924          ERROR [AWT-EventQueue-0] n.s.o.g.m.SwingExceptionHandler - Handling uncaught exception on thread=Thread[AWT-EventQueue-0,6,main]
java.lang.NoSuchMethodError: com/jogamp/opengl/awt/GLCanvas.getPeer()Ljava/awt/peer/ComponentPeer; (loaded from classpath:lib/jogl-all.jar by java.net.URLClassLoader@751e6195) called from class com.jogamp.opengl.awt.GLCanvas (loaded from classpath:lib/jogl-all.jar by java.net.URLClassLoader@751e6195).
	at com.jogamp.opengl.awt.GLCanvas.removeNotify(GLCanvas.java:809)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2831)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4801)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2831)
	at java.desktop/javax.swing.JComponent.removeNotify(JComponent.java:4801)
	at java.desktop/java.awt.Container.removeNotify(Container.java:2831)

**Comment by teyrana** [comment]
@wolsen 
Hmmm, I just double checked that on my machine (Win 10), and it works okay.   

I have an Ubuntu 18.04 machine.  I'll try to test it there, but my working there is that the OpenGL issue is an OS / drivers issue.

**Comment by teyrana** [comment]
[edit] Pared back the commits to *just* those required to fix the ant build.

(the other commits work, but are not minimal)

**Comment by wolsen** [comment]
Pulling this branch and building it results in a successful run on Ubuntu 20.04

**Pull request merged**
