### PR TITLE
[#1746] Fix "Seek value of" unit selector in rocket optimizer

### LINKED ISSUE #1746: [Bug] Unit selector in rocket optimization "seek value of" does not work
The unit selector for the "seek value of" spinner is just blank and unresponsive:
image

In addition, I'd also like to increase the spinner width to at least 3 digits, right now it's just one '0'.

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #1746.

### CODE REVIEW

**Comment by hcraigmiller** [comment]
The spinner itself functions as expected with no anomalies found. Not so much for the results.

Parachute (ft/sec):
Optimize Parachute

This appears to be a situtation where each parameter will need to be tested and reported if in error. For example, body tube length optimization **functions perfectly when seeking stability by calibers**, but not so much for stability by inches:

Optimize Stability Inches

Build 1107
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by hcraigmiller** [comment]
After further testing, it appears that the "Seek value of" function is non operable across all attributes.

**Comment by SiboVG** [comment]
Should hopefully be solved now (I didn't encounter the bug because my unit system was set to metric instead of imperial).

**Comment by hcraigmiller** [comment]
Seek value works well; tested about 100 variations on different components. Functions as expected, no anomalies found.

Build 1117
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
> tested about 100 variations on different components

Wow, kudos to you!

**Pull request merged**
