### PR TITLE
Rewrite tube fin and launch lug drag calculations

### LINKED ISSUE #1207: [Bug] Tube Fin flight profile significantly differs from 15.03
TRF user **Neutron95** reported a disparity in flight data for tube fin rockets between 15.03 and the beta release: (https://www.rocketryforum.com/threads/announcement-openrocket-version-22-02-public-beta-is-underway-download-it-now.171295/page-6#post-2248246)

Using the example tube fin rocket included with OR, I ran flight comparisons and confirmed the report

Error Tube_Fin Flight_Profile
.
The flight profiles are significantly different; the same disparity exists with the current unstable.

@neilweinstock ran a comparison using macOS and found no material difference: (https://www.rocketryforum.com/threads/announcement-openrocket-version-22-02-public-beta-is-underway-download-it-now.171295/page-6#post-2248323)

[Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]

### PR DESCRIPTION
**Pull request by JoePfeiffer**
Directly compute drag of tube fins and launch lugs using characteristics of air in tubes, rather than the "three fin approximation" for tube fins and an interpolation from a wire loop to a closed tube for launch lugs.

I am pleasantly surprised by the accuracy of the simulation for the one rocket I have data to compare against.  I expect as we get data from more rockets with tube fins this will need to be refined.  These are the results for the tube fin rocket described in issue #1207.
<table>
<tr><th>Motor</th><th>Flight 1</th><th>Flight 2</th><th>Simulation Results</th>
<tr><td>B6</td><td>349 ft</td><td>355 ft</td><td>377 ft</td></tr>
<tr><td>C6</td><td>694 ft</td><td>697 ft</td><td>689 ft</td></tr>
</table>

This doesn't fix the center of pressure calculations; that's another can of worms.

Fixes #1207

### CODE REVIEW

**Comment by SiboVG** [comment]
colin-mochrie-whos-awesome

**Comment by SiboVG** [comment]
Again, kudos for the hard work @JoePfeiffer! Code LGTM

**Comment by neilweinstock** [comment]
Does this "air in tubes" calculation result in long skinny tubes behaving as if they are solid?

I must say it is tempting to release this just to get feedback from users (even before whatever is done to the CP calculations).

**Comment by JoePfeiffer** [comment]
The pressure drop calculation has a factor for L/(D^5), so the longer it is the greater the pressure drop and the closer it comes to behaving like a closed tube.  It never *fully* behaves like a closed tube.

I'd like for us to tackle some of the bug reports that have come in before next beta (even if that pushes it into next month), but I don't want to wait for the CP fix -- that one's going to be "interesting".

**Pull request merged**
