### PR TITLE
Revised installer configuration to enable desktop icon and file associations

### LINKED ISSUE #1135: Get file associations working correctly on packaged installers
Right now, file association does not seem to work correctly in the packaged installers.  It is unclear what the problem is right now.

This would be a good thing to get working before the final release, if possible.

### PR DESCRIPTION
**Pull request by JoePfeiffer**
The major change is it turns out you need to do the file installation before trying to create the integrations.

Installers to test in https://drive.google.com/drive/folders/1xaUZXnl9q6CDG-CbkqIQqpFrBz63Gw2k?usp=sharing

Fixes #1135

### CODE REVIEW

**Comment by neilweinstock** [comment]
On the Mac it still does not work properly.  I believe behavior is unchanged: double-clicking an ORK file in the Finder will activate OR, but it will not open the file.

So my interpretation is that the file type is correctly associated in the OS, but the OR code is not properly handling whatever sort of message the OS is sending it to open the file.

**Comment by hcraigmiller** [comment]
Worked perfect on windows, desktop icon, file associations, all good.

**Comment by neilweinstock** [comment]
That said... if file associations work correctly only on Windows that would still be a useful improvement for beta 4.  Mac can be fixed later.

**Comment by neilweinstock** [comment]
https://docs.oracle.com/javase/tutorial/deployment/selfContainedApps/fileassociation.html

**Comment by JoePfeiffer** [comment]
They're also working on linux.  Thanks for the link; I'll see if I can use that to get things working on MacOS.  Naturally, that's the only one I can't test on!

**Comment by neilweinstock** [comment]
Here for ya. :)

**Comment by JoePfeiffer** [comment]
Is it successfully creating a desktop icon for MacOS, even if the file association isn't working?

Briefly looking at that web page, it looks like somebody else's conclusion that it'll take some changes in OR itself and a different main method to get associations working.

**Comment by neilweinstock** [comment]
I don't see a desktop icon, but that's not a thing for the Mac so I wouldn't expect it.  I am seeing proper OR icons in the Finder for the .ork files, so that's good.  I think the only remaining issue is the need for the special code in the main method.

**Pull request merged**
