### PR TITLE
[#1893] Add top view option to 2D display

### PR DESCRIPTION
**Pull request by hcraigmiller**
Adds a 2D top view option.

### CODE REVIEW

**Comment by hcraigmiller** [comment]
Something got lost in translation. . . with the exception of the message and the label, it works as expected (I like the suggestion of @SiboVG to keep the side view as the primary view).

Untitled

**Comment by SiboVG** [comment]
> Something got lost in translation. . . with the exception of the message and the label

Was this produced with [openrocket_build_1319](https://github.com/openrocket/openrocket/suites/10001235923/artifacts/485585890)? I can't reproduce it. There was an issue with the translation file, but that was fixed in the last commit.

**Comment by hcraigmiller** [comment]
Perfection again. I wish I had your skill set @SiboVG. Functions as expected, no anomalies found.

Build 1322
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
> Perfection again. I wish I had your skill set @SiboVG.

I don't know, being skilled in Java is both a blessing and a curse.

**Comment by hcraigmiller** [comment]
It's been a great blessing for the development of OpenRocket. Your efforts are much appreciated.

**Comment by neilweinstock** [comment]
How is a top view different from what’s there now?  I won’t ba able to try it until tomorrow at least.

**Comment by wolsen** [comment]
> How is a top view different from what’s there now? I won’t ba able to try it until tomorrow at least.

This was my thought - isn't this the side view with a 90 degree rotation?

Additionally, I think this should be considered post release? I mean, is it strictly necessary?

**Comment by hcraigmiller** [comment]
It's like a 90-degree snap of the 2D view. You can easily switch between the views without trying to get the exact angle on the slider and then have to put it back.

Side-Top

**Comment by SiboVG** [comment]
I had the same initial reaction as @neilweinstock and @wolsen, but have since "seen the light". You can indeed achieve the same effect with using the rotation slider, but the slider is **very often** overlooked (or users don't understand what it does - as was the same for me), and the extra view also has the extra benefit that you can quickly switch between different views, without having to always pin-point the rotation slider to 90°.

**Comment by SiboVG** [comment]
To more easily differentiate between the 2D and 3D views, I added a horizontal separator between the items
image

**Comment by hcraigmiller** [comment]
Nice touch. I think that will be helpful to users.  Functions as expected, no anomalies found.

Build 1326
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by JoePfeiffer** [comment]
Would it be reasonable to move the rotation slider to 90 when switching to top view? I think of the switch as being a 90 rotation; it would also remind users of the slider's existence.

**Comment by hcraigmiller** [comment]
This actually an approach decision that needs to be made. Coming from a background in drafting, the menu order should be Top View, Side View, Back View. That same background suggests that _the default view should be the side view_. So, if the slider is to snap 90 degrees when changing between the top and side views, to which view should the back view be tied. From a drafting standpoint, that would be the side view.

Against that backdrop, there are two approaches, either have the slider stay the same when changing between the top and side view or snap 90 degrees when this change is made. As to the first approach, @SiboVG (correct me if I misunderstood) took the approach that the slider is an X degree rotation from the Y view, so the slider does not change when views are changed.

The second approach would be that the top and side views are 90 degrees in rotation from one another, so the slider should reflect that change. This was my initial thought, but after considering the interplay with the back view, the back view is neither a 90-degree rotation from the top nor side view.

Although snapping the rotation 90 degrees would make the use of the slider more evident, as @JoePfeiffer noted, I wonder if it would also bring with it some level of confusion for the user. My vote would be for not snaping the slider 90 degrees when changing between the top and side view. The slider would merely be an X degree rotation from the Y view.

**Comment by SiboVG** [comment]
I dislike the idea of the 90° value for the top view, because it changes how the rotation slider is supposed to work. It's supposed to give a rotation offset to the current view type. Setting the slider to 90° in the top view makes it feel like the top view is not a dedicated view, but rather a 90° rotated side view. (which it is, but it feels wrong with my - sorry for the subjective argument)

It does bring attention to the rotation slider, but I'd rather stick with the equal rotation value across all view types.

**Comment by neilweinstock** [comment]
I don't think there's a strictly "right" answer here, but I think I agree with @SiboVG, let's leave it at 0 by default.

**Comment by JoePfeiffer** [comment]
To me, it seems like one view is a rotation of the other, so the slider should move.  But I'll bow to you guys.

**Comment by SiboVG** [comment]
Last commit sets the top view as the first view type (makes a bit more sense for the top view to be actually on top). The default view type is still the side view.

image

**Comment by hcraigmiller** [comment]
Looks like this one is done. Nicely done. Functions as expected, no anomalies found.

Build 1347
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Pull request merged**
