### PR TITLE
Add motor designation to motor selection table

### PR DESCRIPTION
**Pull request by SiboVG**
See the discussion in #1729. Users sometimes search motors based on their designation, but the search only works for name-based searches. This PR adds a designation column to the motor selection table (apparently this was also requested by some users).

Screenshot 2022-10-12 at 17 31 18

### CODE REVIEW

**Comment by neilweinstock** [comment]
Where do those designations come from?  Some in the screenshot above I find to be curious.

For example, the 13mm Quest is A3T, but Estes is just A3... I would normally refer to the Estes also as A3T.

**Comment by SiboVG** [comment]
> Where do those designations come from? Some in the screenshot above I find to be curious.
> 
> For example, the 13mm Quest is A3T, but Estes is just A3... I would normally refer to the Estes also as A3T.

Don't know their backstory, but they are the same ones as shown on thrustcurves.org ([Estes A3](https://www.thrustcurve.org/motors/Estes/A3/), [Quest A3](https://www.thrustcurve.org/motors/Quest/A3T/))

**Comment by neilweinstock** [comment]
OK, guess I can't argue with thrustcurve.

**Comment by JoePfeiffer** [comment]
Yes, there's a consistency problem with the designations.  For instance, the "real" designations of the Estes C6 motors are C6-0, C6-3, and C6-5.  thrustcurve lists all these as C6, with several delays.  The Quest A8-3, meanwihle, has a designation of A8-3 (I'm not sure why a search on thrustcurve for C6 turns the Quest A8-3 up, incidentally).

I don't think we really need a designation column in the table; what we need is (1) more robust searching (there was a recent issue that turned out to be caused by searching failing if the user had the propellant designation in the search term) and (2) a checkbox for displaying propellant codes for motors that have them.

**Comment by SiboVG** [comment]
> (2) a checkbox for displaying propellant codes for motors that have them.

Where would the propellant code be shown?

**Comment by JoePfeiffer** [comment]
The manufacturers put it right after average thrust.  So Aerotech calls the G64 a G64W (W for White Lightning). That seems to be consistent for manufacturers that use a propellant code; note that not all of them use one -- I don't think I've ever seen a propellant code on a black powder motor, for instance.  The "T" in A3T above is a case size code that Estes used at one time for their 13mm motors, and apparently Quest still does.

**Comment by neilweinstock** [comment]
Estes still uses the "T" for 13mm motors.

The weird thing here is that in the motor names themselves, the extra letter is added after the *delay*, not after the average thrust.  So you would have an A10-3T or an E20-7W.  But when the delay is not included (e.g. for thrustcurve data) they do just squash the suffix next to the average thrust.

I will further note that on Rocket Reviews, the Estes A3 *is* listed as A3T: https://www.rocketreviews.com/estes-a3t.html.  I would have thought they are getting their data from thrustcurve.org but maybe not.

**Comment by JoePfeiffer** [comment]
Ouch, I stand corrected on both counts.  However, I still believe we should just display <motor class><avg thrust><optional propellant code>.  For the 13mm black powder motors, it wouldn't be hard to display the "T" if the propellant code box is checked if we feel that's valuable.

**Comment by neilweinstock** [comment]
Without any consideration towards implementation, what I would want as a *user* is:
1) Always show me Designation.  I don't care about name.  (Possible exception: micro-maxx, not sure what to do there)
2) Allow me to search without the extra suffix.  E20 should find me E20W and E20 and E20X or whatever.

I can't think of an occasion where it is useful to me to see the names *without* the extra suffix.  And I don't really want to see both of them next to each other since they're almost the same thing, and it looks redundant.

**Comment by hcraigmiller** [comment]
Functions as described; no anomalies found.

I agree with @neilweinstock's view on two points: (1) most users are more interested in the designation than the name and (2) displaying both the name and designation is redundant and wastes precious space within the motor pane.

If both are deemed necessary, perhaps a happy medium is to have a checkbox that switches between the two so that the user can choose which to display.

Build 1091
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by JoePfeiffer** [comment]
I have to say I'm surprised to see the strong preferences you have for the designation -- between its inconsistency between manufacturers, and truly bizarre designations like CTI uses, I'd expect users to want the common name (like I do). Please, let's have a checkbox selecting between them.

**Comment by neilweinstock** [comment]
I think an option to select is fine.  Either way, though, when using designations, search should be able to handle queries where just the name is used (that is, searching for E20 should match E20W).

**Comment by SiboVG** [comment]
Any suggestions on what the checkbox should look like? To me, a checkbox if for enabling/disabling one specific feature, not for switching between options (i.e. replacing the "Name" column with the "Designation" column). So in that regard, a checkbox isn't very intuitive to me. But if you can find the right wording for the checkbox, or a better UI widget, I'm all ears.

**Comment by hcraigmiller** [comment]
Checking one, unchecks the other?

Motor Designation

**Comment by neilweinstock** [comment]
> Checking one, unchecks the other?

In that case ==> radio buttons.  Could work.

**Comment by SiboVG** [comment]
> In that case ==> radio buttons. Could work.

Radio buttons could work. So just a "Name" column, and  radio buttons with something like "Motor name display:", "Common name", and "Designation" (or "Manufacturer designation"?)

**Comment by neilweinstock** [comment]
That's the general idea.  I think I'd say "Motor name column:" and then "Use common name" and "Use manufacturer designation" as the two buttons.  If there's no room for "manufacturer" then leave it out, but I'd include it if there's room.

This is pretty subjective, others may have different preferences here.

**Comment by hcraigmiller** [comment]
I think I would use ThustCurve’s nomenclature, “Common Name” and “Designation.”

**Comment by SiboVG** [comment]
> I think I would use ThustCurve’s nomenclature, “Common Name” (or just “Name”) and “Designation.”

Yes, but I find ThrustCurve's "Designation" label a bit confusing, adding the "Manufacturer" term clears the concept IMO. And the term "designation" is still present, so people who are used to ThrustCurve's nomenclature should still understand it.

**Comment by JoePfeiffer** [comment]
Yes, "Manufacturer's Designation"

**Comment by SiboVG** [comment]
New functionality:

https://user-images.githubusercontent.com/11031519/195698114-e812b682-c249-4738-b5d6-9b6ac85b31a5.mp4

**Comment by neilweinstock** [comment]
That looks pretty good to me.

**Comment by hcraigmiller** [comment]
Functions as expected, no anomalies found. Very nice additional feature.

Build 1096
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Pull request merged**
