### PR TITLE
[#2142] Set length setting as first item

### LINKED ISSUE #2142: Body Tube and Inner Tube config editors are not consistent
image

On Body Tube, "length" appears on top (correct), while on Inner Tube, length appears at bottom (incorrect).

Also, is there a reason Inner Tube doesn't have a "filled" option for wall thickness?  It seems no more or less likely to need this than Body Tube, feels like they ought to be the same, no?

The one clear difference that seems correct is that Body Tube has an "automatic" option for diameter and Inner Tube does not, because it's not applicable.  everything else seems like it ought to be the same.

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #2142.

image

### CODE REVIEW

**Comment by hcraigmiller** [comment]
This should also be done for the tube coupler and engine block.

With that caveat, functions as expected with no anomalous behavior found.

OR Build: 1676
Microsoft Windows 11 Pro; 10.0.22621 Build 22621.1105; Windows Feature Experience Pack 1000.22638.1000.0
Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)

**Comment by SiboVG** [comment]
> This should also be done for the tube coupler and engine block.

Thanks for noticing. The length is now the first property for tube couplers, engine blocks, bulkheads (thickness ~ length) and centering rings (thickness ~ length).

**Comment by neilweinstock** [comment]
Excellent.

**Comment by hcraigmiller** [comment]
Functions as expected, no anomalous behavior found.

OR Build: 1678
Microsoft Windows 11 Pro; 10.0.22621 Build 22621.1105; Windows Feature Experience Pack 1000.22638.1000.0
Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)

**Pull request merged**
