### PR TITLE
Motorfix - fixes motor simulation count for #351

### PR DESCRIPTION
**Pull request by teyrana**
Oneliner which includes booster and pod instancing when simulation motor clusters in pods and boosters.

Fixes issue: #351 

(bundled with a typo fix)

### CODE REVIEW

**Comment by teyrana** [comment]
test failures are due to the upstream change in travis configuration. ( Addressed in PR #350 )

**Comment by ChrisMickelson** [comment]
I've been testing this one and somethings still off. After looking into it,
this.config.getMount().getInstanceCount(); and this.motorCount are still both being set to 1 when there are multiple booster pods. For example, if there are 4 boosters with motors, they should return 4 as is the case with a normal 4x cluster mount.

**Comment by teyrana** [comment]
Hmmm, can you tell me more specifically where you're seeing the error?

And can you send me the .ork file?

**Comment by ChrisMickelson** [comment]
[files.zip](https://github.com/openrocket/openrocket/files/1092394/files.zip)

Here is a zip of two files:
parallel_test_A.ork - simple rocket with normal cluster of 4 F26s
parallel_test_B.ork - same rocket but instead with 4 boosters, each with an F26.

These should perform pretty close but one only goes to 600ft, and the other gets up to 3300ft.

Also, if you export the simulation into a .csv file, you can see the thrust is consistent with a single motor versus 4x as with the normal cluster.

As another test, monitored the values for this.config.getMount().getInstanceCount(); and this.motorCount by just printing their values with System.out.println(). Their value was 4 with the cluster, but 1 with the booster pods.

**Comment by teyrana** [comment]
@ChrisMickelson 
Ah! Found my mistake.  Corrected, and resubmitted in PR #354.  (to eliminate erroneous commit in PR ;)

**Pull request closed without merging**
