### PR TITLE
[fixes #1020] Fix minor issues FileChooser 'Export CSV' FinSet

### LINKED ISSUE #1020: Small issues with FileChooser of Freeform fin 'Export shape to CSV'
When trying to export the fin shape of a Freeform fin to CSV by going into the Freeform editor into the 'Shape' tab and clicking 'Export CSV', the JFileChooser has some beauty mistakes that should be resolved:

- the startup directory is just the home directory of your computer. In other JFileChoosers in OR (e.g. when saving your design), OR checks what the last used directory was and sets that as the startup directory for the JFileChooser
- the file format is just 'All Files'; also when you have saved the file, you have no file format. It should have 'Comma Separated Files (*.csv)' as file format, just as with exporting simulation data to CSV

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #1020, fixing some minor bugs in the FileChooser of the 'Export CSV' of a FinSet. Additionally, I also added one translation key and renamed some others (which was marked in the code as a 'TODO').

Here is a [jar file](https://drive.google.com/file/d/1rzFQSNNQpyZcF_dy8uXVM8rvHin343VB/view?usp=sharing) for testing.

### CODE REVIEW

**Comment by hcraigmiller** [comment]
In testing OpenRocket-1020.jar, if you save a file "Test" then the .csv extension is properly added. But, if you save a file "Test.Rev.01" or "Test.01"then the .csv extension is not added. Apparently, if the filename contains a "." then the .csv extension is omitted when the file is saved.

**Comment by SiboVG** [comment]
> In testing OpenRocket-1020.jar, if you save a file "Test" then the .csv extension is properly added. But, if you save a file "Test.Rev.01" or "Test.01"then the .csv extension is not added. Apparently, if the filename contains a "." then the .csv extension is omitted when the file is saved.

Latest commit fixes this issue + also enforces FileHelper.forceExtension on other JFileChoosers to avoid the confusion of having different saved file extensions than what was selected as a file format in the FileChooser.

I have updated the original jar file with the changes of the latest commit.

**Comment by hcraigmiller** [comment]
Very nice... no anomalies found.

**Comment by SiboVG** [comment]
Good catch @neilweinstock! The current implementation of FileHelper.forceExtension was indeed that it just checks whether the filename ended with e.g. 'pdf', instead of looking what the full file extension was. The latest commit fixes the issue.

Here is a [jar file](https://drive.google.com/file/d/19DWR6IIaaR1ie3mhM06l8K7h5jLM-oMt/view?usp=sharing) for testing.

**Comment by neilweinstock** [comment]
Looks good from here.

**Comment by neilweinstock** [comment]
I've browsed through the commits and am going to take the liberty of merging and closing this one myself.

**Pull request merged**
