### PR TITLE
[fix] 2D Rocket Figure will now display off-axis CoM and CoP

### PR DESCRIPTION
**Pull request by teyrana**
This does _NOT_ affect any calculations -- it just more accurately displays those same values on the 2D view.

This also means that 2d views and 3d views display these values more similarly.

### CODE REVIEW

**Comment by teyrana** [comment]
( Spin off from #641, #654 )

**Comment by JoePfeiffer** [comment]
I think you're right, we need to do this -- we may decide to pin the CP to Y=Z=0 in some (most?) cases, but the figures need to show whatever we end up calculating.

But, in 2D view, as I rotate the rocket the CP stays stationary instead of rotating with the rocket.

**Comment by JoePfeiffer** [comment]
This isn't rotating the CP with the rocket -- with the attached design (which is the off-axis CP example I created before with the nose cone removed so the CP is *really* off axis) the CP just sits at the top of the body tube as the rocket is rotated.
[two-fins.ork.zip](https://github.com/openrocket/openrocket/files/4595955/two-fins.ork.zip)

**Comment by teyrana** [comment]
(display now respects the rotation slider)

**Comment by JoePfeiffer** [comment]
That's got it.  My vote is we merge this so we actually see what we're calculating (whatever that turns out to be).

**Pull request merged**
