### PR TITLE
New installer config for 24.12

### PR DESCRIPTION
**Pull request by JoePfeiffer**
, including both amd64 and aarch64 architectures, and accounting for changes from gradle build environment.

Assumes jar file is in build/libs/OpenRocket.jar

Note -- in testing, the Windows amd64 installer works. The Linux amd64 installer installs OR, but attempting to run it gives the following stack trace (apologies for the screenshot; I don't seem to be able to copy the text from the window):
stacktrace

### CODE REVIEW

**Comment by neilweinstock** [comment]
What is the purpose and/or benefit of an AMD64 build?

**Comment by JoePfeiffer** [comment]
> What is the purpose and/or benefit of an AMD64 build?

Do you mean an Arm (Install4j wants to call it aarch64, and I have no fervent objections) build? AMD64 is the only architecture we've supported on Linux and Windows up until now, and is the architecture supported by macOS Intel. It's aarch64 that's new.

**Comment by neilweinstock** [comment]
> > What is the purpose and/or benefit of an AMD64 build?
> 
> Do you mean an Arm (Install4j wants to call it aarch64, and I have no fervent objections) build? AMD64 is the only architecture we've supported on Linux and Windows up until now, and is the architecture supported by macOS Intel. It's aarch64 that's new.

Oh, I'd have thought we were calling it X86 or X86_64 or somesuch.  Never mind.

**Comment by JoePfeiffer** [comment]
A bit more info -- the system installed jvm (from Debian repositories) runs the command line constructed in the launcher with no issues. The jvm bundled in the installer shows the behavior described above.

joseph@valiant$ java --version
openjdk 17.0.13 2024-10-15
OpenJDK Runtime Environment (build 17.0.13+11-Debian-2)
OpenJDK 64-Bit Server VM (build 17.0.13+11-Debian-2, mixed mode, sharing)

joseph@valiant$ jre/bin/java --version
openjdk 17.0.13 2024-10-15 LTS
OpenJDK Runtime Environment (build 17.0.13+12-LTS)
OpenJDK 64-Bit Server VM (build 17.0.13+12-LTS, mixed mode)

**Comment by SiboVG** [comment]
I have updated the `DS_Store` to the new version (so the macOS installer displays correctly) + added a helper script to automatically generate the new DS_Store in the future. I've also updated the install4j config to install4j version 11. @JoePfeiffer you will need to upgrade your install4j version, I've sent you a mail with the upgraded license key.

Still haven't looked into the amd64 bug.

**Comment by SiboVG** [comment]
Ha, interesting, I actually think the amd64 bug is related to #2584. It looks like the unit tests are failing because of an issue with the rocket substitutor.

**Comment by SiboVG** [comment]
Hm, I don't have an AMD64 Linux build available, I can only run ARM64 on my MacBook, so I can't really debug this issue...

@JoePfeiffer does the exception also occur when running directly from the JAR or only from the packaged installer?

**Comment by JoePfeiffer** [comment]
> Hm, I don't have an AMD64 Linux build available, I can only run ARM64 on my MacBook, so I can't really debug this issue...
> 
> @JoePfeiffer does the exception also occur when running directly from the JAR or only from the packaged installer?

That's what I'm finding craziest about it. It's the java in the packaged installer.  If I duplicate the command line at the bottom of the installed script but use my system java, it works. If I use the Java from the installer and just run the jar file, i get the guice error.

**Comment by SiboVG** [comment]
> That's what I'm finding craziest about it. It's the java in the packaged installer. If I duplicate the command line at the bottom of the installed script but use my system java, it works. If I use the Java from the installer and just run the jar file, i get the guice error.

Did you test different JRE configurations in install4j?

**Comment by JoePfeiffer** [comment]
> > That's what I'm finding craziest about it. It's the java in the packaged installer. If I duplicate the command line at the bottom of the installed script but use my system java, it works. If I use the Java from the installer and just run the jar file, i get the guice error.
> 
> Did you test different JRE configurations in install4j?
That's next.

**Pull request merged**
