### PR TITLE
[fixes #868] Fin tabs correctly adjust their location when the fin tab _length_ is changed.

### LINKED ISSUE #868: Fin tab length changes are referenced only to the top of the parent component
Rather than referencing the change in length from the selected relative to position, the change is always referenced to the top of the parent component. The design file used is a Simple model rocket.

00 Automatic

Although only the trapezoidal fin has been used above, the same issue exists for all fin types, and for both fins on body tubes and fins on transitions.

### PR DESCRIPTION
**Pull request by teyrana**
This fix addresses Issue #868, and may help with #865.

Basically, the update function in fin set wasn't checking the fin-tab properties, so I inserted a call to `validateFinTab()`.   It appears to work, now, according to the description / images in #868.    Thanks to @hcraigmiller for the high-quality bug report 👍 

@JoePfeiffer I got you fam.

### CODE REVIEW

**Comment by JoePfeiffer** [comment]
Can't look at it carefully right now -- could this bring #527 (fin tabs loaded incorrectly) back? Problem there was validating the tabs in the process of reading a .ork file.

**Comment by teyrana** [comment]
@JoePfeiffer 
Ah. Thanks for the heads up -- yes, it restores the #527 issue behavior.

**Comment by teyrana** [comment]
After looking at it in more detail, the problem is that basically we want to validate from the gui, but not while loading from a file....

What do we think of happing a validate=true|false parameter to the `setTab*()` functions?

**Comment by JoePfeiffer** [comment]
I think we explored that option in the discussion of PR #530.  

It isn't immediately obvious to me that the solution here is validation -- if the fin tab is set relative to the parent's aft end, adjusting the length should just move the forward end.  It doesn't seem like revalidating will necessarily make that happen -- won't it let the aft end of the tab move until it fails validation, then move the forward end?

**Comment by teyrana** [comment]
Okay, I think I've massaged it to resolve both issues. 

Re-reading the discussion on #530 I'm not clear on why we dropped all that validation on UI modification.    Do we want all that validation, at all? 

(for instance -- fin tabs that extend in front or in back of their fins)

I mean, if nobody's going to complain about it, I'm fine with that.... but I do remember complaints about some of it.

Maybe the question should be "which validations" do we want the UI to enforce?

Also, I've split the `validateFinTab` function into `validateFinTabPosition` and ...Length and ..Height functions.

**Comment by teyrana** [comment]
My tests are:
1. Unit tests (of course)
2. Opening a simple rocket with 10-fins and 10-inch tabs.   (the default chord is 5in)

**Comment by JoePfeiffer** [comment]
On dropping validation, it's the question of how much we want to ensure users only do things make sense vs. letting them do what they want.  I remember us as thinking that since there's an "automatic" option that tries to do them most reasonable thing, if they want to change from that they probably have a reason.

**Comment by JoePfeiffer** [comment]
Finally back in town...  I created the attached ork file (as usual, filename changed to .txt to get around github), and with this PR I don't see any change in the display when I change tab length or height, or click "calculate automatically".  If I change tab position, that change and any prior changes are visible immediately. It does appear to be adjusting length relative to the specified part (front, back, middle) of fin now, as it should be.

I guess I'm happy either way on validation.

[fintest.txt](https://github.com/openrocket/openrocket/files/5758491/fintest.txt)

**Comment by teyrana** [comment]
Ooooph, it's been a while.   iirc, this worked when submitted, but I haven't tested it in a while.   I'll take a look this weekend.

**Comment by teyrana** [comment]
Okay, I thiiiiiink this works, relative to what I thought the issue was.  But someone else should probably test it.

**Comment by hcraigmiller** [comment]
Can you provide a .jar file for testing?

**Comment by teyrana** [comment]
@hcraigmiller 
https://drive.google.com/file/d/1o-zqxMqAFlhZFsTTxldMWtsdN54cR67S/view?usp=sharing

**Comment by hcraigmiller** [comment]
OpenRocket-pull-869.jar fixes Issues #868 and #925. Anomalies remain with Issue #865, but the cross-over with Issues #868 and #925 is fixed; where Issue #865 is completely separate from this issue, I will post those anomalies after this PR is merged.

It appears that this PR is complete, no anomalies found.

[OS Windows 10 Pro service pack 120.2212.2020.0 with Java version 11.0.9 2020-10-20 LTS]

**Pull request merged**
