### PR TITLE
Update build.xml to java8 #414

### PR DESCRIPTION
**Pull request by SpamWall**
Ready to run once Travis is using JVM 1.8

### CODE REVIEW

**Comment by wcravens** [comment]
THere are several commits in here of the form 'Merge remote-tracking branch 'upstream/unstable' into unstable'.  This shouldn't be necessary.  When you pull (fetch/merge) the remote 'unstable' branch locally it shouldn't be creating new commits.

Please let me know what environment / tools that you are using because I think that they are incorrectly setup to do a 'no fast forward' merge of the base branches and this isn't a good idea.

**Comment by SpamWall** [comment]
This is my first time using GITHub on an open-source project so I may be approaching this wrong – please advise me of the correct procedure.  When I am working on a change, I branch from local/unstable and do my work there – let’s call this branch “Fix_Screen_#444”.  When a change in merged into openrocket/openrocket unstable (i.e. upstream/unstable) I checkout my local/unstable branch on my PC and merge upstream/unstable into it.  Next, I push my local/unstable to my origin/unstable so my repo is up-to-date with upstream then checkout “Fix_Screen_#444” and merge local/unstable in to it.  When I am done with the fix I push the work branch (“Fix_Screen_#444”) to origin/Fix_Screen_#444 and generate the pull request to openrocket/openrocket.

 

These merges and associated commits generate the comments.  I use IntelliJ for my IDE, but I typically do the merges from GitBash.  I have read some about the fast-forward merge but I don’t know if it is doing that or even how to make it… I thought it did that automatically if it could.

 

I tend to commit every 10-15 minutes during development and those commits go with the push to my origin and then on to the pull-request.  I would love to get rid of them and just have the last commit message go with the PR.

 

Craig

**Comment by wcravens** [comment]
Hi Craig,

I know that it feels awkward, but when the 'root' branch of your feature
(unstable in our case), moves on you have to think carefully about rather
or not you need those new features in your feature branch.  If you
absolutely need them then you need to 'git rebase' your changes on top of
the root brach rather than merging the root branch into your feature
branch.  This is somewhat counter-intuitive at first (or for a long time)
but it's important. Mainline branches like master and unstable should
always be merged into from feature branches rather than merged into other
branches.  Arguable the only commits in master and unstable should be the
merges from feature branches (in masters case it should only be merges from
unstable, but that's a different story).  We are long overdue for
documenting and adopting a git workflow but we have adopted this much.

I almost always have the luxury of personal contact and a whiteboard to
explain git topics like this.  So, I would be more than happy to setup a
conference call / video chat to help explain these subtle idiomatic
practices in more detail if you would like.  Just let me know.

Thanks,

Wes

**Comment by SpamWall** [comment]
I don’t use any parameters.  I follow the steps in https://help.github.com/articles/syncing-a-fork/, substituting unstable for master.  I have not modified my .gitconfig either.

 

I have stayed away from rebasing because of the “The Golden Rule of Rebasing” mentioned in this documentation - https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by SpamWall** [comment]
If I chose to wait until I am done to merge upstream/unstable changes into my code I run into a LOT of merge conflicts.  It seems better to me to merge these into my code as they are put into unstable since waiting can create large deviations that are hard or even impossible to merge once I issue the PR.

 

I would love to take you up on the offer of a white board session to learn the process here.  Until then I will rebase my work branch onto my unstable branch after pulling the upstream/unstable (right?)

 

I thought the overall concept was that, when I forked OR/OR into my own Github repo I worked exclusively out of my clone of my fork and that I would pull from OR/OR to my local then push those changes back to my Github repo to keep the two in synch.  My work branch in my Github repo would become the PR I sent to OR.  Is this incorrect?

 

Craig

**Comment by teyrana** [comment]
> If I chose to wait until I am done to merge upstream/unstable changes
into my code I run into a LOT of merge conflicts.
> It seems better to me to merge these into my code as they are put into
unstable since waiting can create large deviations that are hard or even
impossible to
> merge once I issue the PR.

Okay, THIS may be worth talking about. *why* are you running into so many
merge conflicts?  Normal development on OR (especially in the last month or
two has been slow, and relatively isolated to specific trouble spots.)  Why
are your changes so widespread that they're running into all those other
changes?

> I thought the overall concept was that, when I forked OR/OR into my own
Github repo I worked exclusively out of my clone of my fork and that I
would pull from OR/OR to my local then push those changes back to my Github
repo to keep the two in synch. My work branch in my
> Github repo would become the PR I sent to OR. Is this incorrect?

Sure! This summary is true.  However, it skips over many important steps
about how to get from here to there.


Addendum:
I'm not really arguing for rebasing.  There is always another (if more
time- and labor-intensive) way to accomplish the same thing.  BUT, if
you're going to do it, let's do it right :D

> I have stayed away from rebasing because of the “The Golden Rule of
Rebasing” mentioned in this documentation -
https://www.atlassian.com/git/tutorials/merging-vs-rebasing

That is good advice!  However, please note the phrasing:

> The golden rule of 'git rebase' is to never use it on *public *branches.


Emphasis from *original*.  The PUBLIC part is important here.  If you want
to commit every 30 seconds, that's your deal... but if you squash those
commits to just the *important* changes, the rest of us will have a much
easier time understanding what your intent is, AND you will have an easier
time convincing the maintainers that your patch is worth committing /
merging.

For instance, both of these commits (from one of your pull requests) seem
to repeat many of the same changes?  Prime candidate for rebase /
squash-ing.
1)
https://github.com/openrocket/openrocket/pull/415/commits/f13c65a000563ab933dbb59c3fe9609d01bbbb18
2)
https://github.com/openrocket/openrocket/pull/415/commits/f7f5fd0c3472bc6c6b1cd4410cea43c86a9dd449





Daniel Williams
equipoise@gmail.com
858-220-8134 (Mobile)
github.com/teyrana
<https://github.com/teyrana>LinkedIn
<https://www.linkedin.com/in/williamsdm>

**Comment by SpamWall** [comment]
Here’s a great example.  I just rebased my development onto upstream/unstable.  I am working on changes to the Scale dialog.  The file net.sf.openrocket.gui.dialogs.ScaleDialog, which is the main file I am working in, had so many merge conflicts for a different change that it was just a mess after the merge.  I find that encapsulation is  very poor in large parts of the codebase which means changes are rarely confined to a package.  The ScaleDialog.java file has so many errors after the merge that I just need to throw away my work and start over.

 

Craig

**Comment by teyrana** [comment]
Umm....    I don't see a link, or pasted code sample.

Should I?


Daniel Williams
equipoise@gmail.com
858-220-8134 (Mobile)
github.com/teyrana
<https://github.com/teyrana>LinkedIn
<https://www.linkedin.com/in/williamsdm>

**Comment by wcravens** [comment]
As per @teyrana "p.s. we can probably close #415; as it no longer applies (the travis CI is already configured to use java 8, by #421)"

**Pull request closed without merging**
