### PR TITLE
Upgrade to guice-4.1 and guice-multibindings-4.1

### PR DESCRIPTION
**Pull request by tibbe**
This also requires adding guava, which is no longer shipped with guice.

### CODE REVIEW

**Comment by tibbe** [comment]
I've tested on Windows 10 against both JDK 8 & 9. HiDPI now works with JDK 9 (the --permit-illegal-access VM flag is required for JDK 9 at the moment).

Before:

jdk-8

After:

jdk-9

**Comment by tibbe** [comment]
The build failure is a bit perplexing. I'm not sure why ant wouldn't find one of its jars all of a sudden.

**Comment by tibbe** [comment]
The ant failure seems related to this: https://github.com/travis-ci/travis-ci/issues/7706

**Comment by tibbe** [comment]
I see other pull request builds have failed for the same reason. Perhaps we should merge even with this failure. The jar builds fine.

**Comment by teyrana** [comment]
@tibbe 
FYI, This error is causing issues on other openrocket branches and PRs as well.

**Comment by teyrana** [comment]
@tibbe 
Also, PR #350 addresses some of the Travis build issues, by triggering a build on Ubuntu 14.04 (instead of Ubuntu 12.04 (!!))

**Comment by tibbe** [comment]
I expect all of our builds to run into problems untill travis-ci/travis-ci#7706 is fixed.

**Comment by tibbe** [comment]
Closing and re-opening to trigger Travis re-run.

**Comment by teyrana** [comment]
Yea, no doubt fixing https://github.com/travis-ci/travis-ci/issues/7706 would fix our issue, but their repo has 1.2k+ issues, so I'm not holding my breath.  Heeeeence the workaround.

Also, to clarify, once #350 is accepted and merged, you'll have to merge / rebase onto it to fix the tests here.

**Comment by teyrana** [comment]
The project has upgraded juice and guava libraries as part of #556 -- including functional java 11 support.
This pull request is now superseded.

**Pull request closed without merging**
