### PR TITLE
Illegal multiplier value, mul=1001.33 #121

### PR DESCRIPTION
**Pull request by SpamWall**
Fixed this defect by putting up an error dialog instead of throwing an exception.

### CODE REVIEW

**Comment by SpamWall** [comment]
Looking at the CI output, it looks like the JVM is still pointing to a 1.7 Java version.  If we are going to target Java 1.8, can someone update the JAVA_HOME on the CI machine to a 1.8 JVM?

**Comment by wcravens** [comment]
I'll merge this when we decide what to do about the build failing.  I think that Dan set up travis so I'll let him figure out what to do.

**Comment by SpamWall** [comment]
From the error message on the build server, it is still using the Java 7 JVM.  I changed the Ant file to use Java 8 since that is what the group said was the current target JVM.  I think pointing JAVA_HOME at a Java 8 JVM should fix things.

Craig

⁣Sent from TypeApp ​

**Comment by teyrana** [comment]
@wcravens @SpamWall   
The travis issue was fixed months ago.  If the build fails, now it's because of a recent change.  
(probably in build.xml where the fix was ;)

**Comment by teyrana** [comment]
Re: building with 1.7 vs 1.8.
One can build with a higher JVM, against the target bytecode @ 1.7 -- the setting allows backwards compatibility.  

If we no longer wish to support 1.7, I'm neutral on that.  But it's not a Travis limitation.

**Comment by teyrana** [comment]
Also, let's split all these separate issues into separate Pull-Requests.  

Updating the Scale Dialog is not relating to changing the build.xml file....

**Comment by SpamWall** [comment]
I agree that it is not a limitation of Travis – I didn’t mean to imply that, but Travis is configured (JAVA_HOME) to use a 1.7 JVM.  I suggest installing a 1.8 JVM on Travis and resetting the JAVA_HOME to point to it.  If we are supporting Java 1.8 we should set the language level to 1.8 also IMO.

 

Craig

**Comment by SpamWall** [comment]
Ok.  I'll split them.

⁣Sent from TypeApp ​

**Comment by SpamWall** [comment]
The Travis output says it is using  1.7 JVM.

⁣Sent from TypeApp ​

**Comment by SpamWall** [comment]
I set the language and compiler levels back to 1.7 and removed the 1.8 language features I had used.  #121 now passes on Travis.

 

Should I submit another PR for the 1.8 upgrade of the build.xml files now or wait until the changes are made to Travis?

 

Craig

**Comment by wcravens** [comment]
This PR has a merge conflict.

**Comment by teyrana** [comment]
Closed due to inactivity.
And the submitter deleted the originating repository.
And the PR doesn't reference a known issue.

**Pull request closed without merging**
