### PR TITLE
Fix 1079

### PR DESCRIPTION
**Pull request by JoePfeiffer**
Modify DescriptionArea to follow hyperlinks, both "normal" and within current jar file.
Update About dialog
Update License dialog
Update copyright year.

### CODE REVIEW

**Comment by JoePfeiffer** [comment]
I'd *really* appreciate input from people who know something about how this stuff should be put together!
Test jar file at https://drive.google.com/file/d/1KHTuVrZhdBY8EX8pD6_KSO9FO0KdtZ7A/view?usp=sharing

**Comment by JoePfeiffer** [comment]
Another try at a jar is at https://drive.google.com/file/d/1PTPMcno5TqIYrRQ0uH6uqYu0gRRk6SyQ/view?usp=sharing

**Comment by hcraigmiller** [comment]
It's looking pretty good. There are a few things I noticed.
1. On the copyright line, add a space between “2022" and “Sampo”.
2. On reflection, I think the BSD 2-Clause License should be moved up to just below the "GNU GENERAL PUBLIC LICENSE". That way, the licenses for the code most used by OpenRocket are at the top.
3. To be consistent, "Bitstream Vera Font License" should be changed to BITSREAM VERA FONT LICENSE".
4. Delete the blank line between "see" and "https://www.gnu.org/licenses/gpl-3.0.html".
5. Delete the blank line between "OpenRocket developers may be contacted electronically at:" and "mailto:openrocket-devel@lists.sourceforge.net".
6. Delete the blank line between "You may also obtain a copy of the License at: " and "http://www.apache.org/licenses/LICENSE-2.0".
7. Delete one of the two blank lines between "http://www.apache.org/licenses/LICENSE-2.0" and "OpenRocket uses the Work".
8. Change "Ant product also includes software developed" to "Ant also includes software developed".
9. Delete blank line between "Ant product also includes software developed by: " and "the W3C Consortium (http://www.w3c.org/)".
10. Add a blank line between "Bitstream Vera is a trademark of Bitstream, Inc." and "DejaVu changes are in the public domain".

As to functionality, no anomalies found.
[Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]

**Comment by JoePfeiffer** [comment]
> It's looking pretty good. There are a few things I noticed.
> 
>     1. On the copyright line, add a space between “2022" and “Sampo”.
Got it
>     2. On reflection, I think the BSD 2-Clause License should be moved up to just below the "GNU GENERAL PUBLIC >LICENSE". That way, the licenses for the code most used by OpenRocket is at the top.
The component database is written to go with OR, so I think it's appropriate that its license (ie Apache) comes second
>     3. To be consistent, "Bitstream Vera Font License" should be changed to "BITSREAM VERA FONT LICENSE".
Got it
>     4. Delete the blank line between "see" and "https://www.gnu.org/licenses/gpl-3.0.html".
Got it.
>     5. Delete the blank line between "OpenRocket developers may be contacted electronically at:" and "mailto:[openrocket-devel@lists.sourceforge.net](mailto:openrocket-devel@lists.sourceforge.net)".
Got it.  Also added the Slack channel
>     6. Delete the blank line between "You may also obtain a copy of the License at: " and "http://www.apache.org/licenses/LICENSE-2.0".
Got it.  Also tried to make the wording more consistent.
>     7. Delete one of the two blank lines between "http://www.apache.org/licenses/LICENSE-2.0" and "OpenRocket uses the Work".
Got it
>     8. Change "Ant product also includes software developed" to "Ant also includes software developed".
Ah, much nicer
>     9. Delete blank line between "Ant product also includes software developed by: " and "the W3C Consortium (http://www.w3c.org/)".
Unfortunately, creating a bulleted list seems to insert that blank line.
>     10. Add a blank line between "Bitstream Vera is a trademark of Bitstream, Inc." and "DejaVu changes are in the public domain".
Those three copyright terms (including the public domain notice) seem closely enough related I think they should stay togeter.
> 
> As to functionality, no anomalies found. [Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]

Also added project pages for the fonts and commonmark library.  

New jar at https://drive.google.com/file/d/1AMoVCu_OEWmbBVXnlo8MuZ49kLds09Mr/view?usp=sharing

**Comment by hcraigmiller** [comment]
It looks very nice. I found two inoperable links:

1. Licensed under the Apache License, Version 2.0 (the "License"); you may not use this work except in compliance with the License. You may view the License **[here]**. You may also obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0

2. Licensed according to the Bitstream Vera Font License which may be found **[here]**. You may also obtain a copy of the License at https://github.com/dejavu-fonts/dejavu-fonts/blob/master/LICENSE

In each "here" instance above, its searching for an app to open a .tmp file. It may be that the file extension (.txt) is missing, "LICENSE" instead of "LICENSE.TXT", but just guessing.

All of the other links work.

**Comment by JoePfeiffer** [comment]
> In each "here" instance above, its searching for an app to open a .tmp file. It may be that the file extension (.txt) is missing, "LICENSE" instead of "LICENSE.TXT", but just guessing.

Just to double-check -- the link to the GPL at "The license may be viewed here." is working? Is it opening with a browser tab or window, or with some sort of text editor/viewer?

I think what you're seeing is an issue with your desktop -- the internal links all end up extracting the file from the .jar, making a temporary file with a name based on the name of the resource in the .jar, and turning it over to your desktop to figure out what to do with it.  But if your desktop is doing something reasonable with a .txt file, it's easy enough for me to change the extension on the temporary file.

**Comment by hcraigmiller** [comment]
> Just to double-check -- the link to the GPL at "The license may be viewed here." is working? 

Yes, that link is working.

> Is it opening with a browser tab or window, or with some sort of text editor/viewer?

It is opening in the Notepad application.

> But if your desktop is doing something reasonable with a .txt file, it's easy enough for me to change the extension on the temporary file.

If I copy and paste all three "here" lines to a text editor, the GNU is "LICENSE.TXT" and the others are only "LICENSE" without the .txt extension. I think that the lack of the extension is what is causing the problem.

**Comment by JoePfeiffer** [comment]
This one appends a .txt to constructed filenames that have no extension.

Test jar at https://drive.google.com/file/d/1tCWMvJ2aAVuxuTrF8__unwtX5tlydCQg/view?usp=sharing

**Comment by hcraigmiller** [comment]
Looks great, all links are fully functional, no anomalies found.
[Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]

**Comment by hcraigmiller** [comment]
I just saw that the opening splash page needs to be changed from "2021" to "2022".

**Comment by JoePfeiffer** [comment]
That's a different issue, but yeah, has to be done.  Hmm, I didn't realize the text on the splash screen is created by hand...  or that the splashscreen itself has to be manually copied into its final location...  I'll be opening two issues for this.

**Comment by SiboVG** [comment]
@JoePfeiffer would it be possible to put the LICENSE.txt file either inside the root directory or the .github directory? That way, GitHub automatically recognizes it and puts the license details on the front page of the GitHub repo.

(I wasn't even aware that our license file was located there, that's why I created a new one in PR #1091, but I will delete it from that PR, since it's not necessary anymore)

**Comment by hcraigmiller** [comment]
All links are fully functional, no anomalies found.
[Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]

**Pull request merged**
