### PR TITLE
Center rocket in side-view 2d renderings

### PR DESCRIPTION
**Pull request by wolsen**
Center the rocket within the side-view 2d renderings. This is similar to
how the side-view is rendered in 15.03 version.

Signed-off-by: Billy Olsen <billy.olsen@gmail.com>

### CODE REVIEW

**Comment by teyrana** [comment]
I've not seen this issue, and I was fixing bugs in this code last week.   Are screenshots of the bug and/or the fix behavior available anywhere?

**Comment by wolsen** [comment]
Ah yeah, I'll get some screenshots tomorrow. I looked at this based off some comments from @neilweinstock in slack. If you look at 15.03 the rockets are centered in the side profile and in unstable they are left aligned.

I can also raise a proper bug to track it.

**Comment by neilweinstock** [comment]
There was #502 but that was closed recently.

**Comment by teyrana** [comment]
Ahh, so is that last screenshot the issue this PR is addressing?  Is that what were talking about?

**Comment by neilweinstock** [comment]
@teyrana PR #686 claimed to fix this... should we not still be seeing it?

**Comment by teyrana** [comment]
@neilweinstock 
Issue #502 had multiple issues inside it.   PR #686 fixed the first issue -- fins going out of bounds -- but (apparently) not address the later issue.

**Comment by neilweinstock** [comment]
Actually #502 was only about the above issue.  Should we reopen it just so we can now close it again? :)

**Comment by wolsen** [comment]
> Ahh, so is that last screenshot the issue this PR is addressing? Is that what were talking about?

Yes, that's what this issue is addressing. Here's some screen caps of before and after this change.

**Before Change**
or-nose-cone-unstable-left-justified

**After change**
or-nose-cone-unstable+fix

**Comment by wolsen** [comment]
Opened #722 for this specific one as a spinoff of #502

**Comment by teyrana** [comment]
@neilweinstock 
Yea, it's one of those complicated things where what looks like the same issue can be caused my multiple issues on the back end.  
It's imperfect, and basically something fell through the cracks.  I think we're handling it the right way, though :)

@wolsen
I did some spot checks -- looks good!

**Comment by neilweinstock** [comment]
Does this also fix the centering of the rocket in the side view inside the Rocket Optimization dialog?

**Pull request merged**
