### PR TITLE
Updated Pods Example Rocket

### PR DESCRIPTION
**Pull request by neilweinstock**
Totally new updated Pods Example Rocket.

### CODE REVIEW

**Comment by hcraigmiller** [comment]
Functions as expected, no anomalies found.

Question. Should the name "Pods example" be changed if a powered pods example is added (should a powered pod example be added so that users can see how to configure the motors/recover in pods)?

Build 1327
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by neilweinstock** [comment]
Let's wait on this until the tail cone PR is merged... then I'll change the tail cones on this design to show that feature as well.

**Comment by hcraigmiller** [comment]
Discontinuity error.

D_E

Auto base diameter fixes the issue.

**Comment by neilweinstock** [comment]
Fixed.  I was trying to use a library component, but it seems hopeless.  I still think we should rethink how discontinuity errors are checked.   But that is for the future.

**Comment by hcraigmiller** [comment]
Everything looks good. Functions as expected, no anomalies found.

Build 1343
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Pull request merged**
