### PR TITLE
Process entire part tree when finding active contexts

### PR DESCRIPTION
**Pull request by JoePfeiffer**
When processing the component tree to find active instances of components, it wasn't processing subtrees of inactive components.  The result was that in finding the drag for detached boosters, the drag was calculated as 0.
Notice that if you run the .ork that resulted in filing the issue after this applying this fix, you get a truly bizarre simulation result -- that's actually what we'd expect, since the boosters are separating at launch and have no fins so they're unstable. The attached ork is the same as that one, but uses A8-0's in the boosters and separates at motor ejection charge.
[Pod-Boosters-2.ork.txt](https://github.com/openrocket/openrocket/files/8234582/Pod-Boosters-2.ork.txt)

### CODE REVIEW

**Comment by JoePfeiffer** [comment]
Also some improvements to handling InstanceMap.

**Comment by SiboVG** [comment]
Good work done here @JoePfeiffer, thanks! Is this PR related to #1229?

**Comment by JoePfeiffer** [comment]
> Good work done here @JoePfeiffer, thanks! Is this PR related to #1229?

Yes, I should have marked it as fixing #1229.

**Comment by neilweinstock** [comment]
This is a major fix.  Beta 2 is going to be really good.

**Pull request merged**
