### PR TITLE
Updated release notes for beta 3

### PR DESCRIPTION
**Pull request by neilweinstock**
Will keep updating until the last minute.

### CODE REVIEW

**Comment by JoePfeiffer** [comment]
Please specify that it's just the tube fin drag calculations that are fixed (the stability calculations aren't yet)

**Comment by neilweinstock** [comment]
Ah, OK.  What is the exact state of the stability calculations?

**Comment by neilweinstock** [comment]
@JoePfeiffer please see if you're happy with the update.

**Comment by JoePfeiffer** [comment]
Yes, that looks good to me.

**Comment by JoePfeiffer** [comment]
Let's add something about
Improved time step selection for descent (no issue)
Improved ground hit velocity estimation (partially addresses issue 1349)

**Pull request merged**
