### PR TITLE
Allow rocket info to show stability margin as percentage of length

### PR DESCRIPTION
**Pull request by raketenolli**
* create a new class PercentageOfLengthUnit
* add new unit to stability units

### CODE REVIEW

**Comment by hcraigmiller** [comment]
See also, duplicate issue #822, and new feature request #802.

**Review by neilbalch — APPROVED** [review]

**Comment by JoePfeiffer** [comment]
Rather than just labelling it "%" in the Preferences->Units dialog, would it be clearer to label it "% of length"?  If I hadn't already known what it meant, I'm not sure it would have been obvious to me.

**Comment by wolsen** [comment]
> Rather than just labelling it "%" in the Preferences->Units dialog, would it be clearer to label it "% of length"?  If I hadn't already known what it meant, I'm not sure it would have been obvious to me.

I had the exact same thought you did here @JoePfeiffer. However, after having run it and play with it, I think % is actually fine. For brand new rocketeers, they might confused with the caliber unit as well. I think we should document this, but % is better screen real-estate wise; especially when you know what it is.

So in short, I guess personally I'm fine with % if we release note it and document it.

**Comment by neilweinstock** [comment]
Is this handled as a global units preference, so I'll always see either calibers *or* percentage?

If so, then speaking only for myself, I'd much prefer one of the following approaches:
1) Option to show % *in addition* to calibers (this is best IMHO)
2) Preference selectable on a per-rocket basis

I have a few rockets that I would like to use % on, but not all of them.  If I could only see percentage if I select it as a global preference then I'd never use it (or rather, I'd continue to do it in my head like I do now).

If I'm misunderstanding how this is working, then disregard.

**Comment by wolsen** [comment]
> Is this handled as a global units preference, so I'll always see either calibers _or_ percentage?

Global preference, the same way that stability units are elsewhere (like mm, cm, etc).

> 
> If so, then speaking only for myself, I'd much prefer one of the following approaches:
> 
> 1. Option to show % _in addition_ to calibers (this is best IMHO)

Agreed, however I think landing % is fine and a subsequent combined one to get something like `1.2 cal (12 %)` can be a follow up patch and actually fairly straight-forward.

> 2. Preference selectable on a per-rocket basis

This is a larger change and I think Option 1 is better in general. I would argue it can replace just calibers as the default.

> 
> I have a few rockets that I would like to use % on, but not all of them. If I could only see percentage if I select it as a global preference then I'd never use it (or rather, I'd continue to do it in my head like I do now).
> 
> If I'm misunderstanding how this is working, then disregard.

**Comment by neilweinstock** [comment]
> Agreed, however I think landing % is fine and a subsequent combined one to get something like `1.2 cal (12 %)` can be a follow up patch and actually fairly straight-forward.

So... new issue or leave the existing one open?

**Pull request merged**
