### PR TITLE
[#1715] Add button in preferences for clearing cached preferences

### LINKED ISSUE #1715: [Feature request] Button in preferences to reset cached preferences to default
It could be useful if there was a button in the preferences dialog to clear OpenRocket's cached preferences. For instance in light of PR #1705, if a user skipped a update release and wants to undo that action, they could simply clear the cached preferences.

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #1715. Now there is a button in the preferences for clearing cached preferences (UI settings, recent files list etc.). This is useful for people who have some messed up cached settings (e.g. the case of the missing windows when using OR with an external monitor - this issue is already solved, but just to give an idea of where this feature could be useful).

https://user-images.githubusercontent.com/11031519/195407557-328bcc72-2b8e-44c7-812f-23da012a7068.mp4

### CODE REVIEW

**Comment by hcraigmiller** [comment]
Functions as expected, no anomalies found.

I'm not sure that "Clear cached preferences" is sufficient to give users notice that all of their preferences are being reset to the default settings. Something like "Reset ALL preferences to default settings" may be more understandable. My thoughts.

Build 1092
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
> I'm not sure that "Clear cached preferences" is sufficient to give users notice that all of their preferences are being reset to the default settings. Something like "Reset ALL preferences to default settings" may be more understandable. My thoughts.

For the "Rest all preferences", it would make sense to also reset all the parameters in the preferences dialog (such as all the units). Should I implement that?

**Comment by SiboVG** [comment]
> For the "Rest all preferences", it would make sense to also reset all the parameters in the preferences dialog (such as all the units). Should I implement that?

Oh, nevermind, it resets all preferences, except for the units. I will just implement the units then.

**Comment by hcraigmiller** [comment]
Functions as expected, no anomalies found.

Build 1093
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
> Functions as expected, no anomalies found.

I'm sorry you had to clear your preferences to test this :)

**Pull request merged**
