### PR TITLE
[#1458] Pack component config dialog after inside/outside checkbox change

### LINKED ISSUE #1458: Bug: resize config panel when different inside/outside appearance option selected
When setting a component to different inside/outside appearance, the config panel should resize itself, so not like this:

https://user-images.githubusercontent.com/11031519/174301840-51a188be-87ea-4144-a65e-ebf85f6fa19b.mp4

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #1458 by resizing the component config dialog after changing the inside/outside appearance checkbox.

Demo:

https://user-images.githubusercontent.com/11031519/175384277-221fe612-ab76-4bdd-92dd-7260650a9b84.mov

### CODE REVIEW

**Comment by hcraigmiller** [comment]
Functions as expected. However, edge appearance labels are being truncated.

Label Truncated

**Comment by SiboVG** [comment]
Does the latest commit fix that issue @hcraigmiller?

**Comment by hcraigmiller** [comment]
Test of Build 746... no change.

Label Truncated Build_746

**Comment by SiboVG** [comment]
The text is not cut off when you check the 'Use separate appearance' checkbox, close the edit dialog and then re-open the dialog, right?

**Comment by hcraigmiller** [comment]
Text is truncated in both instances...

Label Truncated Rev_03

**Comment by SiboVG** [comment]
Okay, does the latest commit fix it @hcraigmiller?

**Comment by hcraigmiller** [comment]
Success... looking good.

**Pull request merged**
