### PR TITLE
[#2148] Apply sim changes when window closes & [#1826] Fill in gaps in multi-sim editing

### LINKED ISSUE #1826: [Feature request] Gaps in multi-sim editing functionality
It would be useful to allow multi-component editing of simulations, so you can e.g. edit the launch site parameters for all simulations simultaneously.

### LINKED ISSUE #2148: [Bug] Multi-sim editing only works when clicking the "Close" button
See discussion in #2147. Multi-sim editing only works when you click the "Close" button in the sim edit dialog. When you close the dialog using the x-button in the top-left of the window, or by pressing escape, it doesn't work.

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #2148 and fixes #1826. Now, when closing the edit sim dialog in **any way** (clicking the close button, hitting the escape key, x-button in top-left of the window) applies the simulation options to all selected simulation.

The fix for #1826 is that multi-sim editing had some gaps, namely:
- The checkbox for "Always launch directly up-wind"
- The checkbox for "Use ISA"
- Geodetic calculations

These are now fixed.

### CODE REVIEW

**Comment by SiboVG** [comment]
Oh, and now the edit button for sims is enabled, also when multiple sims are selected (fixes #2140).

**Comment by hcraigmiller** [comment]
Functions as described with no anomalous behavior found.

I do have one concern. If a change is accidental, there is no way to cancel that change. I would have the esc key cancel the changes, rather than confirm the changes.

OR Build:  1673
Microsoft Windows 11 Pro; 10.0.22621 Build 22621.1105; Windows Feature Experience Pack 1000.22638.1000.0
Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)

**Comment by SiboVG** [comment]
> I do have one concern. If a change is accidental, there is no way to cancel that change. I would have the esc key cancel the changes, rather than confirm the changes.

I get your point, but that would be counter-intuitive to the workflow of component editing, where pressing the escape key also applies the changes. I'm also very much used to this workflow from other software, as I don't always want to move my mouse over to the close button and click it. Pressing the escape key just accelerates my workflow + it's aligned to the component edit workflow.

**Comment by neilweinstock** [comment]
Ultimately we could have a cancel/OK button like in the component editor.

**Comment by hcraigmiller** [comment]
I do think something is needed to cancel an accidental change, perhaps as @neilweinstock suggested.

**Pull request merged**
