### PR TITLE
[#1791 & ##1631] Return component mass as section mass if subcomponents mass is overridden & add subcomponent overridden icons

### LINKED ISSUE #1791: [Bug] Override subcomponents mass does not override component tree subcomponent mass values
When the override subcomponents mass box is checked on the configuration pane, highlighting the primary component and subcomponents on the component tree, the primary component shows the overridden value of all of the values combined.

Component tree mass

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #1791.

EDIT: see below for full details of what this PR fixes!

### CODE REVIEW

**Comment by SiboVG** [comment]
`// TODO: add small unit test for checking getMass() vs getSectionMass()`

**Comment by hcraigmiller** [comment]
Different functional error.

The X in X of Y is now the total mass of all components (overridden and otherwise), and Y is the total mass with overrides.

Component tree mass Rev_02

Build 1164
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
Okay, what seemed like a quick-and-easy fix became a bit more complex.

To have a correct tooltip text for components whose parent overrides their settings, I added `overriddenBy` objects for the mass, CG, and CD override, for each `RocketComponent`. Those objects are just a reference to the parent component that overrides the settings of that component. With that information, it's trivial to gather the correct information for each component to set the tooltip text.

**Tooltip texts now look like this:**
Single, normal component
image

Single component, with self-overridden values
image

Single component, with overridden values by parent
image

Multiple normal components
image

Multiple components, including component with self-overridden values
image

Multiple components, including component with overridden values by parent
image


Multiple components, including component with self-overridden values, and component with overridden values by parent
image

------

Now, I'm sorry that I expanded this PR beyond its scope, but I already planned on also using the implementation of the `overriddenBy` objects to fix #1631. So I included it in this PR. Setting subcomponent overrides now also adds an icon for the subcomponents in the component tree, and adds a warning/reminder in the subcomponent override tab that their mass/CG/CD is overridden by a certain component. This also disables the respective override mass/CG/CD checkbox. Demo:

https://user-images.githubusercontent.com/11031519/200739969-39b30fd4-bb01-445f-ae67-78d7e4d8957e.mp4

**Comment by SiboVG** [comment]
At this points, the unit tests fail due to PR #1753. I thought PR #1801 fixed the issue that caused PR #1753, and it did when I ran the checks on PR #1753 before merging, but that was just a lucky run. Joe is investigating the issue.

In the meantime you can use [this JAR](https://drive.google.com/file/d/1ETrY9fOoZjCTB2z4Dw1-zZAq7o-nSx1O/view?usp=share_link) for testing (the old fashioned way 🙃).

**Comment by JoePfeiffer** [comment]
I expect to have something for that later today.

**Comment by hcraigmiller** [comment]
Functions as expected, no anomalies found. A+

Build 1182
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Pull request merged**
