### PR TITLE
[#2126] Apply freeform conversion to config listeners

### LINKED ISSUE #2126: When multi-editing fins, "Convert to freeform" only operates on one
When I have selected multiple fins for multi-editing, the "Convert to freeform" button is available.  However, if I click on it, it only converts the first fin that I had selected, not all the fins that are selected.  It should operate on all of them.

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #2126.

https://user-images.githubusercontent.com/11031519/226393635-c042f27a-6d01-44d7-8289-98ec496c1692.mov

### CODE REVIEW

**Comment by neilweinstock** [comment]
That was quick. :)

**Comment by SiboVG** [comment]
> Note: Multi-component edit correctly converts all selected to freeform, but only splits the first selected fin set. Should multi-component fin split be included in this PR or a new PR?

Implemented now.

**Comment by hcraigmiller** [comment]
If you convert to freeform and then split without closing the multi-component dialog, you get an error.

Untitled

If you convert to freeform and close the multi-component dialog before reselecting both fin sets and splitting the fins, then you don't. When you select both fin sets and split the fins first, the dialog closes automatically so this isn't an issue because reselection is mandatory.

**Comment by SiboVG** [comment]
> If you convert to freeform and then split without closing the multi-component dialog, you get an error.
> 
> Untitled
> 
> If you convert to freeform and close the multi-component dialog _before_ reselecting both fin sets and splitting the fins, then you don't. When you select both fin sets and split the fins first, the dialog closes automatically so this isn't an issue, reselection is mandatory.

I can't recreate this, am I missing something?

**Comment by hcraigmiller** [comment]
Steps:

1. Open the _A simple model rocket example_.
2. Duplicate the fin set and set its position to -3 in; reposition to above other fin set on the component tree.
3. Select both fin sets and click edit.
4. On the _General_ tab, click _Convert to Freeform_.
5. On the _Shape_ tab, move the second point.
6. On the _Shape_ tab, click _Split fins_.

Error occurs.

**Comment by SiboVG** [comment]
Should be fixed now.

**Comment by hcraigmiller** [comment]
Functions as expected, no anomalous behavior found.

OR Build: 1639
Microsoft Windows 11 Pro; 10.0.22621 Build 22621.1105; Windows Feature Experience Pack 1000.22638.1000.0
Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)

**Pull request merged**
