### PR TITLE
Changed File > Export menu format to accommodate multiple file format

### PR DESCRIPTION
**Pull request by hcraigmiller**
Adds custom icons to the File menu for the import and export operations. Renames "Export..." to "Export as Rocksim."

### CODE REVIEW

**Comment by SiboVG** [comment]
I like the icons, but would not use 'Export as Rocksim' in case we add additional export types (such as RASAero)

**Comment by hcraigmiller** [comment]
The code for this PR has been completely rewritten and included the new export menu PR.

**Comment by hcraigmiller** [comment]
I guess I need help from @SiboVG again before I really make a mess of the work I've done. On this PR #1316, two commits need to be deleted and the third kept. **The one that needs to be kept starts “Changed file…” with an index number of 0b236ef**. I hate to bother everyone, but I can't figure out how to do it.

**Comment by hcraigmiller** [comment]
I finally figured it out and created a new PR.

**Pull request closed without merging**
