### PR TITLE
Update to latest dependency versions and Java 9+

### PR DESCRIPTION
**Pull request by thzero**
Updated to latest versions of all the dependencies for both build and test (but still on junit4, not junit5).  Updated travis control file to build for java 9.

### CODE REVIEW

**Comment by wcravens** [comment]
Please fix README.md back to pointing to our travis and not yours.

For the group: is the project ready for the jump to 9?  Maybe I missed a discussion in an issue or on the list somewhere.  This merge request certainly goes a long way and makes up for the previous efforts to update versions; assuming of course that it is building correctly and runs on our OS targets.

**Comment by teyrana** [comment]
We have multiple issues where users are unable to run our released jar file on java 9 and 10 JREs.  Does this help with that goal?

Fwiw, the -dev email-list does not (yet) have a consensus on moving to java9.  TBD.

**Comment by thzero** [comment]
Oops yeah, I forgot that this morning.

Frankly I rebuilt OR using Gradle so it builds and tracks dependencies all so I could get it up and running on later versions because I'm tired of running old java vm version just for sake of OR.  So this was moving all that back over into OR

I wasn't able to run on 9 or 10 either as it was.   Also I had issues with java2d with the dx issue in 8 which I don't seem to have now with updated dependencies.

I don't have a Mac, so can't comment on it.  But it at least ran on Windows with 8, 9 and 11 (my Gradle based version runs on 11).  Ubuntu vm I only tried on 9.

**Comment by teyrana** [comment]
Okay, I have both Mac and linux/ubuntu machines- I'll test it on those.

**Comment by thzero** [comment]
The orange dependency was latest I could find.

**Comment by teyrana** [comment]
Hey, I'm having some issues getting this to run on my machine.  Did you happen to upgrade the IDE files for Eclipse or Intellij?

**Comment by thzero** [comment]
> Hey, I'm having some issues getting this to run on my machine. Did you happen to upgrade the IDE files for Eclipse or Intellij?

I don't use Eclipse, so did not touch anything with regard to those.   For gradle, I just did a compare between the .idea folders, and no changes there.

> Also, If I wanted to use the gradle build, are the branches on your fork in buildable, working order?

They should be, yeah.  Those are the ones I'm working on mostly and use to build my local copies of both the master, as well as unstable, branches.

Although think I just found a bug in the Photo Studio that I'm starting to look into.

**Comment by teyrana** [comment]
Gotcha.  

For gradle, which of your branches would you recommend? `thzero/gradle` or `thzero/gradle-unstable`?

**Comment by teyrana** [comment]
Testing notes:
1. Builds on Mac OSX 10.13.6 with Oracle Java: 9.0.4+11.

**Comment by thzero** [comment]
> `thzero/gradle` or `thzero/gradle-unstable`?

Both should work. 
thzero/gradle is the master branch using gradle
thzero/gradle-unstable is the unstable branch using gradle.

Here are the two versions I've been testing with..

java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)

openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

**Comment by teyrana** [comment]
@thzero

> Here are the two versions I've been testing with..
 awesome! On which OS?

**Comment by JoePfeiffer** [comment]
After updating to java9, I can build from the thzero:update branch,
and I can run from either the jar I create or the one Dan shared.

(1) when I launch the program, I get the following warnings:

snowball:934$ java -jar openrocket-alpha9-java9-52e4eda3.jar 
9.0.1
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/joseph/openrocket/jar/openrocket-alpha9-java9-52e4eda3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

(2) when I try to switch to a 3D view I get the following in the rocket view, instead of the rocket:
After updating to java9, I can build from the thzero:update branch,
and I can run from either the jar I create or the one Dan shared.

(1) when I launch the program, I get the following warnings:

snowball:934$ java -jar openrocket-alpha9-java9-52e4eda3.jar 
9.0.1
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/joseph/openrocket/jar/openrocket-alpha9-java9-52e4eda3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

(2) when I try to switch the rocket View Type to 3D Figure,  3D Finished, or 3D Unfinished, I get the following error message in the rocket view window, instead of a view of the rocket:
Unable to load 3d Libraries: Can't load library: /home/joseph/openrocket/jar/natives/linux-amd64/libgluegen-rt.so
The path up to the 'jar' directory is the directory I'm running from (so if I'm in my home directory and run with java -jar openrocket/jar/openrocket-alpha9-java9-52e4eda3.jar the location of the missing library is /home/joseph/natives/linux-amd64/libgluegen-rt.so).  Note that I can't cut-and-paste the error message; I believe I've proofread what I typed above carefully, but typos are still possible.

I'm not seeing other problems at present.

**Comment by teyrana** [comment]
note:  `openrocket-alpha9-java9-52e4eda3.jar`
Is compiled from this PR #464, rebased onto the most recent `unstable` (i.e. development) branch.

**Comment by thzero** [comment]
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/joseph/openrocket/jar/openrocket-alpha9-java9-52e4eda3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
> WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

Yeah, I'm seeing that now too.   That seems to be a guice issue I think.

> (2) when I try to switch the rocket View Type to 3D Figure, 3D Finished, or 3D Unfinished, I get the following error message in the rocket view window, instead of a view of the rocket:
> Unable to load 3d Libraries: Can't load library: /home/joseph/openrocket/jar/natives/linux-amd64/libgluegen-rt.so

Interesting.  Hadn't see that before.  Checking the jar file, the natives/linux-amd64/libgluegen-rt.so is there at least when I've build it.  Can you open the .jar up as a zip file and check to see if that folder structure and .so file is there??

**Comment by JoePfeiffer** [comment]
I'm not seeing a natives directory, nor any .so files, in either my .jar nor Dan's.

This branch is still built with ant, correct?

**Comment by teyrana** [comment]
yea, I just ran 'ant jar'.  tbh, I'm not really sure what that antfile does... :|

**Comment by teyrana** [comment]
> yea, I just ran 'ant jar'. tbh, I'm not really sure what that antfile
> does... :|.
>
> Ah, I should clarify.  I know what *Ant* does.  I'm less clear on what
*our build* does.

On topic: the Jar ran fine on my machine;
Does that mean it's using locally installed dependencies, instead of the
versions "builtin" to the jar?  Or is that merely a fallback?

**Comment by thzero** [comment]
Could be.

**Comment by thzero** [comment]
Ok... I updated the build.xml.  It now bundles the native libs.

**Comment by JoePfeiffer** [comment]
Now works for me with oracle java9 (though I'm still getting the illegal reflective access error).

**Comment by thzero** [comment]
Yeah, I haven't figured that one out yet...

**Comment by thzero** [comment]
Narrowing the guice issue/warning down to InternalInjectorCreator.initializeStatically

**Comment by thzero** [comment]
https://github.com/google/guice/issues/1133

**Comment by JoePfeiffer** [comment]
After seeing some of the more recent comments on that guice thread mentioned above, it seems like the illegal retrospection message is annoying but not serious, and isn't going to go away until guice is updated.  I'd suggest that if Chris could resolve the conflicts that have arisen due to changes in the Unstable branch since this PR was submitted, it should be committed and we can move on to Java 9.

**Comment by thzero** [comment]
Yeah... pretty much either guice has to be updated, or we gotta get rid of it for something else.

I've got most of the things updated... I'll see about getting anything new done this weekend.

**Comment by JoePfeiffer** [comment]
Since (according to that guice thread) the message is harmless, I'd suggest for this release we just hope guice gets updated.  It does sound like they're working on it.  If it doesn't happen in a timely manner we can look into replacing it later.

**Comment by thzero** [comment]
Should be updated.... gonna take another pass through and see if there are any more dependency updates.

**Comment by gallopinggoose6** [comment]
Guys, Oracle is onto JRE 13 now. I would highly recommend rolling this out sooner rather than later.

**Comment by teyrana** [comment]
Java 11/13 support is now in the development (`unstable`) branch. 

Some of the changes from this PR have been folded in, as well.  For anyone who's following this issue, and wants to take for a spin, please let us know if we've missed anything!

**Pull request closed without merging**
