### PR TITLE
Update guice library to remove AOP; Fixes issue #609

### PR DESCRIPTION
**Pull request by itshanney**
@teyrana Fix for issue #609 by updating the guice library to a Java 11 compatible version per instructions from the following.

https://github.com/google/guice/issues/1133

Runs in IDE without warnings and runs from ant build on the command line without warnings. No additional flags required to run program.

### CODE REVIEW

**Comment by teyrana** [comment]
1. That last commit doesn't seem to update the Intellij Builds.  Should I send over a patch? 
2. Otherwise, I confirm that the warnings no longer appear, and the app runs okay :)

**Comment by wolsen** [comment]
I can confirm that the warnings no longer appear as well and it builds fine in eclipse.

**Comment by teyrana** [comment]
@itshanney 
FYI: here's the patch which enables the Intellij build.  Feel free to loop in, if you like:

`$ git diff --patch-with-stat`

```
 core/OpenRocket Core.iml   |  2 +-
 swing/OpenRocket Swing.iml | 18 +++++++++---------
 2 files changed, 10 insertions(+), 10 deletions(-)

diff --git a/core/OpenRocket Core.iml b/core/OpenRocket Core.iml
index b09b9bb8..53bab302 100644
--- a/core/OpenRocket Core.iml
+++ b/core/OpenRocket Core.iml
@@ -128,7 +128,7 @@
     <orderEntry type="module-library">
       <library>
         <CLASSES>
-          <root url="jar://$MODULE_DIR$/lib/guice-4.2.1.jar!/" />
+          <root url="jar://$MODULE_DIR$/lib/guice-4.2.3-no_aop.jar!/" />
         </CLASSES>
         <JAVADOC />
         <SOURCES />
diff --git a/swing/OpenRocket Swing.iml b/swing/OpenRocket Swing.iml
index 18aa7a5e..de173f02 100644
--- a/swing/OpenRocket Swing.iml
+++ b/swing/OpenRocket Swing.iml
@@ -172,15 +172,6 @@
         <SOURCES />
       </library>
     </orderEntry>
-    <orderEntry type="module-library">
-      <library>
-        <CLASSES>
-          <root url="jar://$MODULE_DIR$/../core/lib/guice-4.2.1.jar!/" />
-        </CLASSES>
-        <JAVADOC />
-        <SOURCES />
-      </library>
-    </orderEntry>
     <orderEntry type="module-library">
       <library>
         <CLASSES>
@@ -245,5 +236,14 @@
         <SOURCES />
       </library>
     </orderEntry>
+    <orderEntry type="module-library">
+      <library>
+        <CLASSES>
+          <root url="jar://$MODULE_DIR$/../core/lib/guice-4.2.3-no_aop.jar!/" />
+        </CLASSES>
+        <JAVADOC />
+        <SOURCES />
+      </library>
+    </orderEntry>
   </component>
 </module>
\ No newline at end of file
```

**Comment by itshanney** [comment]
@teyrana Incorporated. Before you commit, can you take a look at swing/Open Rocket Swing.iml at the very top the <libelement> elements look to be old and referencing old libs.

**Comment by teyrana** [comment]
Huh.  Yea, I think I see what you mean.  I see some of the old libraries.  
Buuuut, they don't seem to be interfering with anything, and I certainly don't break the build.

If it ain't broke.....  

So, I'm going to merge this particular PR. 

And if you'd like to fix those lines and run a smoke test.  I'm open to it.   Otherwise I won't stress about it :)

**Pull request merged**
