### PR TITLE
[Fixes 637] Update print dialog to allow simulation control

### LINKED ISSUE #637: Printing is slow and appears to hang
Printing a rocket is very slow without any user feedback to indicate what's going on. When a rocket has multiple flight configurations or long running simulations there is a long delay between the time the user clicks the "Preview and Print" or "Save as PDF" buttons.

**Reproducer Steps**
1. Open the "Boosted Dart" example rocket.
2. Select Print / Export PDF ... from the file menu
3. Ensure Design Report is selected and click "Preview & Print" or "Save as PDF"

### PR DESCRIPTION
**Pull request by wolsen**
Updates the print dialog to allow for simulations to be re-run
or not. Selecting the "Update simulation data" checkbox will
re-run any out of date simulations prior to generating the
design report.

Fixes #637

Signed-off-by: Billy Olsen <billy.olsen@gmail.com>

### CODE REVIEW

**Comment by wolsen** [comment]
Some obligatory screenshots

New checkbox option on print dialog:

Screenshot from 2020-05-10 21-09-27

Simulation Progress dialog displayed for long running simulations:

Screenshot from 2020-05-10 21-09-42

**Comment by wolsen** [comment]
@neilweinstock, @teyrana would appreciate some feedback. I'll provide a jar for testing later.

**Comment by wolsen** [comment]
I've uploaded a [test jar](https://www.dropbox.com/s/dl2rfczxagoa60z/OpenRocket-fix-637.jar?dl=0). Would appreciate any feedback.

**Comment by neilweinstock** [comment]
*Looks* good.  First time I tried it I was able to generate an exception.  Since then I haven't been able to reproduce the series of clicks that got me there.  Will keep trying.

**Comment by neilweinstock** [comment]
OK, I can reproduce the exception now.

1) Start up OR (I'm on Mac, running Java 11)
2) Load attached ORK file
3) File -> Print/Export PDF
4) Click "Update Simulation Data" **twice** (once to turn on, then once to turn off)
5) Click "Preview and Print".  At this point I repeatably get the following exception:
image

[alcubierre_cranberry.ork.zip](https://github.com/openrocket/openrocket/files/4616508/alcubierre_cranberry.ork.zip)

Let me know if you need any more info.

**Comment by teyrana** [comment]
seems eerily similar to issue #666 :/ 

Let's fix that one, first.  And then circle back.

**Comment by wolsen** [comment]
No, I can recreate this one. It happens to do with some of the simulation data that's imported not containing FlightBranches.

**Comment by wolsen** [comment]
Okay, some final updates from some additional testing.

Updated test jar is also [available](https://www.dropbox.com/s/5jn19osv6a5ke7b/OpenRocket-fix-637-take-2.jar?dl=0)

**Comment by teyrana** [comment]
Looks good to me.

**Comment by neilweinstock** [comment]
Look good.

________________________________

Ce message, ainsi que tous les fichiers joints à ce message, peuvent contenir des informations sensibles et/ ou confidentielles ne devant pas être divulguées. Si vous n'êtes pas le destinataire de ce message (ou que vous recevez ce message par erreur), nous vous remercions de le notifier immédiatement à son expéditeur, et de détruire ce message. Toute copie, divulgation, modification, utilisation ou diffusion, non autorisée, directe ou indirecte, de tout ou partie de ce message, est strictement interdite.


This e-mail, and any document attached hereby, may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized, direct or indirect, copying, disclosure, distribution or other use of the material or parts thereof is strictly forbidden.

**Pull request merged**
