### PR TITLE
[#966] Fix weird behavior when clicking on textured part in 3D view

### LINKED ISSUE #966: Strange behavior when clicking in 3D view on Mac
This is what happens when I click on the rocket in 3D view in the latest unstable, on M1 Mac running Big Sur:
https://user-images.githubusercontent.com/243872/123722157-c42c7600-d855-11eb-918e-e42b0cba2360.mov

Normally, clicking on the rocket in 3D view on the Mac does nothing: component selection hasn't worked for a long time (this is the subject of another issue).  Now, though, almost the whole rocket flashes when you click on it.  Or at least, maybe just the decal textures are flashing (hard to tell, but that's what it looks like to me).

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #966, which was a weird 3D behavior (on macOS, but maybe also others?) when clicking on a textured part (e.g. the body tube or fins of 'A simple model rocket').

### CODE REVIEW

**Comment by hcraigmiller** [comment]
There is a distinct time delay when switching between components in 3D Finished; this delay is about 3 seconds and is visually more apparent with an increased complexity in the design (such a multiple stages). Using _A simple model rocket_, if your click on a different component within the 3 second period, the click on the new component is ignored until a second click after the 3 second period. And, a click on a blank area in the 3D Finish window does not clear the component selection (left or right click); you must click in a blank area of the tree window (left or right click).

**Comment by SiboVG** [comment]
Hm, crap, I didn't know the extra figure update would be that bad for performance...

**Comment by SiboVG** [comment]
Okay, should be fixed now.

**Comment by hcraigmiller** [comment]
Works well now, no anomalies found.

Just to verify function, components may only be deselected by : (1) selecting another component in either the tree or 3D view windows, or (2) by left or right clicking in a blank area of the tree window; a left or right click in a blank area of the 3D window does not deselect a component.

Build 1151
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
> Just to verify function, components may only be deselected by : (1) selecting another component in either the tree or 3D view windows, or (2) by left or right clicking in a blank area of the tree window; a left or right click in a blank area of the 3D window does not deselect a component.

It should be possible to deselect by clicking a blank area in the 3D view. You can create a new issue for it.

**Comment by SiboVG** [comment]
> You can create a new issue for it.

I made an issue for it, #1787.

**Pull request merged**
