### PR TITLE
New app icons

### PR DESCRIPTION
**Pull request by neilweinstock**
Here's the fully-implemented new app icon, with all comments (I think) incoporated.

### CODE REVIEW

**Comment by SiboVG** [comment]
Some of the new icons look very blurry compared to the previous ones.
image

**Comment by neilweinstock** [comment]
Hmm, it is a bit soft, although it looks better in real life than in the slightly enlarged version shown above.
image

**Comment by neilweinstock** [comment]
I'm not sure why that happened.... will fix.

**Comment by neilweinstock** [comment]
OK, check again.

**Comment by SiboVG** [comment]
Yup, it's sharp now, thanks 👍

Some notes though:
1. I'm not too fond of the small black outline on the rocket in the splash screen
Screenshot 2023-01-04 at 22 57 49

3. I would add back a bit of the outside blue haze on the Earth. The Earth almost looks almost too sharp now and takes away some of the attention from the rocket (which should have the main focus)
E.g. if you compare the about dialogs:
image

You can also see this in the welcome dialog, where everything looks too sharp actually (some aliasing issue?).
image

4. I would make the Earth slightly smaller; I liked your original mock-up the best, where part of the right pod is outside the Earth:
image

**Comment by neilweinstock** [comment]
I'll fix most of what you pointed to.  The about box, though, appears to be bad scaling inside the Java app... my supplied image does not look all jaggy like that.

**Comment by neilweinstock** [comment]
All requested changes have been made.

**Comment by SiboVG** [comment]
Thanks! Didn't do a proper test yet, but is it possible that you didn't update the about icon? It still has its right pod inside the Earth.

**Comment by neilweinstock** [comment]
There was an old version in the source directory; wasn't supposed to be there at all.  The correct one is up to date (in resources).

**Comment by SiboVG** [comment]
Sorry @neilweinstock, I wasn't very clear. What I meant was that the outline haze of the Earth should be more defined, not that the blur over the Earth should be more. The new Earth should have the same sharpness and outline as the old icon. What I mean by outline is this:
image

**Comment by SiboVG** [comment]
Also: I think the aliasing issue is because you used "GIMP built-in sRGB" color profile instead of "sRGB IEC61966-2.1". I already tried fiddling with the code to render it with anti-aliasing, but that didn't fix it, so could you try exporting with the "sRGB IEC61966-2.1" color profile?

**Comment by neilweinstock** [comment]
Like this?  The haze is not as extensive as before because it was Too Much.
image

**Comment by SiboVG** [comment]
Yeah that looks better!

**Comment by SiboVG** [comment]
I do hope you're not pulling the old "I'm just gonna send the same image twice and hope the customer magically thinks this is better" graphics designer trick on me.

**Comment by neilweinstock** [comment]
LOL.

The difference is subtle, to be sure.  I'll check in just the new source (XCF file), won't try doing any of the exporting until you take a whack at the color profile stuff.

**Comment by SiboVG** [comment]
Something minor: the 256 icon has a small artefact on top:
image
image

Sounds small, but it is noticeable in the program.

**Comment by neilweinstock** [comment]
Argh, will fix
________________________________

**Comment by SiboVG** [comment]
> Argh, will fix

Graphic design is fun :)

**Comment by hcraigmiller** [comment]
As to function only, functions as expected; no anomalies found.

Overall, the icons look good to me, and the new taskbar icon is even clearly distinguishable from the old one.

Build 1396
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by neilweinstock** [comment]
Anyone else want to review this before we merge?

**Comment by JoePfeiffer** [comment]
Looks excellent to me.

**Pull request merged**
