### PR TITLE
[fixes #989 & #992] Fix 3D view going blank + high CPU usage

### LINKED ISSUE #989: 3D using Windows is intermittent
Since the last merge, I have lost all 3D functionality, both in the editor and in Photo Studio.

Latest merge:
3D No

OpenRocket-969-4.jar:
3D Yes

### PR DESCRIPTION
**Pull request by SiboVG**
This PR (I do very much hope) fixes #989 and #992 where the editor view went blank when switching to the 3D view + where a very high increase in CPU usage was noticed. Okay, so I did an oopsie in my PR of fixing bad highlight colors. The code written to change the foreground for the SelectColorButton and SelectColorToggleButton should never have been put inside the paint-method. Not only does this cause a very high CPU usage, it also messes up the init-method calling of the editor window (which caused it to go blank).

I added the foreground updating in a changelistener and only let that code execute on OSX-devices (i.e. devices that have a custom Button.selectForeground or ToggleButton.selectForeground defined).

Tested on Mac OSX Big Sur to check the functionality and testen on Windows 10 Home to test the 3D view going blank (CPU usage not tested).

Here is a [jar file](https://www.dropbox.com/s/ptur74vl7o5qwhl/OpenRocket-989.jar?dl=0) for testing.

### CODE REVIEW

**Comment by hcraigmiller** [comment]
This appears to have fixed the issues... no anomalies found.

[OS Windows 10 Pro service pack 120.2212.2020.0 with Java version 11.0.9 2020-10-20 LTS]

**Comment by hcraigmiller** [comment]
This does not appear to be an issue in Windows (when resizing the window, the 3D display does not black out).

[OS Windows 10 Pro service pack 120.2212.2020.0 with Java version 11.0.9 2020-10-20 LTS]

**Comment by SiboVG** [comment]
Do you not have the problem that I've discussed [here](https://github.com/openrocket/openrocket/issues/989#issuecomment-896137410) @hcraigmiller?

**Comment by hcraigmiller** [comment]
Issue #989 appears to have been fixed by the 989.jar insofar as I have been able to determine.

**Comment by neilweinstock** [comment]
Outside of PR994, when did the blank buttons occur?  I need to know how to reproduce so I can verify the fix.

**Comment by SiboVG** [comment]
> Outside of PR994, when did the blank buttons occur? I need to know how to reproduce so I can verify the fix.

Starting from the fix bad highlights commit.

**Comment by neilweinstock** [comment]
I mean, how do I reproduce it (in a build before this one)?

**Comment by SiboVG** [comment]
The main OR window needs to be out of focus, you can do this by either making a popup window appear inside OR itself (e.g. change the configuration of a component) or you can go to a different program, e.g. your browser and move the browser window out of the way so that you can see the OR main window.

**Comment by neilweinstock** [comment]
OK, I'll try that tonight.

**Comment by neilweinstock** [comment]
Looks good.

**Review by wolsen — APPROVED** [review]

**Pull request merged**
