### PR TITLE
Fixed trapezoidal fins on transitions not being imported from Rocksim

### LINKED ISSUE #1553: Trapezoidal fin set cannot be attached to transition - Rocksim files
---------- Bug report ----------

Include detailed steps on how to trigger the bug:
(You can edit text directly in this window)

1. Open a Rocksim file with fins on a transition https://www.rocketreviews.com/quest-tomahawk-slcm-5452.html
2. 
3.

What does the software do and what in your opinion should it do in the case described above:

Error will pop up when you try to open the file saying that a trapezoidal fin set cannot be added to a transition.

Include your email address (optional; it helps if we can contact you in case we need additional information):

(Do not modify anything below this line.)
---------- System information ----------
OpenRocket version: 22.02.beta.04
OpenRocket source: default
OpenRocket location: C:\Program Files\OpenRocket\.\OpenRocket.jar
JOGL version: 2.4.0-rc-20210111
Current default locale: en_US
System properties:
awt.toolkit=sun.awt.windows.WToolkit
exe4j.consoleCodepage=cp0
exe4j.isInstall4j=true
exe4j.launchName=C:\Program Files\OpenRocket\OpenRocket.exe
exe4j.moduleName=C:\Program Files\OpenRocket\OpenRocket.exe
exe4j.semaphoreName=Local\c:_program_files_openrocket_openrocket.exe0
exe4j.tempDir=
exe4j.unextractedPosition=0
file.encoding=Cp1252
file.separator=\
install4j.appDir=C:\Program Files\OpenRocket\
install4j.exeDir=C:\Program Files\OpenRocket\
install4j.launcherId=59
install4j.swt=false
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.awt.printerjob=sun.awt.windows.WPrinterJob
java.class.path=C:\Program Files\OpenRocket\.install4j\i4jruntime.jar;C:\Program Files\OpenRocket\.\OpenRocket.jar
java.class.version=55.0
java.home=c:\program files\openrocket\jre
java.io.tmpdir=C:\Users\Joseph\AppData\Local\Temp\
java.library.path=c:\program files\openrocket\jre\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\Joseph\AppData\Local\Microsoft\WindowsApps;
java.runtime.name=OpenJDK Runtime Environment
java.runtime.version=11.0.15+10-LTS
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=11
java.util.Arrays.useLegacyMergeSort=true
java.vendor=BellSoft
java.vendor.url=https://bell-sw.com/
java.vendor.url.bug=https://bell-sw.com/support
java.version=11.0.15
java.version.date=2022-04-19
java.vm.compressedOopsMode=Zero based
java.vm.info=mixed mode
java.vm.name=OpenJDK 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=11
java.vm.vendor=BellSoft
java.vm.version=11.0.15+10-LTS
jdk.debug=release
jnlp.jogamp.tmp.cache.root=jln4175590057652554161
line.separator=\u000d\u000a
os.arch=amd64
os.name=Windows 11
os.version=10.0
path.separator=;
sun.arch.data.model=64
sun.awt.enableExtraMouseButtons=true
sun.awt.exception.handler=net.sf.openrocket.gui.main.SwingExceptionHandler$AwtHandler
sun.boot.library.path=c:\program files\openrocket\jre\bin
sun.cpu.endian=little
sun.cpu.isalist=amd64
sun.desktop=windows
sun.io.unicode.encoding=UnicodeLittle
sun.java.command=C:\Program Files\OpenRocket\OpenRocket.exe
sun.jnu.encoding=Cp1252
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
sun.os.patch.level=
user.country=US
user.dir=C:\Program Files\OpenRocket
user.home=C:\Users\Joseph
user.language=en
user.name=Joseph
user.script=
user.timezone=America/New_York
user.variant=
---------- Error log ----------
1 0.001 INFO (SwingStartup.java:65) Starting up OpenRocket version 22.02.beta.04
2 0.005 INFO (SwingStartup.java:73) Checking for graphics head
3 0.007 INFO (SwingStartup.java:84) Moving startup to EDT
4 0.114 INFO (SwingStartup.java:176) Initializing the splash screen
5 0.224 INFO (SwingStartup.java:180) Registering exception handler
6 0.228 INFO (SwingStartup.java:186) Loading databases
7 1.130 INFO (TranslatorProvider.java:49) Using default locale en_US
8 1.146 INFO (TranslatorProvider.java:61) Set up translation for locale en_US, debug.currentFile=messages.properties
9 1.147 INFO (ComponentPresetDatabaseLoader.java:93) Loading component presets from datafiles/presets
10 1.147 INFO (MotorDatabaseLoader.java:89) Starting reading serialized motor database
11 1.150 INFO (SwingStartup.java:198) Starting update check
14 1.155 INFO (SwingStartup.java:207) Setting best LAF
18 1.332 INFO (SwingStartup.java:224) Opening main application window
19 1.347 INFO (BasicFrame.java:1751) New action initiated
21 1.422 INFO (MotorDatabaseLoader.java:95) Ending reading serialized motor database, motorCount=1885
22 1.427 INFO (MotorDatabaseLoader.java:70) Starting reading user-defined motors
33 1.495 INFO (MotorDatabaseLoader.java:80) Ending reading user-defined motors, motorCount=1894
139 0.000 DEBUG (-) ===== 104 DEBUG lines removed =====
139 2.967 DEBUG (UpdateInfoRetriever.java:229) Update checker response code: 200
140 3.121 DEBUG (ReleaseInfo.java:43) Invalid release tag format for release: OpenRocket_technical_documentation-v13.05
141 3.123 DEBUG (ReleaseInfo.java:43) Invalid release tag format for release: Development_of_an_Open_Source_model_rocket_simulation-thesis-v20090520
142 3.134 INFO (UpdateInfoRetriever.java:153) Current build is latest version
172 4.044 DEBUG (JarUtil.java:40) Found jar file using codeSource
173 4.044 DEBUG (ExampleDesignFile.java:118) Current jar file is: C:\Program Files\OpenRocket\.\OpenRocket.jar
178 4.168 DEBUG (BasicFrame.java:262) ... Setting Initial Selection: [Rocket, Sustainer]
179 4.168 DEBUG (BasicFrame.java:266) BasicFrame instantiation complete
180 4.198 INFO (SwingStartup.java:230) Checking update status
181 4.198 INFO (SwingStartup.java:92) Startup complete
188 13.468 USER (BasicFrame.java:480) Open... selected
189 23.667 USER (BasicFrame.java:1219) Opening files [C:\Users\Joseph\Downloads\quest_tomahawk.ork]
190 23.667 INFO (BasicFrame.java:1222) Opening file: C:\Users\Joseph\Downloads\quest_tomahawk.ork
192 23.686 INFO (BasicFrame.java:1342) Starting OpenFileWorker
193 23.687 INFO (SwingWorkerDialog.java:133) Running SwingWorker net.sf.openrocket.gui.util.OpenFileWorker@1f702b44
194 23.694 INFO (OpenRocketLoader.java:42) Loading .ork file
195 23.715 DEBUG (Rocket.java:574) Freezing Rocket
196 23.715 DEBUG (Rocket.java:478) Rocket is in frozen state, adding event ComponentChangeEvent[mass,aero] info freeze list
197 23.715 DEBUG (Rocket.java:600) Thawing rocket, freezeList=[ComponentChangeEvent[mass,aero]]
198 23.718 DEBUG (Rocket.java:574) Freezing Rocket
199 23.718 DEBUG (Rocket.java:478) Rocket is in frozen state, adding event ComponentChangeEvent[mass] info freeze list
200 23.718 DEBUG (Rocket.java:600) Thawing rocket, freezeList=[ComponentChangeEvent[mass]]
201 23.722 DEBUG (Rocket.java:574) Freezing Rocket
202 23.722 DEBUG (Rocket.java:478) Rocket is in frozen state, adding event ComponentChangeEvent[mass] info freeze list
203 23.722 DEBUG (Rocket.java:600) Thawing rocket, freezeList=[ComponentChangeEvent[mass]]
204 23.756 DEBUG (DatabaseMotorFinder.java:48) type Single-use, manufacturer AeroTech, designation F52C, diameter NaN, length NaN, digest a30f27b7b8960be379427451c0c228d6, warnings WarningSet[]
205 23.758 DEBUG (DatabaseMotorFinder.java:68) motor is F52C
206 23.793 DEBUG (FlightData.java:251) Computed flight values: maxAltitude=320.681 maxVelocity=103.377 maxAcceleration=105.538 maxMachNumber=0.304 timeToApogee=6.966 flightTime=58.917 groundHitVelocity=6.181 launchRodVelocity=19.451
207 23.793 DEBUG (FlightData.java:251) Computed flight values: maxAltitude=320.681 maxVelocity=103.377 maxAcceleration=105.538 maxMachNumber=0.304 timeToApogee=6.966 flightTime=58.917 groundHitVelocity=6.181 launchRodVelocity=19.451
208 23.797 INFO (OpenRocketLoader.java:96) Loading done
209 23.900 INFO (SwingWorkerDialog.java:151) Worker completed before opening dialog
210 23.900 DEBUG (BasicFrame.java:1407) Opening new frame with the document
211 23.901 DEBUG (BasicFrame.java:154) Instantiating new BasicFrame
214 23.905 DEBUG (BasicFrame.java:187) Constructing the BasicFrame UI
228 23.987 DEBUG (RocketFigure3d.java:141) Initializing RocketFigure3D OpenGL Canvas
229 23.987 DEBUG (RocketFigure3d.java:143) Setting up GL capabilities...
260 24.039 DEBUG (JarUtil.java:40) Found jar file using codeSource
261 24.039 DEBUG (ExampleDesignFile.java:118) Current jar file is: C:\Program Files\OpenRocket\.\OpenRocket.jar
266 24.099 DEBUG (BasicFrame.java:262) ... Setting Initial Selection: [Quest Tomahawk Cruise Missile, Stage]
267 24.099 DEBUG (BasicFrame.java:266) BasicFrame instantiation complete
268 24.114 INFO (BasicFrame.java:1268) Closing window because it is replaceable
269 24.114 DEBUG (BasicFrame.java:1692) Disposing window
278 29.207 USER (BasicFrame.java:480) Open... selected
279 33.785 USER (BasicFrame.java:1219) Opening files [C:\Users\Joseph\Downloads\quest_tomahawk.rkt]
280 33.785 INFO (BasicFrame.java:1222) Opening file: C:\Users\Joseph\Downloads\quest_tomahawk.rkt
282 33.786 INFO (BasicFrame.java:1342) Starting OpenFileWorker
283 33.786 INFO (SwingWorkerDialog.java:133) Running SwingWorker net.sf.openrocket.gui.util.OpenFileWorker@4404b8d9
284 33.897 INFO (SwingWorkerDialog.java:151) Worker completed before opening dialog
285 33.897 INFO (BasicFrame.java:1394) Warnings while reading file: WarningSet[Trapezoidal Fin Set can not be attached to Transition, ignoring component.]
286 38.650 DEBUG (BasicFrame.java:1407) Opening new frame with the document
287 38.651 DEBUG (BasicFrame.java:154) Instantiating new BasicFrame
290 38.654 DEBUG (BasicFrame.java:187) Constructing the BasicFrame UI
304 38.716 DEBUG (RocketFigure3d.java:141) Initializing RocketFigure3D OpenGL Canvas
305 38.716 DEBUG (RocketFigure3d.java:143) Setting up GL capabilities...
336 38.738 DEBUG (JarUtil.java:40) Found jar file using codeSource
337 38.738 DEBUG (ExampleDesignFile.java:118) Current jar file is: C:\Program Files\OpenRocket\.\OpenRocket.jar
342 38.785 DEBUG (BasicFrame.java:262) ... Setting Initial Selection: [Quest Tomahawk Cruise Missile, Stage]
343 38.785 DEBUG (BasicFrame.java:266) BasicFrame instantiation complete
350 44.253 USER (BasicFrame.java:480) Open... selected
351 49.036 USER (BasicFrame.java:1219) Opening files [C:\Users\Joseph\Downloads\quest_tomahawk.rkt]
352 49.036 INFO (BasicFrame.java:1222) Opening file: C:\Users\Joseph\Downloads\quest_tomahawk.rkt
354 49.036 INFO (BasicFrame.java:1342) Starting OpenFileWorker
355 49.036 INFO (SwingWorkerDialog.java:133) Running SwingWorker net.sf.openrocket.gui.util.OpenFileWorker@1475ed06
356 49.141 INFO (SwingWorkerDialog.java:151) Worker completed before opening dialog
357 49.141 INFO (BasicFrame.java:1394) Warnings while reading file: WarningSet[Trapezoidal Fin Set can not be attached to Transition, ignoring component.]
358 153.144 DEBUG (BasicFrame.java:1407) Opening new frame with the document
359 153.144 DEBUG (BasicFrame.java:154) Instantiating new BasicFrame
362 153.146 DEBUG (BasicFrame.java:187) Constructing the BasicFrame UI
366 0.000 VBOSE (-) ===== 176 VBOSE lines removed =====
366 153.162 VBOSE (DoubleModel.java:914) DoubleModel[MotorRowFilter:MinimumLength] adding listener (total 1): javax.swing.JSpinner$ModelListener@2ba292de
367 153.162 VBOSE (DoubleModel.java:914) DoubleModel[MotorRowFilter:MinimumLength] adding listener (total 2): net.sf.openrocket.gui.dialogs.motor.thrustcurve.MotorFilterPanel$10@42678bcb
368 153.163 VBOSE (DoubleModel.java:914) DoubleModel[MotorRowFilter:MaximumLength] adding listener (total 1): javax.swing.JSpinner$ModelListener@53c0a0af
369 153.164 VBOSE (DoubleModel.java:914) DoubleModel[MotorRowFilter:MaximumLength] adding listener (total 2): net.sf.openrocket.gui.dialogs.motor.thrustcurve.MotorFilterPanel$11@498a9668
370 153.173 VBOSE (AbstractChangeSource.java:25) Adding change listeners, listener count is now 1
371 153.192 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.dialogs.flightconfiguration.MotorMountTableModel@5a077d05, current number of listeners is 7
372 153.194 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.FlightConfigurableTableModel@76c40913, current number of listeners is 8
373 153.195 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.RecoveryConfigurationPanel$$Lambda$230/0x0000000800527c40@645b789e, current number of listeners is 9
374 153.196 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.SeparationConfigurationPanel$2@9544673, current number of listeners is 10
375 153.198 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
376 153.198 DEBUG (RocketFigure3d.java:141) Initializing RocketFigure3D OpenGL Canvas
377 153.198 DEBUG (RocketFigure3d.java:143) Setting up GL capabilities...
378 153.198 VBOSE (RocketFigure3d.java:145) GL - Getting Default Profile
379 153.198 VBOSE (RocketFigure3d.java:148) GL - creating GLCapabilities
380 153.198 VBOSE (RocketFigure3d.java:152) GL - setSampleBuffers
381 153.198 VBOSE (RocketFigure3d.java:155) GL - setNumSamples
382 153.198 VBOSE (RocketFigure3d.java:165) GL - Creating GLCanvas
383 153.198 VBOSE (RocketFigure3d.java:169) GL - Registering as GLEventListener on canvas
384 153.198 VBOSE (RocketFigure3d.java:172) GL - Adding canvas to this JPanel
385 153.198 VBOSE (RocketFigure3d.java:175) GL - Setting up mouse listeners
386 153.198 VBOSE (RocketFigure3d.java:178) GL - Rasterizing Carets
387 153.200 VBOSE (DoubleModel.java:914) DoubleModel[constant=0.0] adding listener (total 1): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$1@1b90ff8d
388 153.200 VBOSE (DoubleModel.java:914) DoubleModel[constant=0.0] adding listener (total 2): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$Ruler[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
389 153.200 VBOSE (DoubleModel.java:914) DoubleModel[constant=0.0] adding listener (total 3): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$Ruler[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
390 153.200 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
391 153.200 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
392 153.201 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
393 153.201 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
394 153.201 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
395 153.201 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
396 153.201 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@36f16163, current number of listeners is 11
397 153.205 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@2fdbee84, current number of listeners is 12
398 153.206 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@268197cf, current number of listeners is 13
399 153.206 VBOSE (DoubleModel.java:914) DoubleModel[RocketFigure:Rotation] adding listener (total 1): net.sf.openrocket.gui.components.UnitSelector[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=8388608,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,horizontalAlignment=LEADING,horizontalTextPosition=TRAILING,iconTextGap=4,labelFor=,text=,verticalAlignment=CENTER,verticalTextPosition=CENTER]
400 153.207 VBOSE (DoubleModel.java:914) DoubleModel[RocketFigure:Rotation] adding listener (total 2): javax.swing.JSlider$ModelListener@3e385fe
401 153.207 VBOSE (DoubleModel.java:914) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@228e039d
402 153.207 VBOSE (DoubleModel.java:936) DoubleModel[RocketFigure:Rotation] removing listener (total 2): javax.swing.plaf.basic.BasicSliderUI$Handler@228e039d
403 153.207 VBOSE (DoubleModel.java:914) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@339a5607
404 153.213 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
405 153.213 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@6deb53f2, current number of listeners is 14
406 153.213 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.scalefigure.RocketPanel$4@7e7e0aea, current number of listeners is 15
407 153.215 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
408 153.217 DEBUG (JarUtil.java:40) Found jar file using codeSource
409 153.217 DEBUG (ExampleDesignFile.java:118) Current jar file is: C:\Program Files\OpenRocket\.\OpenRocket.jar
410 153.223 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.main.BasicFrame$1@68aa8854, current number of listeners is 16
411 153.267 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
412 153.267 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.204235 user scale, 771.912 overall scale
413 153.270 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.204235 user scale, 771.912 overall scale
414 153.271 DEBUG (BasicFrame.java:262) ... Setting Initial Selection: [Quest Tomahawk Cruise Missile, Stage]
415 153.271 DEBUG (BasicFrame.java:266) BasicFrame instantiation complete
416 153.347 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.408470 user scale, 1543.82 overall scale
417 153.347 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.408470 user scale, 1543.82 overall scale
418 153.348 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.408470 user scale, 1543.82 overall scale
419 153.352 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.408470 user scale, 1543.82 overall scale
420 153.355 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.408470 user scale, 1543.82 overall scale
421 153.356 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.408470 user scale, 1543.82 overall scale
422 155.264 DEBUG (BasicFrame.java:1692) Disposing window
423 157.770 USER (BasicFrame.java:882) Bug report selected
424 157.773 DEBUG (JarUtil.java:40) Found jar file using codeSource
---------- End of bug report ----------

### PR DESCRIPTION
**Pull request by raynichc**
Fixes #1553, I had to remove the final keyword from the finset, I'm not sure it was explicitly needed, but if so, I can probably make it work.

### CODE REVIEW

**Comment by hcraigmiller** [comment]
Conversion from trapezoidal in Rocksim to freeform in OpenRocket works well. The only anomaly found was that the fin tab height dimension is incorrect after the conversion.

Build 1070
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
> The only anomaly found was that when fin tabs are present, the fin tab height dimension is incorrect after the conversion.

@hcraigmiller could you provide a RockSim design file with known tab height that is wrongfully imported in OR, so we can debug the issue? (since I don't have RockSim)

**Comment by hcraigmiller** [comment]
Here is the .rkt (used to import design) and the .ork (save after import) files.

[US Rockets 2.25 V2.Fin_Tabs.rkt.txt](https://github.com/openrocket/openrocket/files/9890857/US.Rockets.2.25.V2.Fin_Tabs.rkt.txt)
[US Rockets 2.25 V2.Fin_Tabs.ork.txt](https://github.com/openrocket/openrocket/files/9890860/US.Rockets.2.25.V2.Fin_Tabs.ork.txt)

Compare

Build 1070
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
Fin tabs should be fixed now.

**Comment by hcraigmiller** [comment]
Functions as expected, no anomalies found. Another one bites the dust.

Build 1141
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Pull request merged**
