### PR TITLE
[#875] Implement RASAero II importing

### LINKED ISSUE #875: RASAero import
It would be good to be able to import (and export, though I see that as less important) designs in RASAero's format.

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #875 and implements RASAero II file (.CDX1) importing. Almost all RASAero components are compatible with OR, although sometimes through the use of inline pods), except for some special stuff like special fin cross sections (see #1626) and protrusions on body tubes. RASAero also uses per-simulation based rocket weight and CG (override).

In short, the following information is imported:
- Rocket components
    - Surface finished are also imported
- Recovery devices
- Simulations
    - Launch site settings are also imported for each sim
    - Motors found in the OR database are also imported
- Comments of the rocket

An immense shoutout to @hcraigmiller for very thorough testing of this PR, and also for doing some preliminary coding in the past (e.g. creating the icons).

-----

Importing can be done in a dedicated menu item:
image

or in the File > Open menu:
image

Demo:

https://user-images.githubusercontent.com/11031519/226205795-37ae392f-197c-402b-8d87-353cd59d403a.mp4

-----

I have written some basic unit tests, but haven't implemented parameter checking for every imported component type, or checking e.g. each possible combination of recovery device importing (there are edge cases). As said before, @hcraigmiller has already done a great deal of testing, so I'm fairly confident that the importing should be stable and correct. So, I will just created a new issue request for extending the unit tests after this PR is merged. (Remind me to do so in case I forget)

If you want additional information on the importing, I advise you to ask @hcraigmiller, as I'm a bit busy at work right now.

### CODE REVIEW

**Comment by SiboVG** [comment]
Okay, there's an overflow error somewhere, will check it out...

**Comment by JoePfeiffer** [comment]
Wow!  This is a huge and important piece of work -- thank you!

**Comment by hcraigmiller** [comment]
Simulations of designs with rail buttons trigger uncaught exception.

**Comment by JoePfeiffer** [comment]
> Simulations of designs with rail buttons trigger uncaught exception.

I expect that to be fixed by PR #2115

**Comment by hcraigmiller** [comment]
@SiboVG, can you update this PR to include PR #2115.

**Comment by neilweinstock** [comment]
Is there any reason we would need to enlist Roger to help us test this?  It sounds like he is enthusiastic about this interworking.

**Comment by hcraigmiller** [comment]
> Is there any reason we would need to enlist Roger to help us test this? It sounds like he is enthusiastic about this interworking.

He has been through private messaging.

**Comment by neilweinstock** [comment]
OK, great.

**Comment by hcraigmiller** [comment]
When this PR is ready for testing, the rules that govern recovery devices is as follows:

**Placement**: 

NOTES: 
- RASAero II ONLY allows the placement of recovery devices in the sustainer (first stage).

RULES:
1. If the sustainer consists of one body tube then Recovery Device 1 is positioned near the top of the body tube with Recovery Device 2 positioned below Recovery Device 1.
2. If the sustainer consists of two body tubes then Recovery Device 1 is positioned near the top of the upper body tube with Recovery Device 2 positioned near the top of the second body tube down.
3. If the sustainer consists of three or more body tubes then Recovery Device 1 is positioned near the top of the upper body tube with Recovery Device 2 positioned near the top of the third body tube down.

**Eevent Configuration**:

NOTES: 
- RASAero II ONLY allows Recovery Event 1 to occur at _apogee_ and Recovery Event 2 to occur at a set _altitude_.
- RASAero II ONLY allows _parachute_ recovery devices.

RULES:
1. If Event 1 is unchecked OR checked but the Event 1 Event Type is set to None, then ignore ALL recovery events (Event 1 and Event 2). [No recovery events/devices in OR]
2. With Event 1 checked and Event 1 event type set to Apogee, if Event 2 is unchecked OR checked but the Event 2 Event Type is set to None, then ignore the Event 2 recovery event. [Event 1 is the only recovery event/device in OR]
3. With Event 1 checked and Event 1 Event Type set to apogee, if Event 2 is checked AND Event 2 Event Type is set to apogee, then change Event 2 Event Type to Altitude (and set the deployment altitude to the RASAero Deployment Altitude (or the OR default if not set in RASAero). [Event 1 must be at apogee and Event 2 must be at altitude in OR]
4. If an event Device is set to None, then change the event Device to parachute, set that event parachute Size to 0 and set the parachute Cd to the RASAero Cd (or the OR default if not set in RASAero). [Ballistic/tumble decent for that device]

Hopefully this will allow everyone testing this PR to understand why the recovery device placement and configuration conversion is behving the way that it is.

**Comment by hcraigmiller** [comment]
This is may fault. Placement Rules 2 and 3 need to be changed to better reflect the most common placement as follows:

RULES:

2. If the sustainer consists of two body tubes then Recovery Device 2 (deployment as set altitude) is positioned near the top of the upper body tube with Recovery Device 1 (deployment at apogee) positioned near the top of the second body tube down.
3. If the sustainer consists of three or more body tubes then Recovery Device 2 (deployment as set altitude) is positioned near the top of the upper body tube with Recovery Device 1 (deployment at apogee) positioned near the top of the third body tube down.

**Comment by SiboVG** [comment]
> Simulations of designs with rail buttons trigger uncaught exception.

Yes, that was because of #2115. I'll include #2122 in this PR.

**Comment by SiboVG** [comment]
> This is may fault. Placement Rules 2 and 3 need to be changed to better reflect the most common placement as follows:
> 
> RULES:
> 
> 2. If the sustainer consists of two body tubes then Recovery Device 2 (deployment as set altitude) is positioned near the top of the upper body tube with Recovery Device 1 (deployment at apogee) positioned near the top of the second body tube down.
> 3. If the sustainer consists of three or more body tubes then Recovery Device 2 (deployment as set altitude) is positioned near the top of the upper body tube with Recovery Device 1 (deployment at apogee) positioned near the top of the third body tube down.

Updated the rules.

**Comment by JoePfeiffer** [comment]
I'm not sure the rule on the placement of the second recovery device with more than three tubes is accurate, due to the presence of both payload sections and switch bands.

If one tube is very short (under, say, 5cm? Under half a caliber?) it's probably a switch band.  Recovery devices will typically be in the body tubes just forward and aft of the switch band.

If there are four long tubes (so no identifiable switch band) I'd expect the first to be a payload bay, the second to contain the second recovery device, the third to contain the first recovery device, and the last to contain the motor.

**Comment by neilweinstock** [comment]
As a very general philosophy, if we need to do a lot of inference to figure out some of this stuff when importing, I think it's perfectly fine to just take our best guess and then put up a dialog warning the user to go and check it.  Even better if we can identify in that dialog exactly which components need checking.

**Comment by hcraigmiller** [comment]
> I'm not sure the rule on the placement of the second recovery device with more than three tubes is accurate, due to the presence of both payload sections and switch bands.
> 
> If one tube is very short (under, say, 5cm? Under half a caliber?) it's probably a switch band. Recovery devices will typically be in the body tubes just forward and aft of the switch band.
> 
> If there are four long tubes (so no identifiable switch band) I'd expect the first to be a payload bay, the second to contain the second recovery device, the third to contain the first recovery device, and the last to contain the motor.

This would suggest a change in the placement rules below.

RULES:

3. If the sustainer consists of three or more body tubes AND if a body tube after the first body tube is less that .8 calibers, then Recovery Device 2 (deployment as set altitude) is positioned near the top of the body tube just above the first body tube of less than .8 calibers with Recovery Device 1 (deployment at apogee) positioned near the top of the body tube just below the first body tube of less than .8 calibers; otherwise,
4. If the sustainer consists of three body tubes then Recovery Device 2 (deployment as set altitude) is positioned near the top of the first body tube with Recovery Device 1 (deployment at apogee) positioned near the top of the third body tube.
5. If the sustainer consists of more than three body tubes then then Recovery Device 2 (deployment as set altitude) is positioned near the top of the second body tube with Recovery Device 1 (deployment at apogee) positioned near the top of the fourth body tube.

@JoePfeiffer, does this position rule change satisfy your concern?

**Comment by hcraigmiller** [comment]
It looks like override rules are needed.

RULES:

NOTES:
- RASAero II limits the number of stages to three.
- Where a flight simulation exists, RASAero II requires the CG and loaded weight for each powered vehicle (sustainer, sustainer plus first booster together, and sustainer plus first and second boosters together).
- To avoid potential RASAero II value discrepancies between flight simulations (where the design has more than one flight simulation), only the first simulation is used to set the overrides. 

1. (a) Override the OpenRocket Stage 1 mass including subcomponents with [the RASAero II Sustainer loaded weight minus the OpenRocket mass of the Stage 1 motor] (with only Stage 1 active, the mass with motors should match the RASAero II sustainer total loaded weight); (b) override the Stage 1 CG including subcomponents with the RASAero II Sustiner CG (with only Stage 1 active, the OpenRocket CG should match the RASAero II sustainer CG).
2. If the design has a second stage, (a) Override the OpenRocket Stage 2 mass including subcomponents with [the RASAero II Stage 2 loaded weight minus the OpenRocket mass of Stage 1 and the Stage 1 motor AND minus the mass of the Stage 2 motor] (with only Stage 1 and Stage 2 active, the mass with motors should match the RASAero II first booster total loaded weight); (b) override the Stage 2 CG including subcomponents with the RASAero II CG for Stage 2 (with only Stage 1 and stage 2 active, the OpenRocket CG should match the RASAero II first booster CG).
3.  If the design has a third stage, (a) Override the OpenRocket Stage 3 mass including subcomponents with [the RASAero II Stage 3 loaded weight minus the OpenRocket mass of Stage 1 and the Stage 1 motor AND minus the mass of Stage 2 and the Stage 2 motor AND minus the mass of the Stage 3 motor] (with all three stages active, the mass with motors should match the RASAero II second booster total loaded weight); (b) override the Stage 3 CG including subcomponents with the RASAero II CG for second booster (with Stage 1, Stage 2, and Stage 3 active, the OpenRocket CG should match the RASAero II second booster CG).

When importing RASAero II designs, it is assumed that the user accurately measured the RASAero II loaded weight and CG values for each simulations.

@SiboVG, should this be included in this PR or be a separate PR?

**Comment by JoePfeiffer** [comment]
@hcraigmiller writes
>     3. If the sustainer consists of three or more body tubes AND if a body tube after the first body tube is less that .8 calibers, then Recovery Device 2 (deployment as set altitude) is positioned near the top of the body tube just above the first body tube of less than .8 calibers with Recovery Device 1 (deployment at apogee) positioned near the top of the body tube just below the first body tube of less than .8 calibers; otherwise,

Looks good

>     4. If the sustainer consists of three body tubes then Recovery Device 2 (deployment as set altitude) is positioned near the top of the first body tube with Recovery Device 1 (deployment at apogee) positioned near the top of the third body tube.

I'd expect RD1 to be positioned in the second body tube.  The third is the "fin can" and motor, and is ejected at drogue deployment.

>     5. If the sustainer consists of more than three body tubes then then Recovery Device 2 (deployment as set altitude) is positioned near the top of the second body tube with Recovery Device 1 (deployment at apogee) positioned near the top of the fourth body tube.

I'd expect RD1 to be in the third body tube (the fourth would be fin can/motor).

To phrase it differently, I'd expect the tubes to be:
payload (optional)
tube containing main chute
switch band (optional; identifiable because it's short)
tube containing drogue chute
tube with fins and motor

**Comment by hcraigmiller** [comment]
Consistent with the comments of @JoePfeiffer, **if a vent band is not identified** then the expectation would be (1) payload (tube count >3), (2) tube containing main chute, (3) tube containing drogue chute, and (4) additional tubes.

The change to the rules to accomplish this would be as set forth below.

RULES (Existing and with changes):

1. If the sustainer consists of one body tube then Recovery Device 1 (deployment at apogee) is positioned near the top of the body tube with Recovery Device 2 (deployment as set altitude) positioned just below Recovery Device 1, both in the same body tube.
2. If the sustainer consists of two body tubes then Recovery Device 1 (deployment at apogee) is positioned near the top of the lower body tube with Recovery Device 2 (deployment as set altitude) positioned near the top of the upper body tube.
3. **[CHANGE TO]** If the sustainer consists of three or more body tubes AND if a body tube after the first body tube is less that .8 calibers, then Recovery Device 2 (deployment as set altitude) is positioned near the top of the body tube immediately below the first body tube of less than .8 calibers with Recovery Device 1 (deployment at apogee) positioned near the top of the body tube immediately above the first body tube of less than .8 calibers; OTHERWISE,
4. **[CHANGE TO]** If the sustainer consists of three body tubes then Recovery Device 2 (deployment as set altitude) is positioned near the top of the second body tube with Recovery Device 1 (deployment at apogee) positioned near the top of the first body tube.
5. **[CHANGE TO]** If the sustainer consists of more than three body tubes then Recovery Device 2 (deployment as set altitude) is positioned near the top of the third body tube with Recovery Device 1 (deployment at apogee) positioned near the top of the second body tube.

**Comment by JoePfeiffer** [comment]
I think we're ending up talking past each other.  My sense of the rules would be:

1. If the sustainer consists of one body tube then Recovery Device 1 (deployment at apogee) is positioned near the top of the body tube with Recovery Device 2 (deployment at set altitude) positioned just below Recovery Device 1, both in the same body tube. (this is unchanged, and copied for completeness)

2.  If the sustainer consists of two body tubes then Recovery Device 1 (deployment at apogee) is positioned near the top of the lower body tube with Recovery Device 2 (deployment at set altitude) positioned near the top of the upper body tube. (likewise unchanged)

3.  If the sustainer consists of three or more body tubes AND if a body tube after the first body tube is less than .8 calibers, then Recovery Device 1 (deployment at apogee) is positioned near the top of the body tube immediately below the first body tube of less than .8 calibers with Recovery Device 2 (deployment at set altitude) positioned near the top of the body tube immediately above the first body tube of less than .8 calibers [this assumes that the first "stubby" body tube is the vent band]; (this reverses recovery devices 1 and 2 from your last list) OTHERWISE,

4. If the sustainer consists of three or more body tubes AND a vent band is not identified then Recovery Device 1 (deployment at apogee) is positioned in the next-to-last body tube, and Recovery Device 2 (deployment at set altitude) is positioned in the tube immediately forward of that one (this reverses the order of the recovery devices, and also sets the tubes containing them based on the motor tube at the rear.

**Comment by hcraigmiller** [comment]
> 4\. If the sustainer consists of three or more body tubes AND a vent band is not identified then Recovery Device 1 (deployment at apogee) is positioned in the next-to-last body tube, and Recovery Device 2 (deployment at set altitude) is positioned in the tube immediately forward of that one ([1] **this reverses the order of the recovery devices**, and also [2] **sets the tubes containing them based on the motor tube at the rear**.

[1] Both are the same order, just worded differently.

[2] I have had situations where the length of the lower body tube was insufficient to accept the motor and an extension body tube and coupler were required to accommodate the motor. Using your placement, the parachute would effectively be in the motor tube. Moreover, if you have multiple transitions, you may have 4 or more body tubes (I have one design with close to 10 body tubes), and I can't think of a situation where I would want the placement of the parachutes referenced to the bottom body tube so much as wanting the parachutes as high in the rocket as possible (after the payload bay).

@JoePfeiffer, do you have a specific situation or RASAero II compatible design in mind that should reference the bottom body tube when there are three or more body tubes (without a vent band)?

**Comment by JoePfeiffer** [comment]
> [1] I have had situations where the length of the lower body tube was insufficient to accept the motor and an extension body tube and coupler were required to accommodate the motor. Using your placement, the parachute would effectively be in the motor tube. Moreover, if you have multiple transitions, you may have 4 or more body tubes (I have one design with close to 10 body tubes), and I can't think of a situation where I would want the placement of the parachutes referenced to the bottom body tube so much as wanting the parachutes as high in the rocket as possible (after the payload bay).

Good point.  I don't tend to think of dual-deploy rockets as having particularly complex configurations.  So yes, as far forward as possible, after a tube inferred to be a payload bay, is good.

>     3. If the sustainer consists of three or more body tubes AND if a body tube after the first body tube is less than .8 calibers, then Recovery Device 1 (deployment at apogee) is positioned near the top of the body tube immediately below the first body tube of less than .8 calibers with Recovery Device 2 (deployment at set altitude) positioned near the top of the body tube immediately above the first body tube of less than .8 calibers [this assumes that the first "stubby" body tube is the vent band], OTHERWISE. [Copied comment of @JoePfeiffer]

Looks good.

>     4. If the sustainer consists of three or more body tubes AND a vent band is not identified then Recovery Device 1 (deployment at apogee) is positioned near the top of the second body tube and Recovery Device 2 (deployment at set altitude) is positioned near the top of the third body tube. [Copied and reworded comment of @hcraigmiller]

This puts the drogue ahead of the main, where I believe the opposite should be true.  So Recovery Device 1 should be in the second tube if there are three tubes (ie no payload bay) or the third if there are four or more (ie there is a payload bay).  Recovery Device 2 should be in the first tube if there are three (no payload bay) or the second if there are four or more (so there is a payload bay).

> @JoePfeiffer, do you have a specific situation or RASAero II compatible design in mind that should reference the bottom body tube when there are three or more body tubes (without a vent band)?

For a simple design with no switch band and only three or four tubes, my phrasing based on the motor tube says the same thing as my comments above, more simply.  Our dual deploy example, with the switch band removed,  would be an example here. For a complicated (ten tubes in a dual deploy rocket? Wow!) design, you're right we sort of have to work from the front.

**Comment by hcraigmiller** [comment]
> This puts the drogue ahead of the main, where I believe the opposite should be true.

Agreed, Recovery Device 1 should always be below Recovery Device 2.

RESTATED RULES:

1. If the sustainer consists of one body tube then Recovery Device 1 (deployment at apogee) is positioned near the top of the body tube with Recovery Device 2 (deployment at set altitude) positioned just below Recovery Device 1, both in the same body tube.
2. If the sustainer consists of two body tubes then Recovery Device 1 (deployment at apogee) is positioned near the top of the lower body tube with Recovery Device 2 (deployment at set altitude) positioned near the top of the upper body tube.
3. [CHANGE TO] If the sustainer consists of three or more body tubes AND if a body tube after the first body tube is less than .8 calibers, then Recovery Device 2 (deployment at set altitude) is positioned near the top of the body tube immediately below the first body tube of less than .8 calibers with Recovery Device 1 (deployment at apogee) positioned near the top of the body tube immediately above the first body tube of less than .8 calibers [this assumes that the first "stubby" body tube is the vent band]; OTHERWISE.
4. [CHANGE TO] If the sustainer consists of three or more body tubes AND a vent band is not identified then Recovery Device 1 (deployment at apogee) is positioned near the top of the **third** body tube and Recovery Device 2 (deployment at set altitude) is positioned near the top of the **second** body tube. [Copied and reworded comment of @hcraigmiller]

The difference between referencing the top vs the bottom.

Compare

This is why I suggested referencing from the top.
Your thoughts @JoePfeiffer?

**Comment by JoePfeiffer** [comment]
Your rule 3 is still placing recovery device 2 below the switch band, and device 1 above it.  These should be reversed.

For that example rocket, my wording of referencing from the bottom puts the chutes in the same tubes as your referencing from the top (I specify recovery device 1 in the next to last tube, not the last tube, and recovery device 2 in the tube before that).  Where it makes an actual difference is when you've extra tubes and transitions, in which case referencing from the top as you suggest is preferred.

**Comment by hcraigmiller** [comment]
@SiboVG, consensus reached:
Rules Recovery Device Placement

With corrections by @JoePfeiffer due to my continuous brain fart as to the vent band rule...

**Comment by SiboVG** [comment]
> @SiboVG, consensus reached: Rules Recovery Device Placement
> 
> With corrections by @JoePfeiffer due to my continuous brain fart as to the vent band rule...

Alright, thanks! Will correct it soon.

**Comment by JoePfeiffer** [comment]
Almost!  If there are exactly three body tubes (ie no payload section and no vent band) and two recovery devices, device 1 is in tube 2 and device 2 is in tube 1.

**Comment by hcraigmiller** [comment]
Addition requested by @JoePfeiffer:
Rules Recovery Device Placement

**Comment by SiboVG** [comment]
Phew, I'm gonna have a beer once this PR is merged.

**Comment by JoePfeiffer** [comment]
Looks good! Thanks for your patience with my nit picking @hcraigmiller and @SiboVG .

Is it waiting on anything else?

**Comment by SiboVG** [comment]
The new rules should be in place now.

**Comment by hcraigmiller** [comment]
Errors:

VBC = Vent Band Count
VBP = Vent Band Position (BT count from top)

**1 RECOVERY DEVICE**

**1 Body Tubes, VBC=0**:  Correct.

**2 Body Tubes, VBC=0**: Recovery Device 1 is positioned in BT-2 (Recovery Device 1 should be in BT-1).

**3 Body Tubes, VBC=0**:  Correct.

**4+ Body Tubes, VBC=0**:  Recovery Device 1 is positioned in BT-3 (Recovery Device 1 should be in BT-2).

**3+ Body Tubes, VBC=1, VBP=2**: Recovery Device 1 is positioned below the vent band (it should be above the vent band).

**2 RECOVERY DEVICES**

**1 Body Tubes, VBC=0**:  Correct.

**2 Body Tubes, VBC=0**: Recovery Device 1 (deployment at apogee) is positioned over the top of Recovery Device 2 near the top of the first body tube (Recovery Device 1 should be in the second body tube).

**3 Body Tubes, VBC=0**: Recovery Device 1 (deployment at apogee) is positioned over the top of Recovery Device 2 near the top of the first body tube (Recovery Device 1 should be in the second body tube).

**4 Body Tubes, VBC=0**:  Correct.

**5 Body Tubes, VBC=0**:  Correct.

**6 Body Tubes, VBC=0**:  Correct.

**3 Body Tubes, VBC=1, VBP=2**: Recovery Device 1 (deployment at apogee) is positioned over the top of Recovery Device 2 near the top of the body tube immediately above (Recovery Device 1  should be below) the first body tube of less than .8 calibers.

**4 Body Tubes, VBC=1, VBP=2**: Recovery Device 1 (deployment at apogee) is positioned over the top of Recovery Device 2 near the top of the body tube immediately above (Recovery Device 1  should be below) the first body tube of less than .8 calibers.

**IF BTC=>5 then Recovery Device 1 is always placed in BT-2 and Recovery Device 2 is always placed in BT-3.**

**5 Body Tubes, VBC=1, VBP=2**: Recovery Device 2 is positioned in BT-2 the vent band (should be BT-1 above the vent band).

**5 Body Tubes, VBC=1, VBP=3**: Recovery Device 1 is positioned in BT-3 the vent band (it should be below the vent band).

**5 Body Tubes, VBC=1, VBP=4**: Recovery Device 1 is positioned in BT-2 (should be BT-3) and the vent band Recovery Device 1 is positioned in BT-3 (should be BT-4)

**Comment by SiboVG** [comment]
Sorry, there was a small logic error that cause issues with recovery device 1.

> **5 Body Tubes, VBC=1, VBP=2**: Recovery Device 2 is positioned in BT-2 the vent band (should be BT-1 above the vent band).
> 
> **5 Body Tubes, VBC=1, VBP=3**: Recovery Device 1 is positioned in BT-3 the vent band (it should be below the vent band).
> 
> **5 Body Tubes, VBC=1, VBP=4**: Recovery Device 1 is positioned in BT-2 (should be BT-3) and the vent band Recovery Device 1 is positioned in BT-3 (should be BT-4)

Okay, I thought from your image that once you have 4+ body tubes, I should ignore the VB. I'll adjust it.

**Comment by SiboVG** [comment]
I **hope** it's correct this time.

**Comment by SiboVG** [comment]
Okay, I actually think my previous commit fixed the issue. I used an ArrayList, which can sometimes mess up the ordering of the items. Care to try again @hcraigmiller?

**Comment by SiboVG** [comment]
Oh yeah, and I love how organized you are 😍.

**Comment by hcraigmiller** [comment]
One more time:
Rules Recovery Device Placement 1649

Not sure what happened, went from correct to ncorrect.

**Comment by SiboVG** [comment]
> One more time: Rules Recovery Device Placement 1649
> 
> Not sure what happened, went from correct to ncorrect.

Ah, that was a typo in the code... Should be done now.

**Comment by hcraigmiller** [comment]
Alright, that merge was accidental. The all of the placements are correct. Should the merge be left or reverted?

**Comment by SiboVG** [comment]
> Alright, that merge was accidental. All of the placements are correct. Should the merge be left or reverted?

Recovery device placement was the final check for this PR, so it's okay to leave it.

**Comment by hcraigmiller** [comment]
I hit the revert button before I asked. How do I clear it?

**Comment by SiboVG** [comment]
> I hit the revert button before I asked. How do I clear it? Untitled

I deleted the revert branch, it's fine now. I went to the openrocket repo (not your own), then clicked on the branches
image

and there you can delete the revert branch:
image

**Pull request merged**
