### PR TITLE
Add option to switch (time) flight event markers to icons

### PR DESCRIPTION
**Pull request by SiboVG**
I recently noticed that apparently, when you make a sim plot where the x axis type is not time, OpenRocket plots the flight event markers using icons, instead of vertical markers. Since I think the markers can get messy pretty easily, I now added the option for time domain plots to switch between vertical markers and icon markers.

I also made the tooltip text of flight event icons more elaborate, to include the x axis value and sample count.

https://user-images.githubusercontent.com/11031519/210019076-360ffd3f-450b-4cc1-82cc-75e4aa53cd57.mp4

### CODE REVIEW

**Comment by hcraigmiller** [comment]
First of all, I like this option. . . it really cleans up the view. But I found events that appear to be on the wrong stage, unless I'm reading it wrong.

Flight Plot Icons

**Comment by JoePfeiffer** [comment]
Very nice option.  I'm seeing the same thing as Craig; it also appears to be displaying all the icons regardless of whether a given branch is shown or not.

**Comment by SiboVG** [comment]
Should be fixed now.

**Comment by hcraigmiller** [comment]
Icons still appearing on wrong stage.

Using the _Three-stage rocket_ example:
Flight Plot Icons No_02

**Comment by SiboVG** [comment]
Ah my bad, didn't read your notes right. I fixed another bug where switching between the stage view type (e.g. switching to "Booster stage(1)" instead of "All") did not properly render the icons.

**Comment by SiboVG** [comment]
Try no. 2, should be working now.

**Comment by hcraigmiller** [comment]
Single stage and multi-stage function without anomalies found. But powered pods still have a few problems.

Flight Plot Icons No_03

[Powered Pods with Recovery.ork.txt](https://github.com/openrocket/openrocket/files/10326156/Powered.Pods.with.Recovery.ork.txt)

**Comment by SiboVG** [comment]
> Single stage and multi-stage function without anomalies found. But when powered pods are added there are still a few problems.
> 
> Flight Plot Icons No_03
> 
> [Powered Pods with Recovery.ork.txt](https://github.com/openrocket/openrocket/files/10326156/Powered.Pods.with.Recovery.ork.txt)
> 
> The more I play with the flight icons, the more I prefer it over the lines. . . nice!

Hm, this appears to be a pre-existing problem. If you open that file in beta 05 and zoom in (in this case for the parachute deployment), you can see these issues.

image

Should we move it into a separate issue?

**Comment by hcraigmiller** [comment]
If it’s preexisting, yes. Besides, I like the icons too much to hold them up.

**Comment by hcraigmiller** [comment]
Looks good to go. As to single stage and multi-stages, functions as expected with no anomalies found.

PR created for preexisting incorrect flight events when powered pods have recovery devices.

Build 1365
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
Latest commit changes the naming from "Vertical marker" to "Vertical line".

image

**Comment by hcraigmiller** [comment]
Functions as expected with no anomalies found. I really do like the icons.

Build 1368
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Pull request merged**
