### PR TITLE
[fixes #641] MassCalculator now accounts for rotations in the tree

### LINKED ISSUE #641: CG calculation error
CG is sometimes shown off-axis in 3D Finished view.  See attached design.

Side view:
image

3D Finished view:
image

Tested on latest unstable build.

[cg_render_bug.ork.zip](https://github.com/openrocket/openrocket/files/4562127/cg_render_bug.ork.zip)

This issue was previously glommed onto #387, I've separated it out here.

### PR DESCRIPTION
**Pull request by teyrana**
This should fix C.G. calculations for Fins-on-pods.

~Would also like to refactor this to be cleaner.~
Refactor is too big a change to be appropriate, here.

### CODE REVIEW

**Comment by JoePfeiffer** [comment]
All looks reasonable, and passes unit tests.

Hmmm, I thought the off-center CP was fixed.  It's certainly still there, though, isn't it...

I've also asked Billy to look at it -- he's better at code reviews than I am.

**Comment by teyrana** [comment]
> All looks reasonable, and passes unit tests. Should the minimum mass comparisons be against MIN_MASS rather than 0?

Good point.  Do you have a specific point you're referring to? 

> Hmmm, I thought the off-center CP was fixed. It's certainly still there, though, isn't it... (see my new #654).

This PR doesn't address that.   It looks like the latest is #654. 

> I've also asked Billy to look at it -- he's better at code reviews than I am.

Sounds good. I'll hold this open until he's had a chance to look at it.

**Comment by JoePfeiffer** [comment]
> > Hmmm, I thought the off-center CP was fixed. It's certainly still there, though, isn't it... (see my new #654).
> 
> This PR does not address Center-of-Pressure calculations. It only address CoM/CoG calculations.

Right -- I was just bummed to observe this while I was running the code.  It's not relevant to this PR.

**Comment by teyrana** [comment]
@JoePfeiffer 

FYI, this change is the one that causes a test failure in IntegrationTest.SimpleRocket. :/

> All looks reasonable, and passes unit tests. Should the minimum mass comparisons be against MIN_MASS rather than 0?

**Pull request merged**
