### PR TITLE
Also check color when using default material

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes a confusion from TRF [here](https://www.rocketryforum.com/threads/wanted-beta-testers-for-the-next-release-of-openrocket.181945/post-2496881) regarding the "Select all of same color" feature. Previously, when the currently selected component had its appearance set to default, using "Select all of same color" would only select other components **of the same type** that also had the default appearance checked. In the post on TRF, both the nose cone and transition used the default appearance and had the same white color, but the same-color selection did not work.

This PR now ensures that when the currently selected component has the default appearance, it will check for all other components that **also have the default appearance** and have the same default appearance, regardless of whether its the same component type as the selected component or not.

### CODE REVIEW

**Comment by SiboVG** [comment]
copilot:poem

**Comment by JoePfeiffer** [comment]
Should we call this a bug fix to squeeze in before release, or an enhancement for right after release?

**Comment by SiboVG** [comment]
> Should we call this a bug fix to squeeze in before release, or an enhancement for right after release?

Not sure; it would make sense to merge it before the release, since the same-color selection was introduced in this release. The code change itself isn't all too major either.

**Comment by neilweinstock** [comment]
> Not sure; it would make sense to merge it before the release, since the same-color selection was introduced in this release.

This is exactly why I was going to recommend merging.  Good job Sibo.

**Pull request merged**
