### PR TITLE
[Resolve #571] Add message fins-on-phantom-bodies

### LINKED ISSUE #571: Add more descriptive messages for Fins-on-phantom-bodies
Currently the warning is something like "thick fins -- accuracy may suffer".  Change this to something like "fins on phantom bodies are allowed, but discouraged -- simulation accuracy may suffer"

Comments on wording are welcome!

@neilweinstock @JoePfeiffer

### PR DESCRIPTION
**Pull request by teyrana**
Adds a new error message to warn users about mounting fins on phantom bodies:

implementation

Runnable jar:
https://drive.google.com/open?id=1wY6ydj5zBnv4VT6QQlKepTxEuNWOLmQC

This is a purely cosmetic change; as such it's subjective.

### CODE REVIEW

**Comment by neilweinstock** [comment]
Might I suggest a very slight trim, so maybe it'll fit a little more easily?

> Phantom bodies (zero length or radius) may produce inaccurate simulations.

Also note capitalization; in all warnings I checked, only first word was capitalized.

**Comment by teyrana** [comment]
> Also note capitalization; in all warnings I checked, only first word was capitalized.

Aye.  Sentence casing?  Sure, we can change that.    In any case, I don't have any strong opinion there..

My concern -- does the message convey the actual rocket situation? in your opinion?

**Comment by neilweinstock** [comment]
> My concern -- does the message convey the actual rocket situation? in your opinion?

Yes, although thought my edit, suggested above, made it just a bit more clear and succinct.

Since then, though, I've had a couple more thoughts:
1. This warning was originally a substitute for a thick fin warning.  That concerned only phantom bodies with zero radius.  Therefore, unless this warning is generated in other places as well, it shouldn't mention zero length.
2. There's no reason to include a definition of phantom bodies in the warning, much like "Thick fin warning" doesn't have a full definition of what a thick fin is.

Therefore, my new proposed edit would be:

> Body tubes with zero radius may produce inaccurate simulations.

If this message is indeed used in other places, triggered by a zero *length* tube, then you can say

> Body tubes with zero length or radius may produce inaccurate simulations.

These say exactly what your original wording did, just more succinctly.  What do you think?

- Neil

**Comment by JoePfeiffer** [comment]
Maybe "Fins on body tubes with zero length or radius may produce inaccurate results"?

**Comment by neilweinstock** [comment]
> Maybe "Fins on body tubes with zero length or radius may produce inaccurate results"?

Are we actually checking for zero length tubes anywhere?  If not we should leave out the "length or".

If this message is exclusively for fins on zero radius tubes (alternative to the "thick fin warning") then I'm in favor of Joe's wording.  It's quite precise.

Anyway, if this warning is just for fins on phantom tubes then

**Comment by JoePfeiffer** [comment]
To the best of my knowledge, we aren't.  Yes, we could have the warning only talk about 0 radius (I'm just developing a pessimism that even if we aren't checking it now, sooner or later we're going to discover we should be).

**Comment by neilweinstock** [comment]
I don't disagree, but in that case couldn't we just change it then?

**Comment by JoePfeiffer** [comment]
Or even make that a separate warning, I suppose.

**Comment by neilweinstock** [comment]
Either way.


________________________________

Ce message, ainsi que tous les fichiers joints à ce message, peuvent contenir des informations sensibles et/ ou confidentielles ne devant pas être divulguées. Si vous n'êtes pas le destinataire de ce message (ou que vous recevez ce message par erreur), nous vous remercions de le notifier immédiatement à son expéditeur, et de détruire ce message. Toute copie, divulgation, modification, utilisation ou diffusion, non autorisée, directe ou indirecte, de tout ou partie de ce message, est strictement interdite.


This e-mail, and any document attached hereby, may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized, direct or indirect, copying, disclosure, distribution or other use of the material or parts thereof is strictly forbidden.

**Comment by teyrana** [comment]
Okay, I've split this into two separate warnings -- one for zero-length bodies, and one for zero-radius bodies.   

Exact messages are: 
1. "Zero length bodies may not result in accurate simulations."
2. "Zero radius bodies may not result in accurate simulations."

**Comment by neilweinstock** [comment]
I would still prefer "may produce inaccurate simulations" or "may produce inaccurate results", but I'll sign off on what you have there.

**Comment by JoePfeiffer** [comment]
lgtm

**Comment by neilweinstock** [comment]
Looks like the messages both say "zero length" instead of one of them saying "zero radius".

**Pull request merged**
