### PR TITLE
[#1532] Custom focus travel policy for component config dialogs

### PR DESCRIPTION
**Pull request by SiboVG**
This is a first draft of fixing #1532, which improves traversing through a component config dialog by pressing the tab/shift-tab key. (more logical order and focusable components).

**Do not test this PR yet.** Just putting it up so that @RemingtonHolder can continue to work on my branch, and I can track his progress more easily through this PR.

By this point, only the body tube config traversal is done, the rest will be implemented by @RemingtonHolder.

### CODE REVIEW

**Comment by RemingtonHolder** [comment]
## Finished Config Dialogs/Panels: 
_*Most Listed By File Name Within The Config Dialog Folder_
### General Tabs:
- [x] AppearancePanel
- [x] OveridePanel
- [x] CommentPanel
- [x] ShoulderPanel
- [x] MotorConfig

### All Other Diologs/Panels:
- [ ] AxialStageConfig
- [x] BodyTubeConfig
- [ ] BulkheadConfig
- [ ] CenteringRingConfig
- [ ] CommonStrings
- [ ] ComponentAssemblyConfig
- [ ] ComponentConfigDialog
- [ ] EllipticalFinSetConfig
- [ ] FinSetConfig
- [ ] FreeformFinSetConfig
- [ ] ClusterSelectionPanel
- [ ] InnerTubeConfig
- [ ] LaunchLugConfig
- [ ] MassComponentConfig
- [ ] MaterialPanel
- [ ] NoseConeConfig
- [ ] ParachuteConfig
- [ ] RailButtonConfig
- [ ] RecoveryDeviceConfig
- [ ] RingComponentConfig
- [ ] RocketComponentConfig
- [ ] RocketConfig
- [ ] ShockCordConfig
- [ ] SleeveConfig
- [ ] StreamerConfig
- [ ] ThicknessRingComponentConfig
- [ ] TransitionConfig
- [ ] TrapezoidFinSetConfig
- [ ] TubeFinSetConfig

**Comment by RemingtonHolder** [comment]
@SiboVG Only panels that are not descendants of `RocketComponentConfig` need to be passed the order arraylist correct?

**Comment by RemingtonHolder** [comment]
@SiboVG Any suggestion for the traversal policy on the freeform fin set shape tab?

**Comment by RemingtonHolder** [comment]
Would like to point out that the ant unit test fails when testing the core package. I haven't been touching the core package at all so I believe it is just a random hang.

**Comment by SiboVG** [comment]
> Would like to point out that the ant unit test fails when testing the core package. I haven't been touching the core package at all so I believe it is just a random hang.

Yes, I know which unit tests you're talking about (it's comparing 2 simulation results, but since simulation results can vary between different runs, at some random runs, the unit tests fail due to a too large difference between the 2 simulations). Planning on increasing the error margin for that unit test soon.

**Comment by RemingtonHolder** [comment]
Am still open for suggestions by anyone on how tab traversal should work for the freeform fin set shape tab

**Comment by SiboVG** [comment]
> @SiboVG Any suggestion for the traversal policy on the freeform fin set shape tab?

I would only focus the leftmost table.

**Comment by neilweinstock** [comment]
> > @SiboVG Any suggestion for the traversal policy on the freeform fin set shape tab?
> 
> I would only focus the leftmost table.

I agree, nothing else would really make any sense.

I am really looking forward to these changes, and will have to test this out ASAP.  Thanks @RemingtonHolder for slogging through all these different dialogs to get this done.

**Comment by SiboVG** [comment]
Shape tab focussing now implemented, so this PR is ready to be tested.

**Comment by hcraigmiller** [comment]
Testing observations and comments.

**Stage**: 
Functions as expected.

**Booster Set**:
All tabs: Tab key does not include “Close” button in cycle. [Bug]
General Tab: Tab key only cycles between “Component name” and “General” tab. [Bug]

**Pod Set**:
Functions as expected.

**Components** (All):

_Parts Library_:
Without a change in highlighting, the tab key moves across an item’s line for the column count (one tab key press for each column) before the next line is highlighted. [Expected?]

_Appearance Tab_:
“Figure style” with “Use default color” unchecked, “Save as default style” is not in tab key cycle. [Bug]

_Freeform Fin Shape Tab_:
Without a change in highlighting, the tab key moves across an X/Y line for the column count (one tab key press for each column) before the next line is highlighted. [Bug?]

In all other respects, components function as expected.

[Windows 11 Pro; Version 21H2; OS Build 22000.739; Windows Feature Experience Pack 1000.22000.739.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
> Without a change in highlighting, the tab key moves across an X/Y line for the column count (one tab key press for each column) before the next line is highlighted. [Bug?]

This should be kept as is, so a user can edit each point value (X and Y value) by pressing the tab key.

All other mentioned bugs should be fixed now.

**Comment by SiboVG** [comment]
> * ~AxialStageConfig~ _(Does not appear to be in use anymore)_
>   ~RocketConfig~ _(Does not appear to be in use anymore)_
>   ~ComponentAssemblyConfig~ _(Does not appear to be in use anymore)_

They are, but you probably can't see their usage in IntelliJ's search method because OR uses string class generation to invoke those config dialogs.

**Comment by SiboVG** [comment]
> All other mentioned bugs should be fixed now.

Oh yeah, I also modified the config dialog tabbed pane so that when you change the selection to a new tab, the tab requests focus. Previously the focus did not change when you switched tabs. For example if the component name text box was selected and you switched to the appearance tab, the component name text box still had focus.

I did this so that when you switch tabs, you are only one tab key-press away from the first GUI widget in the new tab. Previously, you always had to cycle through the first config dialog widgets (component name, preset combobox, preset button, and tab) to get to the first tab widget.

**Comment by RemingtonHolder** [comment]
> > * ~AxialStageConfig~ _(Does not appear to be in use anymore)_
> 
> >   ~RocketConfig~ _(Does not appear to be in use anymore)_
> 
> >   ~ComponentAssemblyConfig~ _(Does not appear to be in use anymore)_
> 
> 
> 
> They are, but you probably can't see their usage in IntelliJ's search method because OR uses string class generation to invoke those config dialogs.

That explains it! Also sorry for the absence, school started back up and it's taking me a bit to get back in the swing of things.

**Comment by hcraigmiller** [comment]
Observations:

_Parts Library_
- Once the focus enters the grid, it cycles continuously within the grid, it does not leave the grid. [Different than Build 964]

_Freeform fin set shape tab_
- Once the focus enters the grid, it cycles continuously within the grid, it does not leave the grid. [Same as Build 964]
- Cycle does not include "-", Fit, "+", Scale Fin, Import from Image, or Export CVS; tab from these items goes to Component name. [Same as Build 964, except Close button is now cycles] [Bug]

Having used the grid behavior both ways, I believe that cycling continuously within the grid may be the best behavior because, in the parts library, once you have the component that you want highlighted, you need to close the pane to activate the change; continuing to tab through the grid will deselect the component you want. Although not entirely the same thing with the freeform fin shape grid, the behavior between grids should probably be consistent.

Build 967
[Windows 11 Pro; Version 21H2; OS Build 22000.739; Windows Feature Experience Pack 1000.22000.739.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
> That explains it! Also sorry for the absence, school started back up and it's taking me a bit to get back in the swing of things.

Don't worry, I know the feeling :) We appreciate your help, good luck at school!

**Comment by SiboVG** [comment]
@neilweinstock you wanted to test this PR out as well?

**Comment by neilweinstock** [comment]
I haven't gone through every tab on every component, but what I've tested is glorious, all works so much more logically than before.

**Pull request merged**
