### PR TITLE
[#1564] Add component information box

### LINKED ISSUE #1564: Feature request: Add rocket component information/help box
To help new users, an information/help box could be added to rocket components' configuration window that has two functions:

1. Help users understand what the different rocket components do (cf. the engine block text 'An engine block stops the motor from moving forwards in the motor mount tube.')
2. Help users understand ow OpenRocket "handles" those components or what extra steps need to be taken to use them (cf. the engine block text 'In order to add a motor, create a body tube or inner tube and mark it as a motor mount in the Motor tab.').

Since those information boxes are only useful for novice OpenRocket users, more experienced users should be able to hide the information boxes.

Proposal: information box on the bottom of the config panel, with a question mark icon that toggles the visibility of the information box.
image

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #1564 by adding component information boxes for each component, thanks to the good work done by @hcraigmiller by writing the component descriptions. I did make some alterations, so please re-read the statements to check if this rocket-noob did not mess anything up.

Demo of the functioning:

https://user-images.githubusercontent.com/11031519/210892972-3e169b45-0108-49b8-bbb9-3acec0ef7779.mp4

Here are all the info boxes:

<details>
<summary>----(Click me to unfold; I'm here to tidy this PR up)----</summary>

Screenshot 2023-01-05 at 23 19 03
Screenshot 2023-01-05 at 23 19 13
Screenshot 2023-01-05 at 23 19 18
Screenshot 2023-01-05 at 23 19 22
Screenshot 2023-01-05 at 23 19 26
Screenshot 2023-01-05 at 23 19 32
Screenshot 2023-01-05 at 23 19 36
Screenshot 2023-01-05 at 23 19 40
Screenshot 2023-01-05 at 23 19 45
Screenshot 2023-01-05 at 23 19 49
Screenshot 2023-01-05 at 23 19 53
Screenshot 2023-01-05 at 23 19 57
Screenshot 2023-01-05 at 23 20 02
Screenshot 2023-01-05 at 23 20 06
Screenshot 2023-01-05 at 23 20 10
Screenshot 2023-01-05 at 23 20 15
Screenshot 2023-01-05 at 23 20 19
Screenshot 2023-01-05 at 23 20 23
Screenshot 2023-01-05 at 23 20 28
Screenshot 2023-01-05 at 23 33 17
Screenshot 2023-01-05 at 23 33 28

</details>

### CODE REVIEW

**Comment by hcraigmiller** [comment]
Keeping your bolding, I would change the text to read:

Rail buttons keep the model rocket from changing orientation when it launches. Rail buttons are used on larger model rockets, in pairs, instead of launch lugs.

A launch lug is the most common guide used to keep smaller model rockets from changing orientation until the rocket leaves the end of the launch rod.

A coupler is a short tube that connects two tubes having the same diameter. In model rockets that use electronics, a coupler may be used for the avionics bay. The body tubes are often glued to the coupler to stop them from sliding.

An engine block stops the motor from moving forward in the motor mount tube. In order to add a motor, create a body tube or inner tube and mark it as a motor mount in the Motor tab.

The parachute is the most common recovery device. Small model rocket parachutes are made of thin, light-weight materials, such as polyethylene or Mylar, while larger parachutes are most commonly made of rip-stop nylon. Parachutes may be decorated in bright and contrasting colors/patterns. Shroud lines attach the parachute canopy to the shock cord. The shroud lines are sometimes brought together and attached using a swivel.

A streamer is a recovery device that, when ejected, unrolls and slows the model rocket during descent. A streamer is a long, narrow, rectangular strip of crepe paper or thin plastic film. The width and length of the streamer are adjusted to match the weight of the rocket, but 10 to 1 is considered the best length to width ratio for a streamer.

**Comment by SiboVG** [comment]
> A launch lug is the most common guide used to keep smaller model rockets from changing orientation until the rocket leaves the end of the launch rod.

This is the same as before, right?

All other changes have been made.

**Comment by hcraigmiller** [comment]
Yes, I was using it for language consistency and forgot to delete it.

**Comment by hcraigmiller** [comment]
This is a nice addition, especially for those new to rocketry. Functions as expected; no anomalies found.

Build 1401
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by JoePfeiffer** [comment]
Should we avoid mentioning gliders, since we don't simulate them?  Our most common use of a parallel stage is strap-on boosters.

**Comment by neilweinstock** [comment]
> Should we avoid mentioning gliders, since we don't simulate them? Our most common use of a parallel stage is strap-on boosters.

I agree with this.

**Comment by SiboVG** [comment]
Changed 'glider' to 'strap-on booster'.

**Pull request merged**
