### PR TITLE
[#1567] Implement rail button screw

### LINKED ISSUE #1567: Feature request: Extend configuration parameters for rail buttons to include exposed screws
Extend the current parameters to include exposed screws. The user would be able to set the screw height, but the diameter of the screw head would be OuterDiameter. There would be no need for the complexity of a drop down to implement this, just the ScrewHeight field.

Rail Button Component Rev_04

The screw head height is already a field within the rail button database (see PR #1540).

See discussion in PR #1538.

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #1567 and implements a rail button screw.

https://user-images.githubusercontent.com/11031519/206908350-c272c66b-a97c-4229-92e7-b0debfe0edf4.mp4

I also noticed that the height sliders in the rail button config panel were not scaled linearly and that the minimum and maximum value of the sliders did not adjust dynamically. This PR fixes that as well.

### CODE REVIEW

**Comment by neilweinstock** [comment]
Very nice.  Are the buttons and/or screws factored into aerodynamic calcs yet?  I can't remember.

**Comment by SiboVG** [comment]
> Very nice. Are the buttons and/or screws factored into aerodynamic calcs yet? I can't remember.

Nope, not yet. PR #766 started it, but it was never finished.

**Comment by neilweinstock** [comment]
In that case, since it looks like that will not get done for this release, I think we should have a warning in the config dialog to that effect.  Rail buttons are the only component in the "body components and finsets" group that are not factored in, and so users might not realize their special status.

**Comment by neilweinstock** [comment]
As a further thought on this, I think the ability to fine-tune the screw dimensions will even further lead folks to think that it will have an effect on aerodynamics, otherwise why bother?

Definitely should have a visible warning there.

**Comment by hcraigmiller** [comment]
Beautiful. Functions as expected, no anomalies found.

Build 1258
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
> In that case, since it looks like that will not get done for this release, I think we should have a warning in the config dialog to that effect. Rail buttons are the only component in the "body components and finsets" group that are not factored in, and so users might not realize their special status.

Filed as #1878.

**Pull request merged**
