### PR TITLE
Upgrade to Java 11/Java 13 and retire Android app

### PR DESCRIPTION
**Pull request by neilbalch**
Please let me know if I forgot to do something. I just opened the project up in Intellij, changed the project SDK to Java 11, and fixed errors until the project compiled and ran. (#347)

### CODE REVIEW

**Comment by wcravens** [comment]
I'd suggest that you build a Jar and somehow get it into the hands of some testers and let them try and run it on their systems.  From what I recall, there is certain 'black magic' that the IDEs (Intellij/Eclipse) can/will do to facilitate these running correctly but there is a good threat that they won't work when ran on other folk's systems.  That's when the fun really begins.

**Comment by neilbalch** [comment]
Alright, @wcravens. What'd the protocol be for getting that done? I have no contacts to reach out to for testing. Also, is there a special process for building a `.jar` executable?

**Comment by gallopinggoose6** [comment]
Did anyone write tests for this project?

**Comment by neilbalch** [comment]
Sorry, I don't understand... did anyone write tests for openrocket (_of course yes_) or my patch (_no_)?

**Comment by gallopinggoose6** [comment]
I mean code designed to run to make sure that the real code works. Basically we would have a little program or procedure that would feed a bunch of inputs into open rocket and see what happens. @neilbalch I'd be happy to run your jar on my system, I'd have to downgrade to JDK 11, but just send me a jar file and I can get to it this weekend.

**Comment by neilbalch** [comment]
For sure. Any preferred media to get the `.jar` to you, @gallopinggoose6 ?

**Comment by gallopinggoose6** [comment]
Just email it to me. Probably copy everyone so that everyone can test it as well.

**Comment by wcravens** [comment]
Tests yes.  Reliable coverage, no.

Wes

**Comment by neilbalch** [comment]
Here goes, @gallopinggoose6. I don't see a way to find your email address from your GitHub profile or commit history, so please accept [my humble Firefox Send](https://send.firefox.com/download/09ec0377806bdfdc/#Y6PAGT5Ehs3UU3JUVYH-jg). Please let me know how else I can help.

**Comment by neilbalch** [comment]
@gallopinggoose6 or use [this one compiled for jdk-13.0.1](https://send.firefox.com/download/6ddd093a1d648a40/#13aUQzMI6X9jxn6S6CXaUw). Same exact code, just compiled with a different JDK.

**Comment by gallopinggoose6** [comment]
Thanks @neilbalch I will take a look at that as soon as I can. I'll test the jdk 13 one on both Windows and Ubuntu. I'm not sure if there's much of a need to publish a jdk 11 one but I'll take a look at that one too, later.

**Comment by neilbalch** [comment]
Indeed, @gallopinggoose6. In truth, I didn't realize that I wasn't up to date and there was a JDK higher than 11.x.x 😬. I'm also of the opinion that we should distribute the `.jar` targeting JDKs 13.x.x.

**Comment by gallopinggoose6** [comment]
@neilbalch Status: I haven't had much time to play around with this, however from the little testing I've done the program appears to return valid numbers. I was able to test the program on a raspberry pi running raspbian with MATE, a Windows system, and an Ubuntu system. I found the fewest number of bugs running on an Ubuntu machine. On windows the program will sometimes crash, and on the Raspberry pi there are broken elements of the UI. @wcravens where is a list of tests that I can run in order to figure out exactly what doesn't work?

**Comment by neilbalch** [comment]
Hrm. Not sure how to debug those Windows crashes without more context...

**Comment by gallopinggoose6** [comment]
@neilbalch Hi! I'm so sorry I have been silent for so long. A lot of busy stuff is happening so far, but here is something you might find useful:
[hs_err_pid5836.log](https://github.com/openrocket/openrocket/files/4082236/hs_err_pid5836.log)
[hs_err_pid8060.log](https://github.com/openrocket/openrocket/files/4082237/hs_err_pid8060.log)

**Comment by neilbalch** [comment]
To be frank, @gallopinggoose6, I'm not sure how to interpret those... :(

**Comment by gallopinggoose6** [comment]
Well @neilbalch I don't really know how to interpret them either. I do want to see openrocket get updated, so do you want to work through this (I hope to be able to devote some more time to this soonish) I know that it happened while I was working inside of the generic quadrilateral fin editor - both times

**Comment by neilbalch** [comment]
No, I mean I _really_ don't know how to interpret those logs. I don't see any errors, exceptions, nothing. I have no idea how to process those logs, or take any meaningful action on their contents.

**Comment by gallopinggoose6** [comment]
I meant just working through the bug, finding some other way of fixing it, perhaps editing how log files work in order to make that happen. Can I find your source code in a forked repository?

**Comment by neilbalch** [comment]
image

Yes, you most certainly can: https://github.com/neilbalch/openrocket/tree/java11-upgrade

**Comment by LamentConfiguration** [comment]
I know I am kinda new here, but with the new release schedule for the jre/jdk, i'm not sure it would be worth the time chasing every version update, perhaps focusing on the current LTS (which is 11), would be the safest/best bet?

**Comment by neilbalch** [comment]
@LamentConfiguration That's a good point. Are the releases that different from one another? Moving up to JDK 11 would be a step in the right direction, although it doesn't solve the problem of reducing the number of Java versions I'd have to have on my computer at once.

**Comment by teyrana** [comment]
@neilbalch Hey, it's awesome to see your progress :)

Would love to help :)   If you post that .jar again, I can help with some debugging.

I also have your branch setup in Eclipse, but it looks like it's missing a few .jar dependencies... do you know if the new ones got added to the project?  The old ones were *really* old, and I'm sure needed to be updated....

@gallopinggoose6 @neilbalch 
Those `*_pid[0-9]{4}.log` files look like the JVM itself crashed?  That's kinda impressive, actually.  I've never seen those!

... However, I'm not sure that's a factor for our project, though.

**Comment by teyrana** [comment]
@gallopinggoose6 
Those sound like a different issue--but we still want to hear about those-- would you mind filing a separate issue?) 

Do you get a popup window with a bug report, and an option to send it to the mailing list? 
If so, the contents of that pop-up window would be the most useful info :)

**Comment by neilbalch** [comment]
Hi, @teyrana! Yeah, of course. Would you like [the one built for jdk-13.0.1](https://send.firefox.com/download/0fb133198bd138ab/#IDlgusg8VfbcoY2zxmlzVg)?

I've been building with IntelliJ Idea, fixing errors that came up until it built and ran successfully. Could you describe what you mean when you say that the project looks like it's missing .jar dependencies? When I open version of the code from my patch on my machine in IntelliJ, it still builds.

**Comment by LamentConfiguration** [comment]
I have no way of knowing how different things will be from 1 to the other, the *trend* seems to be to continue the "backwards compatibility" (sans the headaches going from 8->9+) that is java, while being able to iterate on a small number of features at a time in-between the LTS releases.

I'm guessing the repo doesn't include the dependency jars that intellij's build tool is pulling when building the project from the cloned repo. Perhaps there is a way to provide an "uberjar" that has the specific dependencies your intellij is using?

**Comment by LamentConfiguration** [comment]
also, if you go with a solution like amazon's coretto, or the azul free community jdk, or the openjdk projects, they offer LTS support of 11 for quite a long time, and this might help you limit the number of jdk/jre's you need to have? (I'm a tinkerer myself, and I couldn't see having more than 2 LTS versions (if they're both being supported), and 1 "cutting edge" version, but I know I'm only mildly deep into the world of java).

Soon we'll be able to easily build applications with a small version of the jvm built-in and hopefully avoid a lot of these issues!

**Comment by teyrana** [comment]
@neilbalch 
Ahhh, thanks! That's beautiful! This will make a bunch of people happy :)
It worked fine on my machine, all except the 3d views (couldn't find gluegen.dll or something.  Probably on my end.)

Not all of use use the same IDE, actually.  Eclipse has been the most popular, and a few of us have been trying Intellj.  I'll give that a try.  But when I opened your branch in Eclipse, I got 462 errors... (!!) So I won't *start* by listing them all :P 

With Intellij what's your build procedure?  Do you build through the IDE?  through ant / maven / etc on the command line?  And what's the path where you found the .jar? (Relative to $PROJECT_ROOT, anyway)

@LamentConfiguration 
Yea, we generally lag behind the JDK releases.  So I doubt we'll have enough time to actually track the latest release.  We'd like to at least stay out of EOL releases, though :/   It's mostly driven by how much trouble the community has in running the thing, though.

**Comment by neilbalch** [comment]
@teyrana The 3D views don't exactly work on my end either, I just presumed it comes down to how I specifically configured the build process in IntelliJ. Speaking of which, I just loaded the `openrocket` folder as a project, set the project JDK version to `jdk-13.0.1` and pressed the build button.

At least I think so, I set this up a couple of months ago at this point. The `.jar` was located at `$PROJECT_ROOT/build/jar/OpenRocket-13.0.1.jar`

**Comment by LamentConfiguration** [comment]
@neilbalch regarding 3dviews, there's a big flummox going on with the javafx toolkit being removed from core java and having to be loaded as a dependency now, that might have impact on the 3d views.

I'm gathering the "core" (non-feature) milestones might be to do the following:

1) build against the current LTS jdk (11) with all the javaFX "stuff" working properly.
2) move to a non-ide based build system (gradle or maven) (since most ide's will offer support for both through plugins), while I personally love intellij for my java/kotlin work, i don't like it much outside of that, so I can understand liking a different ide.

**Comment by LamentConfiguration** [comment]
The only problem I can see moving to jdk 11 would be some difficulties with an android-based codebase, since I'm pretty sure android is still "barely" adopting jdk9 stuff.

**Comment by neilbalch** [comment]
As you can probably tell, I'm not a very highly experienced Java programmer, (_I main C/C++ and Python_) so all of these antics are relatively new to me. 😃

**Comment by LamentConfiguration** [comment]
likewise, this project is actually part of the reason I'm getting back into Java some!

I'm a LISP-er at heart, I've become quite fond of kotlin for the JVM/android stuff though.

**Comment by teyrana** [comment]
Yea, I do a lot of Python & C++, too.  But you're doing a great job, so far :)

> @neilbalch regarding 3dviews, there's a big flummox going on with the javafx toolkit being 
> removed from core java and having to be loaded as a dependency now, that might have impact
> on the 3d views.

Eeeesh.  Ummm... Do you know what's going on with that? 

@LamentConfiguration 
Are you saying it'll be easier to fix the graphics under Java 11?

We definitely have some users who will complain about the missing 3d graphics, so that is a showstopper for the next release.  Let's fix that before we merge this into the main line.

> I'm gathering the "core" (non-feature) milestones might be to do the following:
>
> build against the current LTS jdk (11) with all the javaFX "stuff" working properly.
> move to a non-ide based build system (gradle or maven) (since most ide's will offer support for
> both through plugins), while I personally love intellij for my java/kotlin work, i don't like it much 
> outside of that, so I can understand liking a different ide.

Do you think it'd be dramatically easier to port to a gradle build system? 
I'd played with upgrading it, but hand't really gotten it work.  I'd be happy to use it, if someone ports it.

**Comment by LamentConfiguration** [comment]
I'm definitely not going to say "easier"

Easy would be sticking to java8 as a build target and noting that for the software, as all the graphics stuff of javaFX are still built-in to the 8 stuff, and there are still a few LTS versions of 8 out there getting updates for at least a couple more years.

But for any LTS going forward (11, etc.) it'll definitely be required to go to the module-based setup that the jvm has gone to. Java9 is where things started going modular.

Don't worry too much about quickly rising java version numbers, java now has a 6-month release cycle for feature releases, with every 6th release intended to be LTS (so 11, 17, 23), all the other releases are serving double purpose 1) test and refine new ideas before a LTS. 2) help make migrating more incremental for large codebases, even if they aren't using the new version in production.

I *think* there are automated ways in intellij to convert it to gradle. I'll play around with my local copy some in the next couple of days and report back.

**Comment by teyrana** [comment]
@lamentconfiguration

I like the gradle idea but that's probably a separate thread.

Right now, I'd love to hear ideas for the best way to add 3d features into this Java-13 branch... Even educated guesses :)

**Comment by LamentConfiguration** [comment]
3d features that *were* there or are new things?

if they were there it's just a matter of transitioning the project to include the modules that were broken out from the core (i know javafx was, swing is still in the core for 11 though).

if it is an external dependency on another library, it's just making sure there's an up-to-date version for that library, and rebuilding the project.

**Comment by teyrana** [comment]
Woah! No, no, no, Just the old features.  

I'd like to see it all ported, but at minimum, people will expect it to be substantially present.

I'm hoping we can just rebundle the relevant jars?  And that the relevant APIs haven't changed?

**Comment by LamentConfiguration** [comment]
yeah, if it's things that "worked before" it is just a matter of finding what modules they've been split off into and updating project/build files accordingly.

**Comment by LamentConfiguration** [comment]
another thing that has to be taken into consideration with the migration to 11+ is that android is still not there (the modular point) of 9+ yet, so it might be wise to fork it off as a separate repo going forward?

**Comment by teyrana** [comment]
@LamentConfiguration 

Yea, I think that's a good strategy.  There's just not a lot of usage around the Android Port, these days.

**Comment by teyrana** [comment]
@neilbalch 
Okay, I've installed Intellij, and took it for a test run.  Overall, it looks good :)

### Good news first: 
It runs without any modification against Java 11 & 13!  This is great! this is farther than anyone has gotten :) 


### Some bad news:  
1. The example rockets, available from 'File' > 'Open Example...' > aren't available....
The rocket files are still found at `swing/resources/datafiles/examples/`, so it's probably just a path-search thing.
2. There's also this little gem:  "DirectoryIterator.java:153 -- Error opening directory datafiles/presets"  Not sure what that's about, but it's

**Comment by teyrana** [comment]
(I mean, it's not too suprising.  There are so many changes, we're bound to get *some* bugs.)

**Comment by neilbalch** [comment]
Sorry for not clarifying; my reaction doesn't accurately convey what I wanted to say... I'd sure hope my patch builds with JDK 11/13, as that's what the title claims it to do. 😄 

The example rocket issue is intriguing... I'm not sure what kind of time I will have to look into it though. 

During what operation did you get that exception?

**Comment by teyrana** [comment]
Hey, I hope it works too.   But I still check ;)

Which exception? 
1.  Go through the menus I mention.
2. Nothing.  That's an error on startup.

**Comment by teyrana** [comment]
Oh, and I did have to make some minor changes to get your intellij build running: 
Basically, it's locating the JDK for Intellij.  I don't know of a good way around have the developer manually do that. 

Especially if people change from the Oracle JDK to OpenJDK, or vice versa.

```
c12e4054 (HEAD -> java11-upgrade) [fix] local JDK pathing fixes to make branch work on my machine
diff --git a/.idea/misc.xml b/.idea/misc.xml
index 6f34b5b6..0df80099 100644
--- a/.idea/misc.xml
+++ b/.idea/misc.xml
@@ -46,7 +46,7 @@
       </profile-state>
     </entry>
   </component>
-  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_7" default="false" project-jdk-name="11" project-jdk-type="JavaSDK">
+  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_7" default="false" project-jdk-name="Oracle JDK 11" project-jdk-type="JavaSDK">
     <output url="file://$PROJECT_DIR$/out" />
   </component>
 </project>
\ No newline at end of file
diff --git a/.idea/runConfigurations/Openrocket_UI_Jar.xml b/.idea/runConfigurations/Openrocket_UI_Jar.xml
index 633c0528..a701b0db 100644
--- a/.idea/runConfigurations/Openrocket_UI_Jar.xml
+++ b/.idea/runConfigurations/Openrocket_UI_Jar.xml
@@ -2,7 +2,7 @@
   <configuration default="false" name="Openrocket UI Jar" type="JarApplication">
     <option name="JAR_PATH" value="build/jar/OpenRocket.jar" />
     <option name="ALTERNATIVE_JRE_PATH_ENABLED" value="true" />
-    <option name="ALTERNATIVE_JRE_PATH" value="11" />
+    <option name="ALTERNATIVE_JRE_PATH" value="Oracle JDK 11" />
     <method v="2">
       <option name="BuildArtifacts" enabled="true">
         <artifact name="openrocket:jar" />
```

**Comment by neilbalch** [comment]
@teyrana Interesting... I don't get exceptions upon startup, and we're both using the same patch. Hrm.

Yeah, the JDK path is going to be have to be set by each developer. That an unfortunate aspect of Intelij.

**Comment by teyrana** [comment]
Not pop up windows- you have to open the debug log.  I'll screenshot it
when I'm in front of a computer again.

**Comment by teyrana** [comment]
- [ ] Example Rockets Issue:
```
(JarUtil.java:40)                        Found jar file using codeSource
(ExampleDesignFile.java:118)  Current jar file is: D:\project\openrocket\build\jar\OpenRocket.jar
(ExampleDesignFile.java:50)    Cannot find jar file, trying to load from directory
(ExampleDesignFile.java:80)    Loading example from null 
(ExampleDesignFile.java:87)    Directory to search is: datafiles\examples
```
So, it's trying to load files from *inside* the jar, and failing at that.  That's consistent with the other issues, and would also match an inability to load the component presets.   Also, we'll check that it can find the motors.

**Comment by teyrana** [comment]
Not pop up windows- you have to open the debug log.  

Here's the screenshot:

Capture

You can checkout the debug log by hitting the `ctrl+d` shortcut, or 'Help' menu => 'Debug log'.

**Comment by neilbalch** [comment]
Thanks for the context, @teyrana! I'll look into this when I get back in town. If you have any hunches though, please to try them out.

**Comment by LamentConfiguration** [comment]
I was giving a couple goes at getting clean builds and setting up gradle, but i'm running into some odd things as well.

I'm really not sure what the best option for a build system is as I'm not up to date outside of using intellij myself to be honest.

**Comment by teyrana** [comment]
@LamentConfiguration 

Oh, don't worry about it, then.   If you have a burning desire to switch the build system, that's one thing.... but honestly intellij works pretty well, for now, so I we don't have much complaints.

Would love to have more eyes on this, one, fwiw.

**Comment by teyrana** [comment]
@neilbalch 
Okay, good news: 

I was able to fix the 'example' rockets thing by classifying the 'swing/resources/` directory as a "resources root" in Intellij.   And the example rockets are now available :)

Let me know if you want me to throw a pull request over, to merge into your upstream branch.

**Comment by teyrana** [comment]
### So: Current status: 
- [X] Loading Example Rockets (fixed)
- [X] Loading Presets (fixed) 
- [ ] Enable 3d Views

**Comment by neilbalch** [comment]
@teyrana Awesome! The way I see it, you could push a commit to the pull request yourself (_I enabled edits from maintainers a while ago_), you could send me the diffs you applied to fix the presets and example rockets so I can commit them myself, or we could try what you suggested. I have no strong opinion either way.

**Comment by teyrana** [comment]
@neilbalch 
I've submitted the patches as a sub-PR to this one: primarily because if possible, I'd like to get another set of eyes on them, to make sure they work on at least one other person's computer :)

### Pull Request:
https://github.com/neilbalch/openrocket/pull/1

**Comment by LamentConfiguration** [comment]
Ok, well, with this seeming to go well so far? I'm going to go poke at something that actually "interests" me in languages (: the leaking memory/big memory use that was mentioned.

**Comment by teyrana** [comment]
@neilbalch 
I'm starting to look at the 3d views-- can you post the file-path / error that you see when you try to show 3d views?

Mine is `C:\Windows\System32\gluegen-rt.dll`.

**Comment by neilbalch** [comment]
Would this error be found in the Intellij console?

**Comment by neilbalch** [comment]
@teyrana 
image

> Unable to load 3d Libraries: Could not initialize class `javax.media.opengl.GLProfile`

Hasn't `javax` been depreciated somewhat by now? I might be remembering wrong...

**Comment by teyrana** [comment]
Oh.  Huh.  

a) I get a different error :P
b) Migrating to something else, (like Jogl,) is on the table, if we can get it working

**Comment by teyrana** [comment]
@neilbalch 
Fixed. Basically, Intellij was being opinionated again.
java11-3d

**Comment by teyrana** [comment]
@neilbalch 
Okay, I think this PR is ready.  Any objections to merging in?

**Comment by neilbalch** [comment]
I haven't gotten the chance to submit my final patch yet, so I'd prefer if we hold off for another hour. I'll @ you when I'm ready. Thanks for your help with this, man!

**Comment by neilbalch** [comment]
Huh. I still need to go through the process of re-adding the jogl libraries to Intelij when I clone the repository, but there are no diffs in Intellij's configs anymore... I think it's safe to say that we can merge this now, @teyrana, but we might want to investigate this for developer documentation.

**Comment by teyrana** [comment]
> I still need to go through the process of re-adding the jogl libraries to Intelij when I clone the repository, 

Oh, do you mean this in a bug-report way?  or a planning way?

**Comment by neilbalch** [comment]
No, like a note to future developers that they may very well need to go through the same steps I did to sort out Intelij's identity crisis. 😄 Other than that, ready to merge. 👍

**Pull request merged**
