### PR TITLE
Filter decal file chooser on images + don't show edit decal button if not possible

### PR DESCRIPTION
**Pull request by SiboVG**
As discussed in #1991, the decal file chooser dialog needed an option to filter on image files, which this PR implements.
Screenshot 2023-01-24 at 22 25 11

This PR also removes the edit decal button if image editing is not supported on the system:
image
(don't mind the dark UI, Ubuntu did that automatically because my Ubuntu theme is set to dark)

### CODE REVIEW

**Comment by neilweinstock** [comment]
What determines if "image editing is not supported on the system"?

**Comment by SiboVG** [comment]
> What determines if "image editing is not supported on the system"?

On some platforms, the Desktop API that OR uses to call the image editor is not supported. Don't know exactly which platforms, this is just an extra safety built-in. I think #1995 will fix the editor not working on Linux.

**Comment by neilweinstock** [comment]
Sounds good.

**Comment by JoePfeiffer** [comment]
I'm planning on leaving #1995 as a draft until this is merged; or if you'd prefer to incorporate it in this one go ahead.  I've asked @wolsen to see what #1995 does when in a snap.

**Comment by SiboVG** [comment]
> I'm planning on leaving #1995 as a draft until this is merged; or if you'd prefer to incorporate it in this one go ahead. I've asked @wolsen to see what #1995 does when in a snap.

We'll merge this first then.

**Pull request merged**
