### PR TITLE
Introduce material groups, document materials, and document preferences + Refactor material panel to use searchable and groupable combobox

### PR DESCRIPTION
**Pull request by SiboVG**
## Goal of this PR

This PR started out simple. I wanted to apply the searchable and groupable combobox introduced in #2413 for plot types to the component material combobox. However, in order for this to work, I had to introduce some new concepts to OR. Needless to say, a "one-evening PR" turned into a "several weeks" PR.

## TLDR

Component material selection is now much more organized:
image

## New concepts

1. Materials now have a `MaterialGroup`. It's purpose is to group and organize materials. The current list of material groups is:
- **Metals**
- **Woods**
- **Plastics**
- **Fabrics**
- **Paper Products**
- **Foams**
- **Composites**
- **Fibers**
- **Threads and Lines** _(this is basically just for line materials)_
- **Other** _(for unidentified groups)_
- **Custom** _(for user-defined materials - though a user can also choose to select one of the above material groups when creating a new user-defined material)_
2. There are now 2 types of materials:
- **Application materials**: These are materials that are available across all design documents. Prior to this PR, these were the materials that you could add and edit in the OR preferences.
- **Document materials**: These are materials that are available to all components **within the document**. A document material created in _document A_ cannot be accessed by _document B_. Prior to this PR, this was basically the same as the "Custom" material dropdown option in the material combobox, but with this PR, other components can also use that custom material + you are able to edit the document material in the preferences dialog (together with the application materials).
3. Document materials are saved in the .ork file as **Document Preferences**. This ensures that document materials that were created, but not yet assigned to any components will not be lost, since they will be saved in the doc prefs in the .ork. The component material will also still be saved in the rocket component XML object, so older versions of OR should have no issue reading document materials. I also partially introduced the document preferences because I want to use it in a future PR on another topic. I think it could be a useful concept.

Example XML excerpt of the `docprefs`:
```XML
  <simulations>
  </simulations>
  <photostudio>
  </photostudio>
  <docprefs>
    <docmaterials>
      <material>BULK|I'm a document material!|0.0|Custom</material>
      <material>BULK|Wow!|0.0|Custom</material>
    </docmaterials>
  </docprefs>
</openrocket>
```

## Other remarks about functionality

1. I was really annoyed by how unintuitive it is in OR to define custom materials - selecting "Custom" from the combobox list:
image

With this PR, there is now a clear button to add a new custom material, or edit the materials, which opens the "Materials" tab of the OR preferences:
Screenshot 2024-08-09 at 00 47 31

2. As seen in the screenshot above, there is also a button to "Edit materials". Clicking this button opens the `Materials` tab in the `Preferences` dialog. I have added 2 new columns in the Materials table: a `Group` column for the material groups, and a `Scope` column to indicate whether the material is an Application or a Document material.

image

3. Note that empty material groups are not displayed in the combobox.

4. User-defined materials get the prefix `(ud)` in the materials combobox. This is to easily distinguish them from the default materials.

image

## Demo

Of course, nothing beats a demo:

https://github.com/user-attachments/assets/88325438-f663-49bc-9953-c2d4f5255032

## Compatibility

Compatibility should be maintained both from older OR versions to this PR and vice versa *knock on wood*. There should also be no issues loading components from the parts library.

## Testing

This is quite a big PR, so thorough testing would be much appreciated. If you could also review my assignment of the default materials to material groups, that would be helpful. You can see the default materials here:

<details>
<summary>Click me to show the materials</summary>
BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Acrylic", 1190, MaterialGroup.PLASTICS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Aluminum", 2700, MaterialGroup.METALS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Balsa", 170, MaterialGroup.WOODS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Basswood", 500, MaterialGroup.WOODS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Birch", 670, MaterialGroup.WOODS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Brass", 8600, MaterialGroup.METALS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Cardboard", 680, MaterialGroup.PAPER));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Carbon fiber", 1780, MaterialGroup.COMPOSITES));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Cork", 240, MaterialGroup.WOODS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Delrin", 1420, MaterialGroup.PLASTICS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Depron (XPS)", 40, MaterialGroup.FOAMS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Fiberglass", 1850, MaterialGroup.COMPOSITES));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Kraft phenolic", 950, MaterialGroup.COMPOSITES));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Maple", 755, MaterialGroup.WOODS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Nylon", 1150, MaterialGroup.FIBERS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Paper (office)", 820, MaterialGroup.PAPER));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Pine", 530, MaterialGroup.WOODS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Plywood (birch)", 630, MaterialGroup.WOODS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Polycarbonate (Lexan)", 1200, MaterialGroup.PLASTICS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Polystyrene", 1050, MaterialGroup.FOAMS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "PVC", 1390, MaterialGroup.PLASTICS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Spruce", 450, MaterialGroup.WOODS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Steel", 7850, MaterialGroup.METALS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Styrofoam (generic EPS)", 20, MaterialGroup.FOAMS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Styrofoam \"Blue foam\" (XPS)", 32, MaterialGroup.FOAMS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Titanium", 4500, MaterialGroup.METALS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Quantum tubing", 1050, MaterialGroup.PLASTICS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "Blue tube", 1300, MaterialGroup.COMPOSITES));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "PLA - 100% infill", 1250, MaterialGroup.PLASTICS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "PETG - 100% infill", 1250, MaterialGroup.PLASTICS));
		BULK_MATERIAL.add(newMaterial(Material.Type.BULK, "ABS - 100% infill", 1050, MaterialGroup.PLASTICS));

		SURFACE_MATERIAL.add(newMaterial(Material.Type.SURFACE, "Ripstop nylon", 0.067, MaterialGroup.FABRICS));
		SURFACE_MATERIAL.add(newMaterial(Material.Type.SURFACE, "Mylar", 0.021, MaterialGroup.PLASTICS));
		SURFACE_MATERIAL.add(newMaterial(Material.Type.SURFACE, "Polyethylene (thin)", 0.015, MaterialGroup.PLASTICS));
		SURFACE_MATERIAL.add(newMaterial(Material.Type.SURFACE, "Polyethylene (heavy)", 0.040, MaterialGroup.PLASTICS));
		SURFACE_MATERIAL.add(newMaterial(Material.Type.SURFACE, "Silk", 0.060, MaterialGroup.FABRICS));
		SURFACE_MATERIAL.add(newMaterial(Material.Type.SURFACE, "Paper (office)", 0.080, MaterialGroup.PAPER));
		SURFACE_MATERIAL.add(newMaterial(Material.Type.SURFACE, "Cellophane", 0.018, MaterialGroup.PLASTICS));
		SURFACE_MATERIAL.add(newMaterial(Material.Type.SURFACE, "Cr\u00eape paper", 0.025, MaterialGroup.PAPER));
		
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Thread (heavy-duty)", 0.0003, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Elastic cord (round 2 mm, 1/16 in)", 0.0018, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Elastic cord (flat 6 mm, 1/4 in)", 0.0043, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Elastic cord (flat 12 mm, 1/2 in)", 0.008, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Elastic cord (flat 19 mm, 3/4 in)", 0.0012, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Elastic cord (flat 25 mm, 1 in)", 0.0016, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Braided nylon (2 mm, 1/16 in)", 0.001, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Braided nylon (3 mm, 1/8 in)", 0.0035, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Tubular nylon (11 mm, 7/16 in)", 0.013, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Tubular nylon (14 mm, 9/16 in)", 0.016, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Tubular nylon (25 mm, 1 in)", 0.029, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Kevlar thread 138  (0.4 mm, 1/64 in)", 0.00014808, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Kevlar thread 207  (0.5 mm, 1/64 in)", 0.00023622, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Kevlar thread 346  (0.7 mm, 1/32 in)", 0.00047243, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Kevlar thread 415  (0.8 mm, 1/32 in)", 0.00055117, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Kevlar thread 800 (1.1 mm, 3/64 in)", 0.00099211, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Kevlar 12-strand (3.2 mm, 1/8 in)", 0.00967306, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Kevlar 12-strand (4.8 mm, 3/16 in)", 0.01785797, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Kevlar 12-strand (6.4 mm, 1/4 in)", 0.02976328, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Kevlar 12-strand (7.9 mm, 5/16 in)", 0.04464491, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Kevlar 12-strand (10 mm, 3/8 in)", 0.05952655, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Kevlar 12-strand (11 mm, 7/16 in)", 0.07440819, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Kevlar 12-strand (13 mm, 1/2 in)", 0.11607678, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Kevlar 12-strand (14 mm, 9/16 in)", 0.20834293, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Kevlar 12-strand (16 mm, 5/8 in)", 0.28721562, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Kevlar 12-strand (19 mm, 3/4 in)", 0.3497185, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Kevlar 12-strand (25 mm, 1 in)", 0.45686629, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Nylon flat webbing md. (10 mm, 3/8 in)", 0.00951444, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Nylon flat webbing md. (13 mm, 1/2  in)", 0.01334208, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Nylon flat webbing md. (16 mm, 5/8 in)", 0.01618548, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Nylon flat webbing lg. (14 mm, 9/16 in)", 0.02723097, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Nylon flat webbing lg. (25 mm, 1 in)", 0.03969816, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Paraline small IIIA (6.4 mm, 1.4 in)", 0.00371829, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Elastic rubber band (flat 3.2 mm, 1/8 in)", 0.00297638, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Elastic rubber band (flat 6.4 mm, 1/4 in)", 0.00613107, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Elastic braided cord (flat 3.2 mm, 1/8 in)", 0.00106, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Elastic braided cord (flat 4 mm, 5/32 in)", 0.002, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Elastic braided cord (flat 6.4 mm, 1/4 in)", 0.00254, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Elastic braided cord (round 2 mm, 1/16 in)", 0.0035, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Elastic braided cord (round 2.5 mm, 3/32 in)", 0.0038, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Elastic braided cord (flat 10 mm, 3/8 in)", 0.00381, MaterialGroup.THREADS_LINES));
		LINE_MATERIAL.add(newMaterial(Material.Type.LINE, "Elastic braided cord (flat 13 mm, 1/2 in)", 0.00551172, MaterialGroup.THREADS_LINES));
</details>

### CODE REVIEW

**Comment by JoePfeiffer** [comment]
This looks really nice! I'm having an issue selecting a component under Linux, however. If I open the component selection dropdown and go to a material group it opens the submenu for the group, as one would expect. But then when I move my mouse to the right to try to select a specific material, it closes the submenu.  If this description isn't clear I'll try to get a video capture later today.

**Comment by SiboVG** [comment]
> This looks really nice! I'm having an issue selecting a component under Linux, however. If I open the component selection dropdown and go to a material group it opens the submenu for the group, as one would expect. But then when I move my mouse to the right to try to select a specific material, it closes the submenu. If this description isn't clear I'll try to get a video capture later today.

Ah, could be because of commit a27ab137cce9d17c29219c11032b775deef8a1bf, that was pushed in last-minute and I didn't test it properly afterwards, my mistake. I'll check it tonight.

**Comment by SiboVG** [comment]
Should be working now.

**Comment by neilweinstock** [comment]
This looks very nice.

I guess the fillet materials are completely separate from all this?

**Comment by SiboVG** [comment]
> I guess the fillet materials are completely separate from all this?

Good point! The back-end for it was already written, but I forgot to update the UI. All components (incl. fillets, parachutes...) should now have the correct material combobox.

**Comment by JoePfeiffer** [comment]
My prior problem has now been resolved. However, now when I open the component material selection dropdown and go to add a custom component, the Fiber material group submenu remains open. If I click on "Add custom material" I get the custom material dialog, but the material selection menu stays open, and submenus for the material groups open and close as I move the mouse up and down the material selection menu. The material selection menu finally closes when I click on something in the Custom material dialog.

**Comment by SiboVG** [comment]
> My prior problem has now been resolved. However, now when I open the component material selection dropdown and go to add a custom component, the Fiber material group submenu remains open. If I click on "Add custom material" I get the custom material dialog, but the material selection menu stays open, and submenus for the material groups open and close as I move the mouse up and down the material selection menu. The material selection menu finally closes when I click on something in the Custom material dialog.

Yes, I know, that's the issue that a27ab137cce9d17c29219c11032b775deef8a1bf was trying to fix. I haven't found a way to resolve it yet, it's something weird with Java Swing. So for now I just marked it as an inconvenience.

**Comment by JoePfeiffer** [comment]
> > My prior problem has now been resolved. However, now when I open the component material selection dropdown and go to add a custom component, the Fiber material group submenu remains open. If I click on "Add custom material" I get the custom material dialog, but the material selection menu stays open, and submenus for the material groups open and close as I move the mouse up and down the material selection menu. The material selection menu finally closes when I click on something in the Custom material dialog.
> 
> Yes, I know, that's the issue that [a27ab13](https://github.com/openrocket/openrocket/commit/a27ab137cce9d17c29219c11032b775deef8a1bf) was trying to fix. I haven't found a way to properly resolve it yet, it's something weird with Java Swing. So for now I just marked it as an inconvenience.

Ah, OK. I'm happy noting the inconvenience and merging it in. Any objections @jimmiedave @neilweinstock ?

**Comment by SiboVG** [comment]
Okay, I was able to fix the issue, so no more inconveniences :)

**Comment by JoePfeiffer** [comment]
I'm still seeing a little bit of an issue -- the submenu now closes, but the main material selection menu stays open and the custom material dialog opens behind it. I have to click on something in the custom material dialog to get the material selection menu to close.

If you want to take another shot at the menu handling go ahead; otherwise it's a minor enough annoyance on an important enough improvement that I've got no problem with seeing it merged.

**Comment by SiboVG** [comment]
> I'm still seeing a little bit of an issue -- the submenu now closes, but the main material selection menu stays open and the custom material dialog opens behind it. I have to click on something in the custom material dialog to get the material selection menu to close.

That's odd, I'm not seeing that on my machine... I'll try to recreate it on a Linux bootcamp.

**Comment by SiboVG** [comment]
Okay, I can recreate it on Linux. I'll push a fix for it in a minute.

**Comment by SiboVG** [comment]
Should be fixed now - thanks for testing @JoePfeiffer!

**Comment by JoePfeiffer** [comment]
Perfect!

**Comment by jimmiedave** [comment]
Late to the party, but this looks _really_ nice. Very much appreciated, as I struggle with the current state materials system when the weight of "fiberglass" somehow doesn't match what I'm getting from a manufacturer.

**Comment by JoePfeiffer** [comment]
There may be a regression in plotting sim results from this PR.  If I run openrocket_build_2207 (from PR #2528), sim plots behave normally.  if I run openrocket_build_2214 (from this PR), when I try to plot the result of a sim the "Edit simulation" dialog shows "Friction drag coefficient" for the X axis type and all Y axis types.

**Comment by SiboVG** [comment]
> There may be a regression in plotting sim results from this PR. If I run openrocket_build_2207 (from PR #2528), sim plots behave normally. if I run openrocket_build_2214 (from this PR), when I try to plot the result of a sim the "Edit simulation" dialog shows "Friction drag coefficient" for the X axis type and all Y axis types. @SiboVG

Will investigate.

**Comment by SiboVG** [comment]
Thanks for notifying me @JoePfeiffer! The issue is fixed now. Programming is hard :)

**Pull request merged**
