### PR TITLE
[#1490] Select recovery device/stage after config panel select

### LINKED ISSUE #1490: Feature request: select recovery device/stage in design view when selected in recovery/stage configuration tab
Currently, when you select a motor mount in the motors configuration tab, the motor mount is also selected in the design view. The same should also be done in the recovery tab and stages tab.

For example if you select something in the recovery tab, the corresponding recovery device gets selected:
image

Same for the stage selection (note: for this to work, #1489 first needs to be fixed):
image

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #1490 and selects the recovery device/stage in the design view corresponding to the selected recovery device/stage in the recovery/stage configuration table.

Demo:

https://user-images.githubusercontent.com/11031519/176032271-54db5047-31dd-43cf-aced-6637013454bd.mov

This PR also fixes o an issue with #1494 where selecting multiple stages had no effect on the design view.

### CODE REVIEW

**Comment by SiboVG** [comment]
Ouch, sorry, didn't encounter those issues, will push a fix soon.

**Comment by SiboVG** [comment]
> Select _Motors & Configuration_ and _Motors_ tab... upper stage still selected... left-click configuration to select motor... turn off any stage to error.

This is intentional, the motor mount is only selected when the motor table has gained focus. That ensures that the component selection does not always change when you switch to the 'Motors & Configuration' tab. So only an active click in the table triggers the component select, as it should be.

**Comment by SiboVG** [comment]
Does the final commit fix the issues @hcraigmiller?

**Comment by hcraigmiller** [comment]
Functions as described by @SiboVG above, no anomalies found.

Build 766

[Windows 11 Pro; Version 21H2; OS Build 22000.739; Windows Feature Experience Pack 1000.22000.739.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
> Functions as described by @SiboVG above, no anomalies found.

Phew. Thanks for catching the initial bugs!

**Pull request merged**
