### PR TITLE
Rename 'Remove' to 'Delete'

### PR DESCRIPTION
**Pull request by SiboVG**
OR has some parts which switch between the terms 'Remove' and 'Delete' to indicate the delete of something. This PR unifies those terms to 'delete'. The most noticeable changes are 'Remove Configuration' --> 'Delete Configuration' and 'Remove motor' --> 'Delete motor' in the motor configuration tab.

### CODE REVIEW

**Comment by hcraigmiller** [comment]
Functions as expected, no anomalies found. as to this issue. But I am getting an optimization error that does not appear in the current unstable. Is this a problem, or just an artifact of some type?

Build 910
[Windows 11 Pro; Version 21H2; OS Build 22000.739; Windows Feature Experience Pack 1000.22000.739.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
> But I am getting an optimization error that does not appear in the current unstable. Is this a problem, or just an artifact of some type?

Could you elaborate? What is the optimization error?

**Comment by hcraigmiller** [comment]
Open three-stage rocket example. Select Tools -> Rocket optimization, and this results:

Optimization Error

**Comment by SiboVG** [comment]
> Open three-stage rocket example. Select Tools -> Rocket optimization, and this results:
> 
> Optimization Error

Wow, good catch. IntelliJ's refactoring system failed to rename that instance because the translation object splits up its keys there. Fixed in the latest commit.

**Comment by hcraigmiller** [comment]
Functions as expected, no anomalies found.

Build 912
[Windows 11 Pro; Version 21H2; OS Build 22000.739; Windows Feature Experience Pack 1000.22000.739.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Pull request merged**
