### PR TITLE
[#1600] Calculate auto tab for all inner tubes

### LINKED ISSUE #1600: [Improvement] Auto fin tab height calculation for all inner tubes
Currently, the auto fin tab height only functions correctly if the inner tube is also a motor mount tube. If the inner tube is not a motor mount tube, the auto fin height function makes the fin tab height the distance from the outside of the component to the internal centerline of the component.

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #1600.

### CODE REVIEW

**Comment by hcraigmiller** [comment]
Nested inner tubes result in error. The fin tab height attaches to the smallest diameter tube, rather than the first tube that the fin tab comes in contact with (delete the nested inner tube and the height calculates correctly). The next error is in the current unstable and PR # 1598 as well. The nested centering rings causes the fin tab length to be too short (delete the nested centering rings and the tab length calculates correctly). 

See the following:

Fin Tab Auto

[Inner Tube.txt](https://github.com/openrocket/openrocket/files/9378377/Inner.Tube.txt)
[Inner Tube.Nested.txt](https://github.com/openrocket/openrocket/files/9378379/Inner.Tube.Nested.txt)

**Comment by SiboVG** [comment]
> Should this be an instructional issue for the Wiki, or a code change?

The calculate auto tab code was just really janky. I rewrote the whole thing and it now alway looks for the biggest radius CenterRing or InnerTube, no matter where they are located in the component tree. The tab length is set the same length as the max radius component. If there are multiple components with equal maximum size, e.g. 2 centering rings, the fin tab will span both ring lengths and the distance between the two rings.

**Comment by hcraigmiller** [comment]
The fin tab auto calculate is making the fin tab length the distance between the outside (not inside) of the cetering rings, and the height is from the outer diameter to the inner diameter of the component the fins are attached to (not to the outer diameter of the inner tube).

Fin Tab Auto n02

**Comment by SiboVG** [comment]
> The fin tab auto calculate is making the fin tab length the distance between the outside (not inside) of the cetering rings, and the height is from the outer diameter to the inner diameter of the component the fins are attached to (not to the outer diameter of the inner tube).

Ah, I wasn't aware it was supposed to work like this...

**Comment by hcraigmiller** [comment]
It's not. . . 

Fin Tab Auto n03 02

[Tab Height.Short.txt](https://github.com/openrocket/openrocket/files/9383364/Tab.Height.Short.txt)

**Comment by SiboVG** [comment]
> Like this. . .

Yes, I was aware of how it's supposed to work after your prior post, my apologies.

**Comment by SiboVG** [comment]
Okay, latest commit should have everything up and running.

**Comment by hcraigmiller** [comment]
**Functions as expected, no anomalies found.** Works great.

FYI: Issue #1107 is an extension of this work.

Build 926
[Windows 11 Pro; Version 21H2; OS Build 22000.739; Windows Feature Experience Pack 1000.22000.739.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by hcraigmiller** [comment]
Should this PR be working with nose cones, body tubes, and transitions? Currently works with body tubes and transitions that have an aft diameter that is equal to or less than the fore diameter.

**Comment by SiboVG** [comment]
> Is this PR intended to be working with nose cones, body tubes, and transitions? Currently works only with body tubes and transitions that have an aft diameter that is equal to the fore diameter.

This PR isn't supposed to solve that, but there is a bug that the tab height is limited when the fore diameter is smaller than the aft diameter. If the fore diameter is zero, you cannot increase the tab height; it's locked to 0. I would file this as a new issue.

**Comment by hcraigmiller** [comment]
> This PR isn't supposed to solve that, but there is a bug that the tab height is limited when the fore diameter is smaller than the aft diameter. If the fore diameter is zero, you cannot increase the tab height; it's locked to 0. I would file this as a new issue.

Issue #1603 created.

Functions as described, no anomalies found.

Build 926
[Windows 11 Pro; Version 21H2; OS Build 22000.739; Windows Feature Experience Pack 1000.22000.739.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Pull request merged**
