### PR TITLE
[#2076] Support transparent rendering and exporting of PS images

### LINKED ISSUE #2076: [Feature Request] Transparent background in photo studio
I've got a request from someone doing video for Spaceport America Cup to use our scripting interface to generate an animation of a rotating rocket.  The one part of it that I don't think OR does currently is he wants a solid or (ideally) transparent background from our photo studio.  That "ottabee" possible...

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #2076 and adds support for transparent background rendering and exporting in PhotoStudio. A fully transparent color is just rendered as white.

Demo:

https://user-images.githubusercontent.com/11031519/228622619-3fb321ed-1a68-4e24-b1af-ac520e3b8783.mp4

### CODE REVIEW

**Comment by neilweinstock** [comment]
Should we have an "Opacity" slider in the settings panel, like we do for Appearance?

**Comment by SiboVG** [comment]
> Should we have an "Opacity" slider in the settings panel, like we do for Appearance?

Probably a good idea, yes, I'll include that in this PR.

Something unrelated: but I'm not too happy with the workflow that you first have to select "None" in the sky image combo and only then can use a sky color. I think something like a radio button to switch between "color" and "image" would make more sense. Thoughts on this @neilweinstock?

**Comment by SiboVG** [comment]
> > Should we have an "Opacity" slider in the settings panel, like we do for Appearance?
> 
> Are you suggesting an "Opacity" slider in Photo Studio on the Environment tab? If so, thumbs up.

Yes, I'd say below the sky color item.

**Comment by neilweinstock** [comment]
> > Are you suggesting an "Opacity" slider in Photo Studio on the Environment tab? If so, thumbs up.
> 
> Yes, I'd say below the sky color item.

Yes, should like just like the appearance tab, minus the "Shine" parameter.
image

>Something unrelated: but I'm not too happy with the workflow that you first have to select "None" in the sky image combo and only then can use a sky color. I think something like a radio button to switch between "color" and "image" would make more sense. Thoughts on this @neilweinstock?

Hmmmmmm.  I agree that the current implementation could be better.  Not sure if radio buttons are the right way to go (might be, but not yet sure).  Let me think on it for a few minutes.

**Comment by SiboVG** [comment]
Opacity slider added:
https://user-images.githubusercontent.com/11031519/228690212-a43e634d-dd0f-435c-b454-05ed8c182074.mov

**Comment by hcraigmiller** [comment]
Opacity/transparency inoperative.

Transparency

**Comment by SiboVG** [comment]
> Opacity/transparency inoperative.
> 
> Transparency
> 
> OR Build: 1679 Microsoft Windows 11 Pro; 10.0.22621 Build 22621.1105; Windows Feature Experience Pack 1000.22638.1000.0 Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)

That's very odd, works perfectly for me... In your first comment you mentioned that this PR worked as expected, so it stopped working after the slider was added?

**Comment by hcraigmiller** [comment]
> In your first comment you mentioned that this PR worked as expected, so it stopped working after the slider was added?

Yes.

**Comment by hcraigmiller** [comment]
Still not working.

OR Build: 1680
Microsoft Windows 11 Pro; 10.0.22621 Build 22621.1105; Windows Feature Experience Pack 1000.22638.1000.0 Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)

**Comment by SiboVG** [comment]
Are your saved PhotoStudio images also opaque? And does it not work over the full 0-100% range, or only at those extremes? And do you have "use off-screen rendering" enabled/disabled?

**Comment by hcraigmiller** [comment]
Okay, I found the issue. I switched computers and one had the "off-screen rendering" on and the other off.  Apparently, this feature, on my dvices, required off-screen rendering.

With that caveat, functions as expected, no anomalous behavior found.

OR Build: 1680
Microsoft Windows 11 Pro; 10.0.22621 Build 22621.1105; Windows Feature Experience Pack 1000.22638.1000.0
Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)

**Comment by SiboVG** [comment]
Okay, I just implemented "artificial transparency rendering"® when a system does not have off-screen rendering enabled. Since changing the opacity slider basically blends the sky color with a white background (= how transparent background is rendered), I just check whether off-screen rendering is enabled or not. If it isn't, I blend the background color with a white color, depending on the opacity value.

So, there is no need for a Wiki explanation, and this feature should work for all users now. Saving the image with transparency also works for both cases.

Demo (first with off-screen rendering enabled, then with off-screen rendering disabled):

https://user-images.githubusercontent.com/11031519/228822725-aacdf3c9-1a7e-44cb-9afb-08f0fa4cf1e6.mp4

**Comment by hcraigmiller** [comment]
With off-screen rendering _enabled_ and sky color active, **checking** the flame or smoke effect strips color/decals from rocket. Once stripped, Photo Studio must be closed and reopened to correct. If one (or both) is checked when opened, the color/decals will be stripped

With off-screen rendering _disabled_ and sky color active, **checking then unchecking** the flame or smoke effect (the initial check does not trigger error), or checking both, strips color/decals from rocket. Once stripped, Photo Studios must be closed and reopened to correct. If one (or both) is checked when opened, unchecking one has the same effect.

**Comment by hcraigmiller** [comment]
> Is this a result of this PR or is it present in 22.02?

Ah. . . yes. Regrettably it is. Good for this PR, bad for me.

With that caveat, it appears to be functioning as expected.

OR Build: 1690
Microsoft Windows 11 Pro; 10.0.22621 Build 22621.1105; Windows Feature Experience Pack 1000.22638.1000.0 Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)

**Pull request merged**
