### PR TITLE
Adjust ClassLoader in JarInJarStarter for Java9+; Fix macOS setup

### PR DESCRIPTION
**Pull request by itshanney**
@teyrana fix to adjust the ClassLoader in JarInJarStarter as suggested by Billy Olsen.

### CODE REVIEW

**Comment by teyrana** [comment]
| JDK    | Variant     | OS       | Result
|:-------|:-----------|:--------|:-----------------------
|   8      | oracle jdk | WIN10 | `RuntimeException: Error starting Openrocket`
| 11      | oracle jdk | WIN10 | `RuntimeException: Error starting Openrocket`
| 13      | oracle jdk | WIN10 | `RuntimeException: Error starting Openrocket`
|   8      | openjdk   | WIN10 | `RuntimeException: Error starting Openrocket`
| 11      | openjdk   | WIN10 | `RuntimeException: Error starting Openrocket`
| 13      | openjdk   | WIN10 | `RuntimeException: Error starting Openrocket`

**Comment by itshanney** [comment]
@teyrana  added the changes to get macOS working.

**Comment by itshanney** [comment]
@teyrana  how do you generate that table that hows the results? Is there a way for me to do that locally? You will need to drop Java 8.  Once we go to Java 9+, 8 is off the list because backwards incompatibilities in the API.

**Comment by teyrana** [comment]
@itshanney 

> You will need to drop Java 8. Once we go to Java 9+, 8 is off the list because backwards incompatibilities in the API.

Um, would you mind expanding on that? What feature are we using that isn't available in java 8?

p.s. The table isn't generated, it's just some formatting you can do in markdown / comments

**Comment by teyrana** [comment]
OpenJDK 11 Result:
====
```
$ echo $JAVA_HOME
C:\Program Files\Java\openjdk-11.0.6.10-hotspot

$ java --add-modules=java.scripting -Dopenrocket.debug -jar swing/build/jar/OpenRocket.jar
java.lang.RuntimeException: Error starting OpenRocket
        at net.sf.openrocket.startup.jij.JarInJarStarter.runMain(JarInJarStarter.java:40)
        at net.sf.openrocket.startup.OpenRocket.main(OpenRocket.java:36)
Caused by: java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.sf.openrocket.startup.jij.JarInJarStarter.runMain(JarInJarStarter.java:38)
        ... 1 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
        at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
        at net.sf.openrocket.startup.SwingStartup.main(SwingStartup.java:76)
        ... 6 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/jogamp/opengl/GLEventListener
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:642)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:600)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at net.sf.openrocket.gui.main.BasicFrame.<init>(BasicFrame.java:222)
        at net.sf.openrocket.gui.main.BasicFrame.newAction(BasicFrame.java:1571)
        at net.sf.openrocket.startup.SwingStartup.runInEDT(SwingStartup.java:175)
        at net.sf.openrocket.startup.SwingStartup.access$000(SwingStartup.java:43)
        at net.sf.openrocket.startup.SwingStartup$1.run(SwingStartup.java:79)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.jogamp.opengl.GLEventListener
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 27 common frames omitted

```

**Comment by itshanney** [comment]
@teyrana take a look at this final edit. I adjusted the swing/build.xml file to include all the necessary JARs from the lib folder. Everything is starting up as expected with the following command.

java --add-modules java.scripting -Dopenrocket.debug -jar swing/build/jar/OpenRocket.jar 

The change here is that I included all the dependencies for the swing module where they get expanded into the .jar file, like all the other dependencies. I believe this is the solution that somebody came up with in the past to create an "uber jar" that has everything and can be run as one file. I just added the swing/lib/*.jar files to the list as well and all works now.

Regarding openjdk8 and removing it, this is because we need to pick a new "baseline JDK" and that is the lowest common build target.  Right now, we're attempting to align on Java 11 as our lowest baseline, so anything below that should be removed. When we distribute the new OpenRocket.jar file we say it requires Java 11+ or we bundle Java 11+ with it. 

The main concern here is backwards incompatibility. If we're aligning on Java 11 and some developer starts using new features from Java 11, then we wouldn't even be able to compile for Java 8.

**Comment by teyrana** [comment]
okay, that is _weird_ . . .  Those jars (lines 118-130) should already have been added by line 133.  In fact, it *does* in other branches.  Do you know what's going one here?   I have confirmed loading by directory works, in PR #581, so its extra odd that it breaks here.  (Presumably it has something to do with changing the ClassLoader, but that still doesn't indicate what the issue is.)

Furthermore, the `--add-modules java.scripting` flag does not seem to have an effect.  What are we expecting to change?  Does it change anything on your machine?

p.s. Minor nitpick: `swing/build.xml` now has quite a few duplicate tags (109-112  and 113-117).

**Comment by teyrana** [comment]
My impression was that centering we're just troubleshooting on Java11, not necessarily making official support decisions. 

If you wish to make a case for removing java 8, let's be more open about it.   I think people will be receptive.

**Comment by itshanney** [comment]
For Java 8 vs Java 11, it's not going to work without going to Java 11. In Java 9+ they fundamentally moved around and changed packages so they're backwards incompatible. For example, looking at OSXSetup.java, JEP 272 (http://openjdk.java.net/jeps/272) removed the macOS specific libraries and now uses java.awt.desktop.*.  java.awt.desktop.* doesn't exist in Java 8 (https://docs.oracle.com/javase/8/docs/api/) so the code will never compile against a Java 8 compiler.

I see what you mean by the jars be included in the OpenRocket.jar file. Let me investigate some more and I'll submit another commit.

**Pull request closed without merging**
