### PR TITLE
Correct "polished" surface roughness value 

### PR DESCRIPTION
**Pull request by hcraigmiller**
Change incorrect value for polished surface roughness from 2 to .5 microns per Thesis and Hoerner Fluid Dynamics.

01 01 02 Thesis Roughness

### CODE REVIEW

**Comment by SiboVG** [comment]
Hm, there's still some compatibility issues. If a user has a design saved with the old finished and polished surface value and opens that design in OR 22.02 (with the adjusted value), then the simulation results will change because suddenly you drop from 0.5 microns to 0.02 microns.

I really admire your efforts on fixing the surface roughnesses in OR @hcraigmiller, but IMO this is something we should fix after the final release, because it's really easy to break compatibility and change users' simulations unwantedly.

**Comment by neilweinstock** [comment]
I agree with @SiboVG.  This is a good thing to clean up, but needs to be done carefully and it is not urgent to squeeze into this release.

**Comment by hcraigmiller** [comment]
Just trying not to have future designs perpetuate a known error.

**Comment by hcraigmiller** [comment]
Closed, see PR #1875.

**Pull request closed without merging**
