### PR TITLE
Alpha8 - Bugfix Collection

### PR DESCRIPTION
**Pull request by teyrana**
Contains fixes for #424, #425, #419, #431, #426, #439, #436, #425, #419, #426, and other code cleanup.

### CODE REVIEW

**Comment by JoePfeiffer** [comment]
Looks like it fixes 424 and 425; fixes 436, but should the figure also be centered horizontally?  I don't use the freeform fin editor so I can't really comment on the others.  The comment on 
4cb8a03 says it resolves #423, but describes 423 as the Barrowman bug.  I don't think that ever got formally added as an issue, did it?  Too much to try to review all the code changes.

**Comment by teyrana** [comment]
Hmmm, fair point.  I can split them up, if you prefer.

**Comment by JoePfeiffer** [comment]
At the moment I think it's more productive to just observe whether the changes address the bugs, and see if new ones crop up.

**Comment by teyrana** [comment]
Yup. Good eyes. I've removed #423 from the to-review list.  That commit probably should not have a 'fixes' tag, at all.

**Pull request merged**
