### PR TITLE
Upgrade jogl libraries to 2.4.0-rc-20200306

### PR DESCRIPTION
**Pull request by wolsen**
Update the jogl libraries to 2.4.0-rc-20200306

Signed-off-by: Billy Olsen <billy.olsen@gmail.com>

### CODE REVIEW

**Comment by wolsen** [comment]
Test build is available at https://www.dropbox.com/s/aq1zbgf9vhonjnv/OpenRocket-fix-600-updated-jogl.jar?dl=0

**Comment by itshanney** [comment]
@wolsen pulled down and tried locally - works. NSWindow exception is gone. Ship it. 

CC: @teyrana

**Comment by teyrana** [comment]
Yup looks good -- pulled down, and built with Intellij + Win10

Because this those libraries involve hardware / system calls, can you guys add what build system OS you tested?

**Comment by itshanney** [comment]
Tested on macOS Catalina 10.15.2 using late 2019 MacBook Pro hardware.

**Comment by wolsen** [comment]
Test on Ubuntu 20.04 (dev release) using Dell Inspiron 7378, i7-7500u

**Comment by teyrana** [comment]
Okay, that's the big 3. I'm comfortable merging.

**Pull request merged**
