### PR TITLE
Updated small icons for most components

### PR DESCRIPTION
**Pull request by neilweinstock**
Just small clean-up to make the icons sharper, cleaner, and/or better shaped.  These are all pixel-edited images, not sized down from the large GIMP source files.

Comparison shots to come.

The large rail button icon is still in the works, I'll do that in a separate PR.

### CODE REVIEW

**Comment by neilweinstock** [comment]
image
image

**Comment by SiboVG** [comment]
Looks great! 💪

**Comment by hcraigmiller** [comment]
Overall, it is looking very good. My only two comments is that the bulkhead looks like two bulkheads (not one) and, from the mass component, I would remove the Kg or replace it with a M. 

The first I think needs to be adjusted, the second is just an observational comment.

Build 844
[Windows 11 Pro; Version 21H2; OS Build 22000.739; Windows Feature Experience Pack 1000.22000.739.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
> I would remove the Kg or replace it with a M.

I would just remove the text all together; changing it to 'M' is not analogous to how the large 'add Mass Component' icon is.

**Comment by neilweinstock** [comment]
I’ll make the changes next week.
________________________________

**Comment by SiboVG** [comment]
My attempt at incorporating the comments on the mass component and bulkhead. I also increased the darkness of the inner tube's center tube, because it was hard to distinguish the 2 tube shapes at such a small scale (as a musician, the previous version reminded me a lot of a music sheet staff, with the 4 equidistance lines).

preview

**Comment by neilweinstock** [comment]
That all looks fine to me.

**Comment by hcraigmiller** [comment]
I prefer v2. But, I also prefer the thin (before) bulkhead instead of the thicker (v2) bulkhead, and, a shorter tube fin (same diameter but shorter tube proportionally). Everything does look really nice, either way.

**Comment by hcraigmiller** [comment]
Functions as expected, no anomalies found.

Build 875
[Windows 11 Pro; Version 21H2; OS Build 22000.739; Windows Feature Experience Pack 1000.22000.739.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
> I prefer v2. But, I also prefer the thin (before) bulkhead instead of the thicker (v2) bulkhead (small only), and, a shorter tube fin (same diameter but shorter tube proportionally (small and large), compared to other fin icons). Overall, everything does look really nice, either way.

Hm, yeah I see what you mean. How's this? Bulkhead now resembles the original icon, but a bit more sharp.

oi

**Comment by neilweinstock** [comment]
Still looks good to me

**Comment by hcraigmiller** [comment]
Looks good to me too.
Functions as expected, no anomalies found.

Build 879
[Windows 11 Pro; Version 21H2; OS Build 22000.739; Windows Feature Experience Pack 1000.22000.739.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Pull request merged**
