### PR TITLE
Improve progress bar reporting

### LINKED ISSUE #1728: [Bug] Uncaught exception when adding/running new simulation
With run outdated simulations on:

1. Open .ork
2. Run simulation with existing configuration.
3. Add second configutation (same one); runs very slow.
4. Go to flight simulations tab.
5. Add third configutation (same one)
4. Go to flight simulations tab (uncaught exception).

Crash
[Bug Report.txt](https://github.com/openrocket/openrocket/files/9742769/Bug.Report.txt)
[Sea Killer.ork.txt](https://github.com/openrocket/openrocket/files/9742770/Sea.Killer.ork.txt)

[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

### PR DESCRIPTION
**Pull request by JoePfeiffer**
The progress bar dialog was trying to keep track of simulation apogee in two places; in one of them the "apogee" was actually one simulation status update after apogee.  Combined with the bug fixed in PR #1749, this could lead to a reported apogee of 0, causing the exception reported in #1728.  This PR removes the redundant apogee calculation.

Fixes #1728

The SimulationRunDialog sitll needs significant cleanup, but I'd like to just get this bug fix in now and save that for a later PR.

### CODE REVIEW

**Comment by hcraigmiller** [comment]
Functions with no anomalies found. However, after adding a second (or more) identical configuration, every one but the original runs very slowly. Even deleting all of the configurations and creating just one new one runs very slowly.

Build 1109
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by JoePfeiffer** [comment]
> Functions with no anomalies found. However, after adding a second (or more) identical configuration, every one but the original runs very slowly. Even deleting all of the configurations and creating just one new one runs very slowly.
 
Is that with the same "Sea Killer" ork file you attached to issue #1728?  The super slow sims (along with the actual exception) should have been fixed by PR #1749, which I believe is incorporated in this...

**Comment by hcraigmiller** [comment]
Yes. Same file, same process.

**Comment by JoePfeiffer** [comment]
Getting back to this -- please verify again.  I'm not able to duplicate the slow sims now.
Please export the flight data from one of the super-slow sims as a .csv.  The problem with running slow that turned up on the way to the exception before was that the adaptive time step could get arbitrarily small, so the time steps right after recovery device deployment were really tiny (this is what was addressed in PR #1749).  I'm not seeing them do this now.

**Comment by hcraigmiller** [comment]
I switched to a different computer and the issue went away. It looks like it's time to get a new notebook.

Functions as expected, no anomalies found. 

Build 1120
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Pull request merged**
