### PR TITLE
[#2456] Overhaul of sim table GUI

### LINKED ISSUE #2456: [Feature Request] Part 1 of Sim Tab overhaul
- [ ] Replace red and green dots in leftmost column with either a checkmark (sim is up to date) or a "reload" icon (sim needs refreshing).  Clicking the Reload icon should run the sim.
- [ ] Add new second column tentatively titled "Results" (name subject to change).  This column shows the number of warnings encountered, or else a checkmark (also subject to change) if there are none.
- [ ] Move simulation settings into a new leftmost tab in the Plot/Export dialog, to be renamed "Sim Details" or somesuch.  Adjust buttons on top to match.
- [ ] Display the tooltip with all warnings when hovering anywhere on the associated row in the table.

Further details provided below.

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #2456. Changes summarized:
1. Warnings now have a priority level: HIGH (critical), NORMAL (normal warning) and LOW (informative warning - currently not used, but implemented in case we may need it in the future)
2. Warnings have a dedicated column in the simulation table
3. The sim table status column icons have changed from a checkmark for up-to-date sims, a refresh arrow icon for outdated sims, and a red hexagon for simulations with no motors
4. The simulation settings, plot and export panels are combined in one simulation config dialog
5. The sim config dialog also contains a "Warnings" tab, displaying all the warnings for that sim
6. Clicking the "Sim outdated" icon in the sim table status column reruns the selected simulation
7. Double-clicking the cell in the sim table warnings column opens the warnings tab of the selected simulation
8. The warnings, plot, and export tab are disabled for multi-sim editing. We may want to hide them instead (especially because the disabled state is not distinguisable from the normal state on macOS in light mode).

I kept the separate edit simulation and plot/export simulation buttons above the sim table; I think it's still useful to have this separated access. I did remove the "Plot >>" and "<< Edit" buttons in the sim edit dialog and sim plot/export dialog (since users should now use the tabbed pane to switch from one view to the other).

image
image

image
image

image
image

https://github.com/openrocket/openrocket/assets/11031519/6cac8f0c-c4c0-412c-ae9d-dea9bf66a59b

https://github.com/openrocket/openrocket/assets/11031519/2137ece8-2492-48ec-a409-502386e68d53

Probably still room for improvement, so I'm open to suggestions.

### CODE REVIEW

**Comment by neilweinstock** [comment]
This is an excellent start.  A few initial comments:
1) I think the icons could use improvement.  I'll work on that.
2) In the "Warnings" tab, if there is a category with 0 warnings, just omit it (e.g. don't say "0 Critical Warnings").
3) There are some XML character references showing up in the warnings tab
4) I'm not sure we really need the separate "Edit Sim" and "Plot/Export" buttons, since they bring you to the same dialog.  I would favor condensing them into one.
5) I would center the "Warnings" column data

**Comment by neilweinstock** [comment]
> Playing with it for a couple of minutes, if there are warnings then the Plot/Export (and maybe the Edit Simulations?) button should come up with the warnings display. It actually seems a little odd to have two buttons bringing up the same dialog, but open to different tabs. A single button that opens to the edit tab if the sim isn't up to date, or either the plot or the warnings tab depending on whether there are any warnings for sims that are up to date?

I vote for just one button: "Sim Details", or another name if we don't like that one.  Personally I prefer not to have buttons changing names or anything.  Always open to "Warnings".  Although I'd probably prefer to change the name of the "Warnings" tab to "Messages".

> I'd suggest another textarea should be for simulation aborts; the stop sign icon would also make more sense for that than for critical warnings (but then I don't know what to use for critical vs normal warnings). Or maybe some sort of explosion icon for aborts?

An example of a critical warning is "Tumbling under thrust".  See the spreadsheet for examples: https://docs.google.com/spreadsheets/d/1yfpcBPWksnH0gIZftQGK9pdxlO1jneulchLwy8Q6O0A/edit?usp=sharing

After thinking for a minute I agree that it makes sense to separate out simulation aborts into their own category, but will need to think about how to distinguish.

In the software I use at work every day, they have "Info", "Warnings", "Critical Warnings", and "Errors" (where "Errors" are equivalent to our sim aborts, that is things that stop the process from running).  These are all displayed in a "Messages" tab:
image

I don't have any examples handy that show Errors; they're in red.  In this example you can see that regular and critical warnings are only distinguished visually by the color of the circle (yellow vs.  darker yellow/orange.)  If we're going to have a separate category for sim aborts, then they should get the stop sign, and we'll have to figure out what to do for the others.

**Comment by SiboVG** [comment]
> In the software I use at work every day, they have "Info", "Warnings", "Critical Warnings", and "Errors" (where "Errors" are equivalent to our sim aborts, that is things that stop the process from running). These are all displayed in a "Messages" tab:
> image

Ah, Vivado, long live you and your (non-critical) warnings that every developer ignores.

**Comment by neilweinstock** [comment]
> Ah, Vivado, long live you and your (non-critical) warnings that every developer ignores.

Don't get me started.  (ノಠ益ಠ)ノ彡┻━┻

**Comment by SiboVG** [comment]
I get that it's not all too pretty to have the plot button open the plot data tab, but I'm not sure whether it's desirable to only have one "Simulation details" button, because:
1. A 2-click action ("Plot simulation" > "Plot") now becomes a 3-click action ("Simulation Details" > "Plot data tab" > "Plot")
2. Don't overestimate users; a lot of them will probably not even notice that there are multiple tabs in the sim config dialog.

Plotting simulations is just such an important action in OR that I don't want it to be "hidden" in a dialog tab.

Anyway, I'm a bit spent on this PR for the moment, so if you can come up with concrete design improvements, I'd be happy to implement them, but I'll be holding off on the discussions for the time being. 🙂

**Comment by JoePfeiffer** [comment]
> I vote for just one button: "Sim Details", or another name if we don't like that one. Personally I prefer not to have buttons changing names or anything. Always open to "Warnings". Although I'd probably prefer to change the name of the "Warnings" tab to "Messages".

I agree on not having the button name change, I meant it just changes what tab it opens.  I don't really like "Sim Details", but I don't have any better ideas.  I really like changing "Warnings" to "Messages".

> An example of a critical warning is "Tumbling under thrust". See the spreadsheet for examples: https://docs.google.com/spreadsheets/d/1yfpcBPWksnH0gIZftQGK9pdxlO1jneulchLwy8Q6O0A/edit?usp=sharing

Not any more!  As of #2457 tumble under thrust is an abort.

**Comment by JoePfeiffer** [comment]
> I get that it's not all too pretty to have the plot button open the plot data tab, but I'm not sure whether it's desirable to only have one "Simulation details" button, because:
> 
>     1. A 2-click action ("Plot simulation" > "Plot") now becomes a 3-click action ("Simulation Details" > "Plot data tab" > "Plot")

My suggestion is if the button opens to the "plot" tab when the sim is up to date and there are no messages, it opens straight to the plot tab. It stays a two click sequence.

>     2. Don't overestimate users; a lot of them will probably not even notice that there are multiple tabs in the sim config dialog.

Sadly, you are correct.  There's every chance they'll never notice Edit and Plot/Export open to the same dialog.
> 
> Plotting simulations is just such an important action in OR that I don't want it to be "hidden" in a dialog tab.
> 
> Anyway, I'm a bit spent on this PR for the moment, so if you can come up with concrete design improvements, I'd be happy to implement them, but I'll be holding off on the discussions for the time being. 🙂

It's a pretty huge piece of work!

**Comment by neilweinstock** [comment]
> Not any more! As of #2457 tumble under thrust is an abort.

Feel like going to that spreadsheet and changing any line items to "abort", if appropriate?  I just changed "Tumbling under thrust".  For some reason my custom formatting is not working on that, so it's just gray; if anyone can figure out what's going on there I'd appreciate it.

**Comment by neilweinstock** [comment]
> > I get that it's not all too pretty to have the plot button open the plot data tab, but I'm not sure whether it's desirable to only have one "Simulation details" button, because:
> > ```
> > 1. A 2-click action ("Plot simulation" > "Plot") now becomes a 3-click action ("Simulation Details" > "Plot data tab" > "Plot")
> > ```
> 
> My suggestion is if the button opens to the "plot" tab when the sim is up to date and there are no messages, it opens straight to the plot tab. It stays a two click sequence.
> 
> > ```
> > 2. Don't overestimate users; a lot of them will probably not even notice that there are multiple tabs in the sim config dialog.
> > ```
> 
> Sadly, you are correct. There's every chance they'll never notice Edit and Plot/Export open to the same dialog.

I can accept that.

**Comment by JoePfeiffer** [comment]
This has languished long enough. It's a huge improvement; let's use it for a while and see what concrete changes we want.

**Pull request merged**
