### PR TITLE
Create messages_ar.properties

### PR DESCRIPTION
**Pull request by MedKebsi**

### CODE REVIEW

**Comment by SiboVG** [comment]
Okay, **please** just add new commits to PR #1899 instead of creating new PRs. Creating new PRs for every little change makes the GitHub workflow really unorganized.

**Comment by MedKebsi** [comment]
sorry but i dont know how to add new commit

**Comment by SiboVG** [comment]
> sorry but i dont know how to add new commit

How did you create Pull Requests? Did you just edit files on GitHub.com, or did you use a git command line tool, or any other git or version control tool?

**Comment by MedKebsi** [comment]
on GitHub.com

**Comment by SiboVG** [comment]
> on GitHub.com

Ah, okay. Well I'll add the commits to PR #1899 for you then. I won't bother you with trying to learn the git system on such short notice 🙃.

**Comment by MedKebsi** [comment]
ok thank you 
im sorry

**Comment by SiboVG** [comment]
> ok thank you im sorry

No problem! It's not your fault that GitHub is not beginner-friendly.

**Comment by MedKebsi** [comment]
yeh thank you

**Pull request closed without merging**
