### PR TITLE
[fixes #1125] Fix nose cone config layout

### LINKED ISSUE #1125: [Bug] Nose cone/transition configuration dialogs are so large as to extend beyond the screen edge.
Nose cone

[Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]

### PR DESCRIPTION
**Pull request by SiboVG**
Don't know when this slipped in, but the nose cone config dialog was really wide because of the description box:
Screenshot 2022-02-12 at 17 33 20

New behavior:
Screenshot 2022-02-12 at 17 33 41

The description box doesn't grow when resizing the window, but that's a problem for future-me.

Here is a [jar file](https://drive.google.com/file/d/1QohGXF0YFytJIdWdrpjSnsnPDJaRa2_g/view?usp=sharing) for testing.

### CODE REVIEW

**Comment by hcraigmiller** [comment]
The problem with nose cones has been resolved, but the window is still oversized for transitions.
[Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]

**Comment by SiboVG** [comment]
Sorry, wasn't aware the transition had the same issue, should be fixed in [this jar](https://drive.google.com/file/d/1QohGXF0YFytJIdWdrpjSnsnPDJaRa2_g/view?usp=sharing).

**Comment by SiboVG** [comment]
Right, got the issue, in one of Joe's previous commits, a line for setting the DescriptionArea dimension got lost 🙃

Here is a [jar file](https://drive.google.com/file/d/1SYlgmgA2vheeyDhJJQj1Vrh7VRJ9eRZP/view?usp=sharing) for testing.

**Comment by hcraigmiller** [comment]
I went through all of the windows and found one additional window that is off the screen: _OpenRocket debug log_.

Debug

[Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]

**Comment by JoePfeiffer** [comment]
Oops....

**Pull request merged**
