### PR TITLE
[#1227] Fix fin root edge display in 3D view and fin template

### LINKED ISSUE #1227: When exporting templates, draw fin roots correctly for fins-on-nose cones and fins-on-transitions
As reported by @MadRocketer on TRF: https://www.rocketryforum.com/threads/announcement-openrocket-version-22-02-public-beta-is-underway-download-it-now.171295/post-2250080

When a fin is placed on a transition or nose cone, the exported template still shows a straight edge.
image
Exports like this:
image

Obviously it would be preferable for the exported template to show the correct root edge contour.

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #1227. The root edge of a fin set now correctly outlines a transition's shape both in the 3D view and in the fin template export. Besides the fins, the fin tabs also weren't drawn correctly (neither in the 2D view, nor in the 3D view - the fin tab root edge was always just a straight line). This PR solves that issue as well.

Demo (with a transparent transition):

https://user-images.githubusercontent.com/11031519/185255413-d52b3dcc-c1fa-4c30-9025-a2d433d4c4f4.mp4

Fin template export also works with fin tabs:
Screenshot 2022-08-18 at 00 27 28

### CODE REVIEW

**Comment by neilweinstock** [comment]
LOL, that was quick, gonna need to come up with something more challenging for you. ;)

If I may nitpick: in the last screenshot there, you can see the line segments in the curved root line.  Is it possible to use smaller steps so it looks smoother?

**Comment by hcraigmiller** [comment]
The height of the fin tab does not auto calculate correctly.

1. Create transition with inner tube and centering rings.
2. Add freeform fin (default).
3. On _Fin tabs_ tab, left-click _Calculate autimatically_.

Results in fin tab height to centerline of transition.

**Comment by SiboVG** [comment]
> If I may nitpick: in the last screenshot there, you can see the line segments in the curved root line. Is it possible to use smaller steps so it looks smoother?

Done, export now looks like this:
image

**Comment by SiboVG** [comment]
> The height of the fin tab does not auto calculate correctly.
> 
> 1. Create transition with inner tube and centering rings.
> 2. Add freeform fin (default).
> 3. On _Fin tabs_ tab, left-click _Calculate autimatically_.
> 
> Results is fin tab height that goes to centerline of transition.

That's not a result of this PR, so there should be a new issue created for it. Also a side note: if the transition's fore diameter is smaller than the aft diameter, the calculations is done correctly. It's only when the aft diameter is smaller than the fore diameter that the tab height is calculated incorrectly.

**Comment by hcraigmiller** [comment]
Actually, the cause was user error on my part. . . I failed to check the inner tube "motor tube" checkbox.

**Functions as expected, no anomalies found.**

Build 918
[Windows 11 Pro; Version 21H2; OS Build 22000.739; Windows Feature Experience Pack 1000.22000.739.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Pull request merged**
