### PR TITLE
[fixes #1067] Improve GitHub repository

### LINKED ISSUE #1067: Improve GitHub repository
The OR-repo is very basic. This can weaken people's attention for and interest in (developing) OpenRocket. To quote from GitHub's '[Community management and operation](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/about-community-management-and-moderation)'-page: 

> "GitHub offers tools that help repository maintainers establish and enforce standards of behavior in their communities on GitHub.com."

We should start using these tools to ease OR's development and interest.

What I would like is first of all go through the README-file, check if additions are needed (maybe add a screenshot of the OR homepage of 'A simple model rocket' in the beginning to have a visual to attract new visitors to). Additionally, GitHub has some other useful files that you improve the repo:

1. [CODE_OF_CONDUCT](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project): this is just a sign of maturity for the repository, instead of being in the Wild West without clearly defined rules.
2. [CONTRIBUTING](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors): this is a **very** important file IMO. It will include all the necessary information to create a clear issue report, a good pull request etc. Especially for people inexperienced with open-source development or development in GitHub, this will be a game changer.
3. [LICENSE](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository): just generally good practice to include under which OpenRocket operates.
4. [SUPPORT](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-support-resources-to-your-project): this file will ease the way for OR-users or -developers to ask for help. We could link the Slack-server here, the OR-forum etc.
5. [CITATION](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files): this would be helpful for people using OpenRocket in research and would want to cite OpenRocket (I know people can just quote Sampo's thesis, but anyway, would be nice to add the citation directly to the repo).

Lastly, to make our lives more easy, we can also create [issue and pull request templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). This enforces structured issue reports and pull request, which sounds like heaven for any developer.

I suggest to put all the files I just mentioned in the '.github'-directory of the repo to keep our business clean.

I am going to put this as a beta-blocker for the simple reason that once we release the beta, we will hopefully attract some new people to the repo. Preparing the repo for them could spark new devs and testers to get involved + it will keep new issue report that will come from the beta clean.

I know, documentation, *barf*, but the OR-repo is in need for some modernization...

### PR DESCRIPTION
**Pull request by SiboVG**
This PR adds some files that help improve the GitHub repository:

- README: updated the information in this file (some wrong links etc., added all the contributors) + added a screenshot of OR to grab some attention
- CONTRIBUTING: contains information for someone who's new to open-source development in general and how to get started as a tester, developer, translator for OR...
- SUPPORT: information about our documentation and communication channels
- LICENSE: nothing fancy, just our license
- CITATION: from what I found, this is the most common format for citing a GitHub repo 
- CODE_OF_CONDUCT: just a standard text that I copied, not that special really

I also took the liberty of adding myself as a contributor in the About-dialog.

Some parts may be incomplete, but I feel like this is a good start for a modernized repo.

### CODE REVIEW

**Comment by JoePfeiffer** [comment]
A concern with the License file:  does this have a problem since we have at least one library and one font under different licenses, and of course the parts database is a submodule of our repository, also under a different license?

**Comment by SiboVG** [comment]
Hm well first of all, strangely the files did not seem to work when they were inside the .github directory... so I moved them to root in the latest commit. And you can also review the changes on [my brach](https://github.com/SiboVG/openrocket/tree/issue-1067). You can check there that the citation is correct on the top right. The other files are just plain read-work, but only CONTRIBUTING.md and SUPPORT.md would need a quick skim.

**Comment by JoePfeiffer** [comment]
In the code of conduct -- who should we identify as our community leaders, and what should the contact method be?  

On another note, I'm awfully happy that we're introducing a code of conduct now when I don't think I've ever seen anything happen that calls for it, rather than cleaning up after a mess (and I was Chair of the NMSU Faculty Senate for a year.  Oh God, the stuff we discovered was a problem after the fact...).

**Comment by SiboVG** [comment]
Whoops, I have to be honest, the code of conduct was really a standard file that I didn't care to much about and just copied from somewhere (referencing details are on the bottom, so don't worry about any licensing issues 😉). I even missed the part where you had to fill in the contact method.

I guess using the admins as community leaders would be appropriate? Maybe we can make a new mailing list for this?

**Comment by JoePfeiffer** [comment]
Our community is small enough I think everyone accepted into the organization is a community leader (tempting as it is to limit it to admins, so I wouldn't see it...).  Now getting into stuff I haven't had to research before... an anonymizing email server that could scrub the identity of someone posting to it, but which would allow a reply?

I don't want to get bogged down in this.  Maybe suggest a private slack message to someone other than whoever they've got a beef with?

**Comment by SiboVG** [comment]
Yeah we're starting to overthink it, for the size that we're at now. I'll just add that they can send the community leaders a mail, message on Slack or anything else (whatever the term 'community leader' may be)

**Pull request merged**
