### PR TITLE
messages_ar.properties

### PR DESCRIPTION
**Pull request by MedKebsi**
this file is the translation in arabic for open rocket

### CODE REVIEW

**Comment by SiboVG** [comment]
Awesome, thanks! See my comments in #1900 to put the translation to the locales list.

If you want, you can also add your name in `openrocket/swing/src/net/sf/openrocket/gui/dialogs/AboutDialog.java` after line 58, and in `openrocket/README.md` after line 71.

**Comment by MedKebsi** [comment]
sorry but i dont know how to add new commit

**Comment by SiboVG** [comment]
Your changes have been merged, thanks again for your contribution!!

**Comment by JoePfeiffer** [comment]
Yes, thank you and welcome aboard!

**Pull request merged**
