### PR TITLE
Update icons for stages, pods, and boosters

### PR DESCRIPTION
**Pull request by wolsen**
The icons for stages, pods and boosters do not match the theme of the
rest of the component icons and are larger in size. This change includes
and updated set of icons for these assembly components.

Co-Authored-By: Billy Olsen <Billy.olsen@gmail.com>

### CODE REVIEW

**Comment by neilweinstock** [comment]
Note the icons are also made smaller, to allow all the component buttons to be smaller.

**Comment by wolsen** [comment]
Updated icons shown here

Screenshot from 2021-08-09 18-58-42

**Comment by wolsen** [comment]
Worked in collaboration with @neilweinstock on this one and have have reviewed and critiqued the work as Neil progressed. While I'm listed as a co-author, I am merely doing the git-fu and placing the images in the proper location. Merging.

**Comment by SiboVG** [comment]
Very clean, thanks @neilweinstock @wolsen!

**Pull request merged**
