### PR TITLE
[#1680] Update flight config stagemap according to unique stage ID

### LINKED ISSUE #1680: [Bug] Changing stage order in component tree does "not" change activeness of stages
If one of the stages in your multi-stage design is inactive, and if you then move the order of any of the stages, then the activeness of the stages is not changed accordingly.

E.g. in a 'Three-stage rocket', take the following steps:
1. Rename the last stage to "Booster stage 2" just for clarity
2. Disable "Booster stage 2"
3. Move "Booster stage 2" in the component tree so that it's after "Sustainer" and before "Booster stage"
4. Instead of "Booster stage 2" still being inactive, and "Booster stage" being active, the roles are now reversed. "Booster stage 2" suddenly becomes active and "Booster stage" inactive (you can see this both in the stage selector buttons and in the rocket design view). The **correct behavior** should be that "Booster stage 2" remains inactive, and "Booster stage" active, regardless of how they are moved in the design.

If you look at the activeness of the stage selector buttons, you can see that nothing changes; the last stage selector button is still inactive and the first and second one are still active.

Demo:

https://user-images.githubusercontent.com/11031519/191020090-1d532037-0c7f-438a-899b-f1ca89c010e5.mp4

Issue already present in beta 4.

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #1680. Stages are now given a unique ID, just like flight configurations are assigned a unique ID (it's the same ID generation code). That unique ID is then used to identify stages when updating the stageMap in the flight configurations.

### CODE REVIEW

**Comment by hcraigmiller** [comment]
Functions as expected, no anomalies found.

One observation. . . the active stages appear more muted than the inactive stages. Is this the desired behavior?

Stages

Build 1039
[Windows 11 Pro; Version 21H2; OS Build 22000.739; Windows Feature Experience Pack 1000.22000.739.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
> One observation. . . the active stages appear more muted than the inactive stages. Is this the desired behavior?

I guess that's just how your Windows systems renders toggled and untoggled buttons, should not have anything to do with this PR.

**Comment by SiboVG** [comment]
Whoops, I just now noticed that a RocketComponent (so also a stage) already has a unique ID generator. Will do a refactor of my code...

**Comment by SiboVG** [comment]
Fixed now. While writing unit tests I also found an issue in `updateStageNumbers()` in `Rocket.java` where the stage number of substages (boosters) did not update correctly - which the unit test in `ParallelStageTest.java` conveniently masked. The power of using unit tests is proven once again :)

**Comment by hcraigmiller** [comment]
Functions as expected, no anomalies found.

Build 1048
[Windows 11 Pro; Version 21H2; OS Build 22000.739; Windows Feature Experience Pack 1000.22000.739.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Pull request merged**
