### PR TITLE
[fix][i10n] Adjusts Labels for add-component buttons: Stage, Booster, Pods

### PR DESCRIPTION
**Pull request by teyrana**
- Partially Addresses #643:
- Changes the button text on the (add new) Stage, Booster, and Pod Buttons.
- Adjusts internationalization strings to have more consistent naming with the other button strings
-  removed unused tooltip strings

text-fix

### CODE REVIEW

**Comment by wolsen** [comment]
LGTM, will wait for #659 to land first

**Comment by teyrana** [comment]
@JoePfeiffer 
@wolsen 
Updated with feedback:
text-fix-2

**Comment by wolsen** [comment]
+1 from me. I know @JoePfeiffer preferred "Mass Objects" but I think the term "Components" is good here as it provides consistent nomenclature.

**Comment by JoePfeiffer** [comment]
My preference was for consistency of singular/plural.  "Mass Components" is better than "Mass Objects".  LGTM

**Pull request merged**
