### PR TITLE
[#2131] Throw warning message when save filename contains illegal characters

### LINKED ISSUE #2131: [Improvement] Throw warning when users tries to save filename with illegal character
**Describe the bug**
When saving a design file (as of yesterday), the file will no longer save as a .ork, only as a .tmp, the file still works, but it doesn't save the name, so finding the file to rename it is a problem. 

**To Reproduce**
No one else seems to be having this issue, but I am using a flash-drive (but also have been for the past year+) with plenty of storage. But it occurs no matter how I try to save it.

**Expected behavior**
The file to save as a normal .ork file, not whatever 73047023984792374274.tmp is

**Screenshots**
image
image

**ORK File**
If the problem is triggered by a particular ORK file, please zip it and attach it to this issue.

**Platform**
 - OS: [e.g. Windows10] windows 10
 - OpenRocket version (e.g. 22-02) (22-02)
 - Graphics card (if a graphics or display-related problem)

**Additional context**

### PR DESCRIPTION
**Pull request by SiboVG**
This PR fixes #2131 and opens a warning message when you try to save a file with illegal characters (/ \ ? * " : < > |). This is valid for any file saving action in OR (design file save dialog, sim export dialog...).

https://user-images.githubusercontent.com/11031519/227068556-46c3ad80-4b97-4923-be32-8a8225f86e3e.mov

### CODE REVIEW

**Comment by SiboVG** [comment]
Does it work now @hcraigmiller?

**Comment by SiboVG** [comment]
> ? * (no action/stays on dialog)

Just noticed that this is normal. The ' ? ' and ' * ' characters are used to change the file type in the save dialog.

**Comment by SiboVG** [comment]
Just found another bug, I'll mark the PR as ready when I fixed that.

**Comment by hcraigmiller** [comment]
Functions as expected, no anomalous behavior found.

OR Build: 1656
Microsoft Windows 11 Pro; 10.0.22621 Build 22621.1105; Windows Feature Experience Pack 1000.22638.1000.0
Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)

**Pull request merged**
