### PR TITLE
Clamp beta factor (compressibility correction) in transonic region + apply it in supersonic region

### PR DESCRIPTION
**Pull request by SiboVG**
This PR is related to #2543. It clamps the Prandtl-Glauert compressibility correction factor (beta) to 0.6 in the transonic region, between Mach 0.8 and 1.1, as described in "Active Guidance and Dynamic Flight Mechanics for Model Rockets", David Ketchledge (1993). This avoids beta reaching infinity when it nears Mach 1. Additionally, I also applied the compressibility correction in the supersonic region for fins, as described in literature.

### CODE REVIEW

**Comment by SiboVG** [comment]
Note: as far as I can tell, this has little to no effect on the simulations, but it's the correct way to use compressibility correction.

**Comment by JoePfeiffer** [comment]
Every source I'm finding (other than Ketchledge) says it's only usable at speeds up to about Mach 0.7; see, for instance, _Fundamentals of Aerodynamics_ by Anderson (6th ed, 2017), p. 774, "... it is purely a subsonic theory and begins to give inappropriate results at values of M = 0.7 and above".

There are a bunch of places describing the Prandtl-Glauert singularity as causing vapor cones at Mach 1, but the more careful sources (even wikipedia!) say there's a big pressure effect there (but not like Prandtl-Glauert), but wave their hands about just what it actually looks like.

So if we incorporate it at all we need to only use it at speeds below Mach 0.7 where its impact will be much less than the variation between motors, and then we still have the question of what the right thing to do is in the transonic and supersonic regions.  At that point it seems better to just not use it, particularly since it doesn't seem to make any real difference to our results.

**Comment by SiboVG** [comment]
> Every source I'm finding (other than Ketchledge) says it's only usable at speeds up to about Mach 0.7; see, for instance, _Fundamentals of Aerodynamics_ by Anderson (6th ed, 2017), p. 774, "... it is purely a subsonic theory and begins to give inappropriate results at values of M = 0.7 and above".
> 
> There are a bunch of places describing the Prandtl-Glauert singularity as causing vapor cones at Mach 1, but the more careful sources (even wikipedia!) say there's a big pressure effect there (but not like Prandtl-Glauert), but wave their hands about just what it actually looks like.
> 
> So if we incorporate it at all we need to only use it at speeds below Mach 0.7 where its impact will be much less than the variation between motors, and then we still have the question of what the right thing to do is in the transonic and supersonic regions. At that point it seems better to just not use it, particularly since it doesn't seem to make any real difference to our results.

I could have sworn that I saw more references using the Prandtl correction at supersonic flow, but looking deeper into it, I think you're right.

I have removed the correction for supersonic flow, and have put a clamping when mach is between 0.99999 and 1.00001, to avoid the singularity.

I'm just gonna name-drop the Kármán-Tsien and Laitone's correction. They are similar to Prandtl-Glauert, but more accurate. I don't think it will make a big difference though, so it may not be worth the extra calculations.

**Comment by JoePfeiffer** [comment]
> I could have sworn that I saw more references using the Prandtl correction at supersonic flow, but looking deeper into it, I think you're right.

Maybe we saw the same thing? If I didn't, I can't imagine why I would have put in the correction in the first place.

> I have removed the correction for supersonic flow, and have put a clamping when mach is between 0.99999 and 1.00001, to avoid the singularity.

It would be simpler to just decide the clamping value, and use MathUtil.max(CLAMP_VALUE, MathUtil.safeSqrt(1 - mach*mach))

> I'm just gonna name-drop the Kármán-Tsien and Laitone's correction. They are similar to Prandtl-Glauert, but more accurate. I don't think it will make a big difference though, so it may not be worth the extra calculations.

Since Prandtl-Glauert doesn't seem to appreciably improve our accuracy, I don't really see that we need it.  We certainly don't need either of the others! (they actually both appear in the text I mentioned above -- it's amusing that the author carefully derives Prandtl-Glauert, and then just drops the other two without any derivation).

**Comment by SiboVG** [comment]
> It would be simpler to just decide the clamping value, and use MathUtil.max(CLAMP_VALUE, MathUtil.safeSqrt(1 - mach*mach))

Fair enough! I'll adjust it tonight.

> Since Prandtl-Glauert doesn't seem to appreciably improve our accuracy, I don't really see that we need it. We certainly don't need either of the others! (they actually both appear in the text I mentioned above -- it's amusing that the author carefully derives Prandtl-Glauert, and then just drops the other two without any derivation).

Yes, I also like this passage from Hoerner's "Fluid-Dynamic Drag":

> A number of attempts have been made (2,c) of improving the rule by introducing second-order terms. One effect thus taken into ac¬ count simply concerns the difference between (CpC01Yl /Cp;nc) and (AV/V)com/(AV/V);nc. It is be¬ lieved, however, that the second-order term in the pressure coefficient as a function of the thickness ratio (t/c) is usually cancelled by progressive boundary layer losses. Another correctly suggested modifica¬ tion, is to replace in equation 5 the ambient Mach number by the somewhat increased local Mach num¬ ber at the surface of the solid considered. All modifi¬ cations proposed tend to make the compressibility factor larger when approaching the critical Mach number, particularly in higher thickness ratios. Inas¬ much as the increment is but small (for typical air¬ foil sections) and since certain increases in pressure and lift coefficients can also be explained on different levels (4), the author proposes that it usually does not pay, in engineering applications, to complicate the original rule by introducing higher order terms.

**Comment by SiboVG** [comment]
I clamped it to an arbitrary beta value of 0.25.

**Pull request merged**
