### PR TITLE
adds documentation to aerodynmics package 

### PR DESCRIPTION
**Pull request by Vicilu**
and some refactoring of the files

### CODE REVIEW

**Comment by Vicilu** [comment]
btw, I've notice the AbstractChangeSource class source keeps converting EventListener and checking every time in the fire event method if it's instance of StateChangeListener while the implemented methods only allows StateChangeListener to be added in the array, why is that? even if you extend, you can't add this other types

**Comment by Vicilu** [comment]
if you want a more general, you can use a more general interface with accepting EventListeners with an array of List<? exenteds EventListener> while an extended class will change it?

**Comment by kruland2607** [comment]
Can you describe the bug fixed in ecb467?

**Comment by Vicilu** [comment]
it was my own bug, my bad at c9dadc1, and got fixed in it

**Pull request merged**
