### PR TITLE
Upgrade to guice-4.1 and guice-multibindings-4.1

### PR DESCRIPTION
**Pull request by tibbe**
This also requires adding guava, which is no longer shipped with guice.

This allows us to use Java8 and eventually Java9. Java9 is required for HiDPI support on new monitors.

Tested on Ubuntu 14.04.

### CODE REVIEW

**Comment by tibbe** [comment]
If we still need JDK 1.6 we can use guava-20.0 instead. Preferences?

**Comment by tibbe** [comment]
With this change I've managed to run openrocket on JDK-9 (from inside Eclipse) and have HiDPI work. All the buttons, text, etc. is the right size!

**Comment by ChrisMickelson** [comment]
Could you create a pull request that's based on the unstable branch? That's what we're working with for the next release. I would love to test it however I'm stuck with 1080p screens everywhere. Perhaps running Ubuntu in a 4K VM might work?

**Comment by tibbe** [comment]
Closed in favor of #345 against unstable.

**Pull request closed without merging**
