### PR TITLE
Calculate friction drag from TubeFinSet

### PR DESCRIPTION
**Pull request by JoePfeiffer**
beginning of a fix for #1207.  Note that after looking at the code, I don't regard 15.03's results as any sort of "ground truth"; we really need comparisons with actual data (or at least CFD) to know what's more accurate.

### CODE REVIEW

**Comment by neilweinstock** [comment]
Regrettably, I don't think we're likely to get test that will answer this question for us.  CFD is not out of the question, I suppose.  What would we want from a CFD model, would it just be a Cd number for an assortment of configurations?

in the near term I think if we can get results that are close to what Rocksim is yielding then it is an indicator that we're probably on the right track.

**Comment by hcraigmiller** [comment]
Would it be helpful to generate some comparisons between OpenRocket and Rocksim 10? If so, any particular specifications or just a variety.

**Comment by neilweinstock** [comment]
I do think a set of test files, along with the Rocksim results for us to compare against, would be very helpful indeed.

**Comment by JoePfeiffer** [comment]
It would be very helpful to see RockSim and RASAero (does RASAero do tube fins?) results for the attached rocket
[tubular.zip](https://github.com/openrocket/openrocket/files/8311355/tubular.zip)
Even before seeing the comparison that C6-7 result doesn't look reasonable.

**Comment by hcraigmiller** [comment]
Here is the comparison using Jean Nevada as the launch site for both.

Tube_Fins Compare Rev_01

**Comment by neilweinstock** [comment]
> Even before seeing the comparison that C6-7 result doesn't look reasonable.

Yeah that number is nuts... suggests frictionless fins.

Also noteworthy is the very significant difference in CP between OR and Rocksim, as shown in Craig's screenshot above.  And OR is showing *double* the speed off the rod, which makes no sense because max acceleration is almost identical between the two.  Maybe Rocksim is simulating a longer rod?

**Comment by JoePfeiffer** [comment]
Commented before my coffee. I haven't added the pressure drag calculation in yet. It does sound like there's a difference in launch rod length, also.

**Comment by hcraigmiller** [comment]
Launch parameters.

Tube_Fins Compare Rev_02

**Comment by neilweinstock** [comment]
Where's the rod length in Rocksim?

**Comment by hcraigmiller** [comment]
This is with 36" rods... all other conditions unchanged.

Tube_Fins Compare Rev_04

**Comment by hcraigmiller** [comment]
I went back and re-ran everything to ensure the launch rod length was the same.  Here are the results.

Tube_Fins Compare Rev_05

**Comment by hcraigmiller** [comment]
Oh, I forgot... RASAero II does not allow tube fins. I'm working on a hack to do a ring fin in RASAero II for comparison in the event that OpenRocket adds that feature.

**Comment by neilweinstock** [comment]
Interesting.  The rod speed numbers are closer now, but still much more different than I would expect, unless drag is making that much of a difference even at the relatively low speeds on the rod.

**Pull request closed without merging**
